### ISSUE TITLE
Give issues ids and permalink icons so they're linkable.

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#10]
Linking to issues is annoying.  Auto-add ids to issues, and a permalink icon like headings get.

Though, we preferably want the ids to be stable, so that linking to an issue doesn't go stale as soon as you add/remove an issue preceding it.  Hmm.  Maybe hash the contents with something simple?

**Comment by frivoal** [comment]
Just an idea to make this work even better.

Generating the id from a hash of the content works fine initially, but it would be nice to be able to edit an issue after having share the permalink with the rest of the world.

Maybe one way to do that would be that when you run "bikeshed source", it would embed the issue id in the source markup, so that later, even if the content of the issue changes, bikeshed can keep the permalink working.
