### ISSUE TITLE
Premature warning against the lack of a priv&sec section considered harmful

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1028]
The "This specification has neither a 'Security Considerations' nor a 'Privacy Considerations' section. Please consider adding both, see https://w3ctag.github.io/security-questionnaire/." warning should not be shown on immature drafts.

Please consider not having that warning if the spec isn't a CR or later status (or maybe any status plus Work Status >= Refining).

Otherwise, we risk writing a "No new security consideration" section just to silence bikeshed very early on in the spec's lifecycle, when most of its content isn't stable, and forget to actually consider the security considerations when the spec is mature enough to be actually evaluated for security problems.

I'm sure that you can come up with a generic enough way to declare that so that it can be set to kick in for CR for W3C specs, at whatever the appropriate stage is for other groups.

**Comment by mikewest** [comment]
I think it's reasonable to surface the question early on; thinking about these considerations early means that you can address them before the design has solidified into an implementation. If you're only adding these considerations at the point you hit CR, then it seems like you're quite likely to run into design constraints. CR is late. :(

**Comment by frivoal** [comment]
Yes, but Bikeshed doesn't make you think through it. It makes you add a dummy section without thinking about it when you're trying to get something else done and are annoyed at seeing the warning.

**Comment by mikewest** [comment]
Bikeshed warns that you don't have a security/privacy considerations section. It's not fatal, it doesn't stop you from compiling the document and moving on with your day. You're totally capable of silencing the warning by adding an empty section, but you're also capable of silencing the warning by jotting down some notes about things you'll need to address in the future, adding issues, etc. :)

**Comment by tabatkins** [comment]
Yeah, there's no way to force you to address it mechanically; a human review step with "a reasonable P&S section" on the checklist would do that, but that hopefully also happens (and is probably happening late, as @mikewest points out).  BS does the best it can; there are plenty of ways to silence its errors if you don't want to think about them, but that doesn't mean you're producing a good spec.

(Because of this, I'm fairly careful about adding new global warnings; I try to ensure they only show up for actual errors, and linting-style warnings are limited to when you affirmatively turn on a linting procedure.  This one is relatively important, tho, and not obvious to remember in my experience.)
