### ISSUE TITLE
Bikeshed strips-out SVG namespaces causing validation issue

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#1029]
There's an inlined SVG in the Bikeshed source: https://github.com/w3c/sensors/blob/9335c1f/index.bs#L735-L800.

Here's what it renders to with the latest release of Bikeshed (5eac41affc3976771f238ed8f80db1c877b65b40): https://gist.github.com/tobie/d4a0e43cc7781fec2daa933674d099f5

And here's the validator error I get when trying to publish with echidna: https://validator.w3.org/nu/?doc=http://owl.w3.org//916cf371-4630-491c-abd6-c663b65e6bbd/Overview.html ([echidna error](https://labs.w3.org/echidna/api/status?id=916cf371-4630-491c-abd6-c663b65e6bbd)).

It seems BIkeshed strips out the namespace part of the attribute.

**Comment by tabatkins** [comment]
Yeah, this is ultimately caused by LXML being fucking terrible with namespaces.  A namespaced tag or attr name is expressed as `{http://example.com/}foo` in the tree, rather than anything remotely sensible, so I just throw away the entire namespace part, since it's virtually never needed, and I can't actually reconstruct the namespace without doing some extra shenanigans (manually figuring out where a namespace declaration is, outputting it correctly, then tracking where that url is used in namespaced names and outputting the desired namespace name).

That said!  You never need namespace declarations in HTML.  The SVG-in-HTML parser ignores them entirely, and just looks for attributes that have the literal ns-prefix "xlink".  So you can just drop that xmlns:xlink attribute entirely.

**Comment by tobie** [comment]
That worked. Thanks!! :)
