### ISSUE TITLE
Line numbers for code

### ISSUE THREAD

**Issue by jfbastien** [tabatkins/bikeshed#1045]
I was trying to add `linenos` from Pygments: http://pygments.org/docs/formatters/
But that gets stripped from e.g. `<xmp>` IIUC. I think it has to be re-added like highlight language is?

Anyhow, what's the best way to activate line numbers for some code blocks?

**Comment by tabatkins** [comment]
Nah, per <https://github.com/tabatkins/bikeshed/issues/1043#issuecomment-309840453> I'm not using the right formatter for linenumbers to work out of the box.

But solving the "highlight lines" problem lets me solve the "number lines" problem almost for free, so yay!

**Comment by tabatkins** [comment]
Done.  Add `line-numbers` to an element or ancestor, or set the `Line Numbers` metadata to apply it to the whole document. (Use `no-line-numbers` to turn it off.)

**Comment by tabatkins** [comment]
And you can start the numbering from any value by setting `line-numbers=5` or whatever.

**Comment by tabatkins** [comment]
Never mind, moved that functionality to a new `line-start=5` attribute, to make it friendlier to the highlight-lines functionality.

**Comment by jfbastien** [comment]
Thanks! I tried it out on [the paper where this was desirable](https://github.com/jfbastien/papers/blob/master/source/P0690r0.bs) and it does something weird:

<img width="837" alt="screen shot 2017-06-29 at 09 08 10" src="https://user-images.githubusercontent.com/298127/27697946-8d7322c4-5caa-11e7-9819-44b474e94377.png">

I edited the `<xmp>` tags to `<xmp line-numbers>`. Looking at the generated HTML, it looks like it's grouping the zero-indent things separately, and all indented things are grouped under the preceding zero-indent thing. What's funny is that it *counts* correctly, but doesn't annotate. It even has per-line highlight and all!

I tried `<pre>` and it counted slightly differently but had a similar issue.

**Comment by tabatkins** [comment]
Fixed!

There were actually two errors that your document pointed out. The first, shown in your screenshots, is a consequence of the fact that if your newlines are contained in elements rather than being top-level text, I can't break it up into separate lines, and instead just do a single "line" wrapper around the whole sequence, with a number at the start and end.  Unfortunately, this was being caused by the *highlighter*, not your spec's code. Fixed that now so the highlighter never claims to highlight newlines.

Then second was shown in a couple of other blocks, where you had some overlapping line numbers. In fact, those were the empty lines in your source - I remove the newlines from the source and just rely on `div`s to create line-break-like behavior, but since the empty-line `div`s were totally empty, they were collapsing to zero height. I inserted a single space into them, and it's fixed.

**Comment by jfbastien** [comment]
Great! Tried it out, works wonderfully now. I can remove my silly numbering. Thanks 😁 

<img width="575" alt="screen shot 2017-06-29 at 15 46 43" src="https://user-images.githubusercontent.com/298127/27713792-2ec80b44-5ce2-11e7-930f-fd4fe56c9bf7.png">
