### ISSUE TITLE
Bikeshed echidna not producing output specberus wants

### ISSUE THREAD

**Issue by AngeloKai** [tabatkins/bikeshed#1046]
When I was trying to publish WD-05 for the Web Authentication API spec (https://github.com/w3c/webauthn/issues/486), I noticed bikeshed echidna is producing the spec with following text: 

```
<p>
  <em>
    This section describes the status of this document at the time of its publication.
    Other documents may supersede this document.
    A list of current <abbr title="World Wide Web Consortium">W3C</abbr> publications
    and the latest revision of this technical report can be found in the
    <a href="https://www.w3.org/TR/"><abbr title="World Wide Web Consortium">W3C</abbr>
    technical reports index</a> at https://www.w3.org/TR/.
  </em>
</p>
```

However, in specbreus, it says the text should be: 

```
<p>
  <em>
    This section describes the status of this document at the time of its publication.
    Other documents may supersede this document.
    A list of current W3C publications
    and the latest revision of this technical report can be found in the
    <a href="https://www.w3.org/TR/">W3C
    technical reports index</a> at https://www.w3.org/TR/.
  </em>
</p>
```

The difference resulted in specbreus never passing. Wendy helped file a bug on specbreus here: https://github.com/w3c/specberus/issues/622.

**Comment by tabatkins** [comment]
So do we want to fix the boilerplate to remove the `abbr`, or ping Specberus again to get them to fix this?

**Comment by tripu** [comment]
@AngeloKai, @tabatkins:

I must be missing something. According to https://github.com/w3c/webauthn/issues/486#issuecomment-306911763 and
[`https://lists.w3.org/Archives/Public/public-tr-notifications/2017May/0042.html`](https://lists.w3.org/Archives/Public/public-tr-notifications/2017May/0042.html)
, you tried to publish
[`https://www.w3.org/TR/2017/WD-webauthn-20170505/`](https://www.w3.org/TR/2017/WD-webauthn-20170505/)
, but Pubrules passes without errors for that document:
[`https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FWD-webauthn-20170505%2F&profile=WD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FWD-webauthn-20170505%2F&profile=WD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004)
&hellip;as it should, because [the rule cares only about the `.text()` content of that element](https://github.com/w3c/specberus/blob/master/lib/rules/sotd/supersedable.js#L19-L26), not about the markup.

Am I right?
(If not, it might be that the issue has been fixed in the meantime, after this issue was filed&hellip;)

**Comment by AngeloKai** [comment]
The current published draft https://www.w3.org/TR/2017/WD-webauthn-20170505/ is doing what specbreus says I should do. I guess either Wendy or someone else changed the text along the way. My guess is that if you replace with the below text, it won't pass. 

```
<p>
  <em>
    This section describes the status of this document at the time of its publication.
    Other documents may supersede this document.
    A list of current <abbr title="World Wide Web Consortium">W3C</abbr> publications
    and the latest revision of this technical report can be found in the
    <a href="https://www.w3.org/TR/"><abbr title="World Wide Web Consortium">W3C</abbr>
    technical reports index</a> at https://www.w3.org/TR/.
  </em>
</p>
```

**Comment by tripu** [comment]
I found the issue. The markup that webauthn WG submitted to Echidna on May 5 was not exactly what was reported here, but:

```html
<p>
  <em>
    This section describes the status of this document at the time of its publication.
    Other documents may supersede this document.
    A list of current <abbr title="World Wide Web Consortium">W3C</abbr> publications
    and the latest revision of this technical report can be found in the
    <a href="https://www.w3.org/TR/"><abbr title="World Wide Web Consortium">W3C</abbr>
    technical reports index</a> at http://www.w3.org/TR/.
  </em>
</p>
```

The problem there is that that last URI was `http` instead of `https` (not the two extra `<abbr>`).

I've been examining webauthn's build scripts ([`.travis.yml`](https://github.com/w3c/webauthn/blob/master/.travis.yml), [`.deploy-output.sh`](https://github.com/w3c/webauthn/blob/master/.deploy-output.sh)) and config ([`.bikeshed-include/status-WD.include`](https://github.com/w3c/webauthn/blob/master/.bikeshed-include/status-WD.include)) and Bikeshed sources ([`bikeshed/boilerplate/webauthn/status-WD.include`](https://github.com/tabatkins/bikeshed/blob/master/bikeshed/boilerplate/webauthn/status-WD.include)), and their history of changes, to try to find where/when exactly they fixed that issue&hellip; but I couldn't find it.

Anyway, their current builds (latest 2 days ago) [have that URL right](https://github.com/w3c/webauthn/blob/gh-pages/index.html#L308).

**Comment by tripu** [comment]
I think we can close this one, @tabatkins?
