### ISSUE TITLE
"bikeshed update" should be faster when there are no updates

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#1062]
As @tabatkins and I were just discussing, "bikeshed update" ought to be a good bit faster if there are no updates to be made, so that it's easier to run "bikeshed update" off of a cron job or similar and have it not waste too much work.

**Comment by tabatkins** [comment]
Would it be acceptable for me to run a cron hourly or so that generates and saves the data files to github, and then have `bikeshed update` default to fetching those files, rather than pulling down all the data sources and generating on the client side?  There'll still be an option to override and get an absolutely up-to-date version straight from the tap, but there's no good reason to pull down the entire data source every time all the time.  Then I can (a) only send the stuff that needs updating, and (b) slowly do diffing *on my own* rather than at the tap.

(Getting diffs from the data sources would be great, rather than pulling the entire thing each time, but that's a longer term project and would involve a few actors. I think this'll give most of the benefits in a much timelier manner.)

**Comment by dbaron** [comment]
It sounds reasonable to me.

The problem of having slightly out-of-date data seems less significant to me than the problem of updating multiple specs at once.  (I thought I'd filed an issue about that, i.e., about the ability to generate multiple specs at once and prefer references between generated-specs over references in the database, but I can't find it.)

**Comment by tabatkins** [comment]
Yeah, I ran into that last week too, and had to just push the files with broken refs and wait for Shepherd to iterate to stability. It's not great.  But it's also a way more complicated problem than this issue. ^_^

**Comment by tabatkins** [comment]
Having fun iterating toward this: instead of working on it directly, I've taught myself how Python packages work and refactored the updater accordingly, and moved a bunch of data file loading out of the critical path and instead lazy-load just the parts I need when I need them.  Shaved at least 20% off of the empty-file generation time!

This is working towards me splitting up the anchors.data file into pieces, and *then* putting together support for a manifest file that lets me update only the bits that are needed.

**Comment by tabatkins** [comment]
Okay, as of af6768e5 this should be working!  <https://github.com/tabatkins/bikeshed-data/> is a separate repo containing up-to-date information, updated several times an hour, and `bikeshed update` will check manifests against it to update only the parts that have changed.  (You can run `bikeshed update --force` to force a full update manually, and it'll fall back to a full update if anything errors out while doing a manifest-based update.)

Let me know if there are any problems!
