### ISSUE TITLE
ID for all autolinks probably broke whatwg/dom

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1066]
See this validation log: https://travis-ci.org/whatwg/dom/builds/261805947.

Suspect this is 2a0b31ce6dc9f47aedca34c2b82e3e1df9dbd69b.

**Comment by tabatkins** [comment]
Fuck, I spotted this quickly and fixed it, but it looks like I didn't push the fix. >_< Super sorry about that.

Since the computer I did it on isn't at hand, I redid the fix (it's pushed now, 3bc09468). To reduce the incidence of dedup'd IDs colliding with existing ones that happen to end with a number, I switched to deduping by appending an integer using unicode circled digits instead.  Please let me know if there are any further issues!

**Comment by tabatkins** [comment]
(That is, if I generate a bunch of `id="ref-for-foo"` attributes on the various links, they'll dedup to `id="ref-for-foo①"`, `id="ref-for-foo②"`, etc).
