### ISSUE TITLE
Fatal error in `bikeshed update`

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#1076]
Updating bikeshed now fails for me.

```
$ bikeshed update
Downloading anchor data...
FATAL ERROR: Couldn't save anchor database to disk.
[Errno 2] No such file or directory: '/Users/zcorpan/VCS/git/tabatkins/bikeshed/bikeshed/spec-data/anchors/anchors-gu.data'
 ✘  Did not generate, due to fatal errors
```

Regression from c96a1d6b6b488f46176d099093c00ce68a499cd5 maybe? Or do I need to fix/change something on my side?

**Comment by zcorpan** [comment]
I created the directory myself, and now it seems to succeed. But it seems the script should create it if it doesn't exist?

**Comment by tabatkins** [comment]
Yeah, sorry, I didn't properly add the folder to the commit. Will fix for
others as soon as I get to my desk.

On Aug 22, 2017 08:58, "Simon Pieters" <notifications@github.com> wrote:

I created the directory myself, and now it seems to succeed. But it seems
the script should create it if it doesn't exist?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tabatkins/bikeshed/issues/1076#issuecomment-324072076>,
or mute the thread

**Comment by tabatkins** [comment]
Done.
