### ISSUE TITLE
Regression-test against all known Bikeshed specs

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#1086]
My manually-written tests don't exercise all code paths, and I'm not optimistic they'll ever get there.  The variety of specs in the wild, however, pretty much do. I should be regression-testing against all the known specs.

**Comment by foolip** [comment]
Do you already have a list of all specs using Bikeshed?

**Comment by tabatkins** [comment]
Definitely not, I'm regularly surprised by where it gets used. But as a start we can grab all the csswg, Houdini, and whatwg specs, and can probably grep the W3C org for more .bs files.

**Comment by xfq** [comment]
A quick search: https://github.com/search?utf8=%E2%9C%93&q=org%3Aw3c+extension%3Abs&type=Code

**Comment by tabatkins** [comment]
Or here's the search minus all the CSSWG-related stuff, only 50 specs <https://github.com/search?utf8=%E2%9C%93&q=org%3Aw3c+extension%3Abs+-repo%3Aw3c%2Fcsswg-drafts+-repo%3Aw3c%2Ffxtf-drafts+-repo%3Aw3c%2Fcss-houdini-drafts&type=Code>

**Comment by jfbastien** [comment]
[Hai](https://github.com/jfbastien/papers/tree/master/source)

**Comment by foolip** [comment]
The branch https://github.com/foolip/bikeshed/tree/auto-test-update is now being updated daily by the scripts in https://github.com/foolip/bikeshed-tests. It has 197 .bs files.

One way of doing this might be to just merge all of that into Bikeshed weekly or so. Alternatively, Bikeshed's Travis job could pull in all of the .bs files and generate the HTML with and without the code changes in a PR, but then I don't know what should cause the job to fail, since some changes are correct.

@tabatkins?

**Comment by tabatkins** [comment]
Manually merged in the stuff.  foolip, when you're grabbing the tests, are you *generating* the .html files, or *grabbing* them from the repos?

**Comment by xfq** [comment]
The UI Events spec uses `<pre class=include>` to include the sections of the spec, but the `sections` directory isn't included in https://github.com/tabatkins/bikeshed/tree/master/tests/github/w3c/uievents
