### ISSUE TITLE
<dfn> inside highlight="idl" causes error

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1098]
```html
<pre highlight="idl">
  enum <dfn enum>TestEnum</dfn> {
    "test"
  };
</pre>
```
produces a
```
FATAL ERROR: IDL SYNTAX ERROR LINE: 1 - skipped: "TestEnum"
```

although it does successfully highlight the IDL as desired:

```html
<pre class="highlight"><span class="kt">enum</span> <dfn class="idl-code" data-dfn-type="enum" data-export="" id="enumdef-testenum"><code class="highlight"><span class="nv">TestEnum</span></code><a class="self-link" href="#enumdef-testenum"></a></dfn> {
  <span class="s">"test"</span>
};
</pre>
```

I'd like to use this in https://w3c.github.io/permissions/#permission-registry to link to permissions defined outside the permissions spec.

**Comment by tabatkins** [comment]
Ah, found it - the `<dfn enum>` gets highlighted, and it autodetects (due to its parent having `highlight=idl`) that it should highlight as IDL; parsing then (correctly) fails, as `"TestEnum"` isn't valid WebIDL by itself.

I'll see what I can do to correct recognize this as something that shouldn't be explicitly highlighted.
