### ISSUE TITLE
Add support for basic tables

### ISSUE THREAD

**Issue by cconcolato** [tabatkins/bikeshed#1128]
The class 'propdef' adds a bunch of table entries (applies to ...). It would be good to have a basic table generation, that does not add 'Applies to:', 'Percentages ...

**Comment by sandersaares** [comment]
This would also be very valuable to me. Supporting, for example, Markdown table syntax would be relatively nice and universal.

**Comment by tabatkins** [comment]
@sandersaares That's a very different request than what @cconcolato is making. Markdown tables are not part of CommonMark, they're significantly complex to parse, and save you fairly little over an ordinary HTML table with all ending tags omitted.  I'm not currently planning to add them.

@cconcolato is just asking for the ability to generate a simple two-column table with simple string keys, identical to the current propdef/etc tables but unconstrained in the names/values used.  That's quite easy to do, since I already have all the parsing support set up for it.  (But it's also pretty easy to do with a plain HTML table with a `class=def`, which is all that triggers the styling.)

**Comment by brycelelbach** [comment]
I'd really, really, really like to have tables, akin to what github flavored markdown supports. This is a common ask from the C++ committee folks using bikeshed.

**Comment by tabatkins** [comment]
I continue to suspect that this support is purely a result of people being scared to use HTML properly.  Just omit your end-tags, people! It's not hard!

```
<table>
 <tr><th>foo<td>1<td>2<td>3
 ...
 <thead>
  <tr><th>headings<th>first<th>second
</table>
```
(Or you can put your `<thead>` first to reflect how it'll look on the page, but then you either need to close it with a `</thead>`, or manually add a `<tbody>` (the markup I provided implicitly adds one).)

**Comment by slurps-mad-rips** [comment]
Would like to agree with @brycelelbach. As someone writing a large quantity of papers for WG21, I shouldn't have to spend time write raw HTML for a text preprocessing tool. restructuredText supports tables, CommonMark has tables, GitHub has tables, and a variety of other markdown flavors do too. It's not a question of whether I want to use HTML properly or understand it, it's a question of "Why should I spend time writing raw HTML when I could have something that is close to the visual representation of what the content will eventually look like?". My papers and proposals are about the content, not spending time writing markup. This is an extremely painful thing that might cause me to encourage others to move away from bikeshed when restructuredText and other markdown engines handle with ease.

**Comment by tabatkins** [comment]
CommonMark doesn't have tables.

I'm still of the opinion that the difference between ascii tables and html tables is much smaller than y'all are pretending, and the few extra chars required for an html table is balanced by the fact that you don't need to spent extra time re-aligning column widths when things change, or worrying about escaped characters, or wondering how to rewrite when things get larger than you want to display in an ascii form.

To wit:

```
| foo  |  bar | baz  |
+------+------+------+
| r1c1 | r1c2 | r1c3 |
| r2c1 | r2c2 | r2c3 |
```

is basically equivalent in complexity to

```html
<table>
 <thead>
  <tr><td>foo<td>bar<td>baz
 </thead>
 <tr><td>r1c1<td>r1c2<td>r1c3
 <tr><td>r2c1<td>r2c2<td>r2c3
</table>
```

In these simplest of cases, the HTML looks a little more complex, but that's ignoring the fact that you have to spend effort going back and re-aligning the ascii to make it look pretty. Check out what happens when you *don't* do that:

```
| foo | bar | baz |
+-----+-----+-----+
| first row, first col | first row, second col | first row, third col |
| row 2, col 1 | row 2, col 2 | row 2, col 3 |
| 3rd row, 1st col | 3rd row, 2nd col | 3rd row, 3rd col |
```

Hoo boy, that's terrible to look at! And if you want to make it pretty, you can't predict ahead of time how many padding-spaces to put into each cell; you have to wait until you're totally done, and then go back and align them column-by-column.

-----

And the character escapes! You probably *expect* something like the following to work:

```
| foo               | bar                   |
+-------------------+-----------------------+
| <b>a | bolded</b> | <i>a | italicized</i> |
```

(I even lined up the cells all pretty to guide your eyes properly.)

But it's unclear if it does! Is the table processing done *before* or *after* HTML processing, or intertwingled?  We can make it worse by instead using markdown inline styling, `**a | bolded**` and `* a | italicized*`, so now you have to worry even more about relative precedence *within the markdown constructs*. And the answer that normal markdown gives for accidentally-intertwined inline constructs (like `one *two **three* four** five `) is that the starting one wins, and then negates the second one (the previous actually emits `one <i>two <i><i>three</i> four</i></i> five`; seems a little weird, like the matching went degenerate, but that's the spec). This would *not* match your intuition for the above! It would instead split the row into *four cells*.

Other markdown block-level syntaxes don't have this problem, because their structure is denoted *purely* by **line prefixes**. The *rest* of the line is entirely free-form, and free to be full of arbitrary contents and inline markdown syntaxes, and following lines can be used to extend the block without added complexity, as long as you don't start following lines with a block-prefix indicator. Tables are the only construct with these problems.

-----

And what if you *started* with nice short cell contents that each take up only a fraction of a line, but later had to extend one so it has several lines of text? There's no way to align those; you'd have to deal with multiline cells instead, which means manually breaking your lines at small widths, *and* means that now we require row indicators so we know when a cells spans multiple lines of text. So the initial example changes to:

```
| foo  |  bar | baz  |
+------+------+------+
| r1c1 | r1c2 | r1c3 |
+------+------+------+
| r2c1 | r2c2 | r2c3 |
```

Now it's more typing, more aligning to make things pretty and actually look like an ascii table. The benefits of short ascii tables get gradually eaten away!

One might say "well, just turn it into a `<table>` at that point" and sure, that's possible. But then you have to pay the cost of a complete syntax rewrite for that section. I try my best to avoid that sort of thing in Bikeshed-flavored Markdown, with things like wrapping a markdown-list in a `<ul>` so you can put attributes on it.  I'm even considering a way to let you intermix `<li>` into markdown lists, when you need to add attributes to a single list item; complex, but not too bad, and worth it for the saved rewrite. But switching over single rows of an ASCII table to HTML sounds... much more fraught, and more difficult to read.

------

On the other hand, just writing HTML tables from the start, and omitting all the end-tags that you can, means that you get *pretty* compact when you have small tables (you pay a few more chars for the cell separators), but you don't have to go back and align things at the end (and then re-align when you make any edits), and it automatically works well with other markdown, with longer contents, etc.

-----

Ultimately, if *tables* are the thing that makes you throw Bikeshed away in favor of substantially lesser tools, that's unfortunate. But I'm sticking to my guns here: ASCII tables aren't part of CommonMark for *good reasons*, and HTML tables are *easy and lightweight* if you omit endtags like you should.

Bikeshed-flavored Markdown is intentionally extra-compatible with raw HTML precisely so that we don't have to try to cram everything into Markdown-ified syntaxes; we can support what Markdown does well - writing plainish text with simple ascii-art formatting - and then leave the rest to HTML, which can handle a lot of nonsense in a simple and unambiguous, albeit slightly longer and more code-ish, fashion.

**Comment by tabatkins** [comment]
Something I probably *would* consider supporting is adding a new type of `<pre>` block intended for ascii-art boxes, that automatically transforms `-`, `|`, and `+` into the appropriate box-drawing characters.  You'd have to use normal HTML to get links and stuff, but it would let you draw simple ascii-art tables if you wanted.

**Comment by sandersaares** [comment]
I agree with your analysis on the formatting merits of this feature. Personally I tend to prefer HTML tables.

However, there are also non-formatting merits that, I think, play a far greater role here: people familiar with Markdown expect Markdown tables to work. That's all the reason there is to me wanting it. I don't want my document authors to be surprised that their tables do not work.

This is about avoiding surprises - if users are more comfortable using a somewhat inferior style of formatting, they should be enabled that capability unless it carries unreasonable maintenance burden (which I suppose it may - I have no idea how any of the formatting is implemented).

**Comment by ryanthompson591** [comment]
I would like to add a vote here for common markdown tables.  I work with an IAB working group using bikeshed and I had to come here to figure out we couldn't use tables.  A lot of our table creation is simple and would be much more easily maintained with markdown tables.

I suppose I am stuck with html for now.

I was surprised markdown tables didn't work and had to come here to figure it out.

**Comment by RedBeard0531** [comment]
An additional reason to support gfm-style tables that I'm dealing with right now is taking an existing large document from hackmd.io that uses those tables and turn it in into a bikeshed paper. Not having gfm table support makes this much harder.

**Comment by jfbastien** [comment]
Sounds like lots of folks want gfm-style tables, and @tabatkins find table markup distasteful. One good thing gfm has going for it is a spec, [including one for tables](https://github.github.com/gfm/#tables-extension-). I doubt Tab would implement something they find distasteful, but with this horde of people clamoring for it I'd bet that a good pull request would go a long way.

**Comment by tabatkins** [comment]
Yeah, if my arm was twisted, I'd be willing to support GFM tables. They give you the basic functionality of tables with small, short cells. No line-breaking, no block-level markup, and an overall textual design that's on the more minimal side.

It's still a *bad idea*, and people just need to learn to love omitting end tags on internal table elements, but still. ^_^

Note that, because there *is* no standard for "markdown" tables, there's no guarantee that moving a table from another type of markdown+ language to bikeshed-flavored markdown will work. But most simple ones will, sure.

**Comment by cconcolato** [comment]
@tabatkins any chance of seeing progress on this issue?

**Comment by tabatkins** [comment]
It's been a while, but I've finally added support for the simple def tables requested in the OP. ^_^

You can now write things like 

```html
<pre class="def">
first: something
second: something else
second: merged into previous line
</pre>
```

and it'll be formatted like the other specialized *def tables, as a 2-col table.

[The docs](https://tabatkins.github.io/bikeshed/#def-block) explain the particulars of the parsing.
