### ISSUE TITLE
Strange error with text macros containing quotes

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1162]
The following fails:

```
curl https://api.csswg.org/bikeshed/ -f -F file=@url.bs > url.html -F md-Text-Macro="SNAPSHOT-LINK <a href=\"/\">Test</a>"
```

The folllowing succeeds:

```
curl https://api.csswg.org/bikeshed/ -f -F file=@url.bs > url.html -F md-Text-Macro="SNAPSHOT-LINK <a href=/>Test</a>"
```

This is using url.bs from https://github.com/whatwg/url/pull/360.

The error is

```
Error running preprocessor, returned code: 1.
\033[1;31mFATAL ERROR:\033[0m Error loading default metadata:
Expecting ',' delimiter: line 10 column 15 (char 492)
\033[7;31m Γ£ÿ \033[0m Did not generate, due to fatal errors
```

This was not a problem before #1155, for some reason.

**Comment by tabatkins** [comment]
Ah, yay for dumb text substitution!

The problem here is that your macro string is just nakedly substituted into your computed-metadata JSON file. That file is using double-quotes around its strings. Sub in double-quotes there, and you get broken JSON.

I *could* maybe run a json-escape on the values you pass in. The problem is that I have no idea what context you're substituting the values in - maybe it's inside a string, maybe it's a plain value, etc. You might set up the macro intentionally as a JSON array, for example, intending it to be an actual array in your computed-metadata file. So I don't think I can really do that.

Fix for now is to either use single quotes in your macro, or double-escape the quotes, once for JSON and then once for the command line.

I'll catch that JSON error tho, and output a better error message.

**Comment by domenic** [comment]
It seems when substituting the value inside a JSON file, you should JSON escape it... Or, you could perform substitution after pulling them out of the JSON file (but before using them for any other purpose).

**Comment by tabatkins** [comment]
The problem with that is, as I said, I currently have no way of knowing that the value is going to be used inside of a JSON string. I could *assume* that, but I'm not sure how valid it would be.

(You run into an exactly identical problem with macros in your HTML - maybe the macro is plain text, maybe it's an attribute value, maybe it's HTML, and there's no way for me to know ahead of time and thus escape automatically. You have to escape things the correct amount by hand, instead.)

**Comment by domenic** [comment]
I mean, you're substituting into a .json file... you should know that at some point.

**Comment by tabatkins** [comment]
Sure, if I was doing the JSON parsing with my own custom parser, and filling in the substitutions as I go, I'd know what context each substitution appeared in and would be able to escape automatically. I'm not doing that, because it would be fairly silly - I'm doing one naive text-substitution pass before handing it over to Python's JSON parser.  It would be a good bit of wheel-reinventing to write my own JSON parser.

**Comment by domenic** [comment]
In other words, one of two options:

```
if (isJSONFile) {
  macros = escape(macros);
  doSubstitution(jsonFile, macros);
}
result = parseJSON(jsonFile);
```

or

```js
result = parseJSON(jsonFile);
doSubstitution(result, macros);
```

**Comment by domenic** [comment]
I see, your issue with my first option is that the macro could be a ... number or null? With quotation marks in them? I think we can assume that won't happen.

**Comment by tabatkins** [comment]
Nah, the possibility I'm worried about is someone using a macro to pass an array containing strings (as allowed in the structure), or passing in an entire key/value pair.

**Comment by domenic** [comment]
I guess if that's an intended use case then double-escaping makes sense, but I'd rather give up that use case myself so that the contents of text macros can be used in multiple different places. E.g. if I double-escaped then I used [SNAPSHOT-LINK] inside my .bs file as text content, it would have the backslashes in the .html output, which seems bad.

**Comment by tabatkins** [comment]
Hmm, that's probably reasonable. Okay, I'll do the JSON string-escaping and just hope for the best.

**Comment by tabatkins** [comment]
And done. Looks like it works fine, let me know if there are any problems.

**Comment by domenic** [comment]
Confirmed working, yay!
