### ISSUE TITLE
Metadata passed in from the API does not override computed metadata; it should

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1163]
E.g.

```
curl https://api.csswg.org/bikeshed/ -f -F file=@url.bs -F md-status=LS-COMMIT \
     -F md-title="URL Standard (Commit Snapshot deadb33f)" \
     > "index.html";
```

still has a `<title>` of "URL Standard".

**Comment by tabatkins** [comment]
By definition it can't, because computed metadata can be affected by metadata passed in the command line (a feature you are currently using in the WHATWG boilerplate!).

**Comment by domenic** [comment]
Can we add some way to override?

**Comment by tabatkins** [comment]
Wait, my previous objection didn't make sense - I already do the out-of-order thing, where I have to compute the in-document Group metadata to know what defaults.metadata to load.

I can still make command-line show up last, then. Heck, I can fix your earlier issue about wanting computed-metadata to show up before in-document metadata (because you're right, it's still more generic than the individual document's metadata).

**Comment by domenic** [comment]
Hmm OK, that sounds lovely, although be sure not to break the feature we're using where (as you pointed out) we're passing in a text macro from the command line which ends up substituted into computed metadata!

**Comment by tabatkins** [comment]
Yeah, that's fine - metadata sources are monoids, so I can (and do) just recombine them arbitrarily at any point.  (The current code combines the baseline, in-document, and command-line metadatas, then uses that to load the defaults, then combines the defaults in, then uses that to sub and load the computed-metadata, then combines that in, etc.)

**Comment by tabatkins** [comment]
Done; let me know if there are any problems.

**Comment by domenic** [comment]
Confirmed working, yay!
