### ISSUE TITLE
How to add a favicon to the spec?

### ISSUE THREAD

**Issue by beaufortfrancois** [tabatkins/bikeshed#1175]
I'm not sure how to easily add a favicon to the bikeshed generated html file.
I wish it would be as simple as something like:

```diff
<pre class='metadata'>
Title: My First spec
Shortname: my-first-spec
Level: 1
Status: ED
+ Favicon: https://example.com/favicon.ico
</pre>
```

**Comment by tabatkins** [comment]
Currently it's based entirely on your boilerplate files - if the `header.include` file for your group has a favicon in it, it's done. I don't yet have something that'll add a favicon to an arbitrary file, but I'm definitly not opposed to the idea.  Your proposed syntax looks good to me.

**Comment by beaufortfrancois** [comment]
I'd be happy to start a PR if you could share with me some hints on where to start.

**Comment by tabatkins** [comment]
Sure! So you'd edit `metadata.py` to add the new metadata - you probably don't need to write a new parsing function, since you'll just be taking the value literally with the assumption that it's a single URL. Note that it needs to be added at the top of the file, in the MetadataManager class, and at the bottom, in the collection of metadata objects.  (At some point we'd probably want to add some more options, since favicons are actually kinda complex, but it's fine to start with the "single url" solution.)

Then edit boilerplate.py to add a new function that adds a favicon `meta` if the favicon metadata is set. Add a call to it in an appropriate spot in Spec.py/preprocess() - there's a whole block of boilerplate calls in there where it would be appropriate.

**Comment by beaufortfrancois** [comment]
Thank you @tabatkins!
I've just submitted https://github.com/tabatkins/bikeshed/pull/1177 PR. Let me know what you think of it.

**Comment by beaufortfrancois** [comment]
QQ: Is it going to be available in https://api.csswg.org/bikeshed/ right away?

**Comment by tabatkins** [comment]
Very shortly, the API server has a commit hook, so whenever the to get around to talking to each other.
