### ISSUE TITLE
sequence<unsigned long> and record<DOMString, double> not handled

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1191]
In https://github.com/tabatkins/web-audio-api, there is an attribute of type `sequence<unsigned long>` and bikeshed complains:

>LINK ERROR: No 'idl-name' refs found for 'sequence<unsigned long>'.
<a data-link-type="idl-name" data-lt="sequence&lt;unsigned long&gt;">sequence&lt;unsigned long&gt;</a>

Similarly we get an error for `record<DOMString, double>`:

>LINK ERROR: No 'idl-name' refs found for 'record<DOMString, double>'.
<a data-link-type="idl-name" data-lt="record&lt;DOMString, double&gt;">record&lt;DOMString, double&gt;</a>

**Comment by rtoy** [comment]
I see that in the IDL section, `sequence<unsigned long>` and `record<DOMString, double>` are correctly linked to the corresponding sections of WebIDL.  These are the types of a member of a dictionary and in the description of these members, the type isn't linked.  But the links to the types like `unsigned long` of other members of the dictionary are correctly linked.

**Comment by rtoy** [comment]
For an example, see https://rawgit.com/tabatkins/web-audio-api/gh-pages/index.html#dictdef-audioworkletnodeoptions

**Comment by equalsJeffH** [comment]
we are getting this error when building the webauthn spec:
```
 LINK ERROR: No 'idl-name' refs found for 'record<USVString, AuthenticationExtensionsPRFValues>'.
<a data-link-type="idl-name" data-lt="record&lt;USVString, AuthenticationExtensionsPRFValues&gt;">record&lt;USVString, AuthenticationExtensionsPRFValues&gt;</a>
```
the spec source is:
```
    dictionary AuthenticationExtensionsPRFInputs {
        AuthenticationExtensionsPRFValues eval;
        record<USVString, AuthenticationExtensionsPRFValues> evalByCredential;
    };
```
...which is a problem because the echidna toolchain does not allow there to be any errors or warnings.

Trying to workaround this particular error by including an explicit reference `{{evalByCredential}}` does not cause the link error to go away.

**Comment by tabatkins** [comment]
Tracked the error down and properly fixed it - and sorry for taking two years to do so, @rtoy!

So this was being caused by the code that adds attribute/dictmember info to the definitions when you put them in a `dl`; I wasn't properly bailing on some "complex" typenames (like `record<foo, bar>`) that aren't actually linkable.

Code now handles "simple" `record<>` stuff (if the two types are just typenames), and properly bails on all future unions and more complex higher-kind types that I'm not explicitly handling.

**Comment by equalsJeffH** [comment]
great, thanks Tab!  will try it out....

**Comment by rtoy** [comment]
Thanks great!  A few more WebAudio bikeshed errors gone!  Slowly getting closer to a clean build of the WebAudio spec.
