### ISSUE TITLE
{{Cache}} causes service-workers-1 in the biblio, even with default biblio status: current

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1196]
Example: https://github.com/domenic/async-local-storage/blob/e4b47d6f3a6801f83b8e0408d1fb2fd20c71cac6/spec.bs (see https://github.com/domenic/async-local-storage/blob/e4b47d6f3a6801f83b8e0408d1fb2fd20c71cac6/spec.bs#L95 and https://github.com/domenic/async-local-storage/blob/e4b47d6f3a6801f83b8e0408d1fb2fd20c71cac6/spec.bs#L14); unfortnuate output at https://domenic.github.io/async-local-storage/#informative

**Comment by tabatkins** [comment]
Ah, you're running into #906.  `service-workers-2` doesn't exist in SpecRef, but `service-workers` does (as an alias for `service-workers-1`), so it helpfully tries to refer to that instead in the bibliography/index.

**Comment by tabatkins** [comment]
I'm gonna close this as a duplicate; when #906 is fixed this'll just come up as an error, so what you really want to do is get this into SpecRef.

**Comment by tabatkins** [comment]
Okay, fixed #906. Turns out this ends up doing an okay thing for your spec - you just get the "fake biblio" generated from the information that Shepherd has about the spec.  It would still be better to actually get service-workers-2 into SpecRef, because while you can autolink into the spec, you can't do a `[[service-workers-2]]` biblio autolink.  (It'll, rightfully, report that it doesn't know about that spec.)
