### ISSUE TITLE
Do a real parse of the tag to classify data-blocks, rather than looking for substrings

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#1207]
The auto-updating of tests has broken since https://travis-ci.org/foolip/bikeshed-tests/builds/354146090 and it appears to be because of the change in cssom to use Web IDL mixins:
https://github.com/w3c/csswg-drafts/pull/2123

**Comment by tabatkins** [comment]
Bug is that once Bikeshed realizes a line is starting a data-block (starts with `<pre`), it just looks to see if the appropriate class appears anywhere in the text of the line; in this case it's seeing "include" and assuming it's an include-block. (This *should* only be firing for `class=include`.) It then fails to parse as an include-block, and then hits some other error which actually makes Python complain, which I *also* need to fix.

But the fix for this is to bite the bullet and actually parse the tag per HTML; this part of the HTML parser is pretty simple and should be okay to do by hand.

(I do data-block processing before handing things to the HTML parser, so can include text that would make HTML unhappy.)
