### ISSUE TITLE
script-dfn-panel interferes with fixup.js

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#1335]
fixup.js goes to some lengths to make the sidebar ToC less annoying. For example, when you are in a narrow window such that the ToC sidebar floats over the content, it goes away automatically when you click on a link. https://www.w3.org/StyleSheets/TR/2016/readme.html However this functionality is broken in CSS specs, and the culprit seems to be something in script-dfn-panel.

Please fix Bikeshed to not break things.
Thanks~

**Comment by tabatkins** [comment]
Ah, nope, this isn't anything about Bikeshed at all; it's fixup.js that's broken.  The problem is in the listener on line 118:

```javascript
toc.addEventListener('click', function(e) {
  if(e.target.tagName.toLowerCase() == "a" && 
     document.body.classList.contains('toc-sidebar') && 
     !sidebarMedia.matches) {
    toggleSidebar(false);
  }
}, false);
```

The first check (`e.target.tagName.toLowerCase() == "a"`) fails if you click on the *text* of the ToC entry, because then the target is a `span`; you have to click outside of the text but within the highlighted area for this condition to pass and for it to close.

You can observe this in, for example, <https://www.w3.org/TR/2018/WD-geolocation-sensor-20180821/#geolocationsensor-interface> - Ctrl-+ until the sidebar hides by default, then open it and try clicking directly on the text of any entry; it won't auto-close. Then do the same on <https://drafts.csswg.org/css-values/>, same result. Try clicking *off* the text, tho, and both of them auto-close.

The only reason you're noticing this more often on CSS specs is that we tend to have longer section titles than most specs, so it's more likely you're clicking on text.

The fix is pretty simple:

```javascript
toc.addEventListener('click', function(e) {
	if(document.body.classList.contains('toc-sidebar') && !sidebarMedia.matches) {
		// Only toggle-off if an <a> was clicked.
		var el = e.target;
		while(el != toc) {
			if(el.tagName.toLowerCase() == "a") {
				toggleSidebar(false);
				return;
			}
			el = el.parentElement;
		}
	}
}, false);
```

It's even easier if we want to rely on `el.closest()`, as then we can just take the original code and replace the first check with `e.target.closest("a")`, but that won't work in pre-Edge IE.

**Comment by fantasai** [comment]
Geolocation is Bikeshed-generated, fwiw, so I'm not sure comparing it to a CSS spec which is also Bikeshed-generated makes much sense. ^_^ An example of a non-Bikeshedded spec would be TTML https://www.w3.org/TR/ttml2/ (which auto-closes as expected).

So the issue is that fixup.js works fine on specs that don't have additional markup generated within their toc entries, but Bikeshed adds such markup, breaking the script. But it's fixup.js that should be fixed here, because it _should_ be general enough to handle additional markup.

**Comment by tabatkins** [comment]
Ah, thanks, I just grabbed the most recently published spec from /TR; I didn't pay attention to what generated it. ^_^

And note that the problem definitely still exists in the TTML spec, you're just less likely to hit it - click on the *section number* in the ToC, and you'll navigate the document, but it won't auto-close, for exactly the same reason (the section number is in a `span`).

**Comment by tabatkins** [comment]
And yeah, given that ToCs are generated from headings, if you have any further markup in your heading, such as a `code` element, that'll stop fixup.js from working too.
