### ISSUE TITLE
bikeshed test --rebase broken with tests in tree

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#1376]
https://github.com/tabatkins/bikeshed/pull/1281 is the latest automatic test update, and since then it hasn't been possible to automatically create these PRs. Here's the latest failure:
https://travis-ci.com/foolip/bikeshed-tests/builds/89472279

The reason is that `bikeshed test --rebase` doesn't even work with the tests that are in the tree and that haven't changed.

I've bisected `bikeshed test --rebase tests/github/w3c/webappsec-suborigins/index.bs`breakage down to commit 6127abccc3dd74e68b797f65d2311489a7c30893 from July 27.

After the tests have been fixed, tests should ideally run on every PR and push to master to prevent this from happening.

**Comment by foolip** [comment]
It's possible this is a macOS problem, at least that's where I discovered it.

**Comment by tabatkins** [comment]
I think I see the problem. 6127abc changes things so that when you list tests manually, you just provide the test name (or subpath below the `bikeshed/tests/` folder), and it prefixes the appropriate path automatically. This way you don't have to run the command from any particular folder, or type unnecessary common path prefixes if you're rebasing several.

But `find tests/github -type f`, run from the bikeshed root folder, returns paths like `tests/github/...` - in other words, they have the `tests/` prefix already on them, in addition to the subpath I was expecting. So then Bikeshed auto-corrects them to basically `bikeshed/tests/tests/github/...`, which obviously fails to point to a file.  (I need to produce a better error message for that; failing at a later point because there's no text is a bad and confusing error.)

I think the correct fix is to `cd` into the `tests` folder before running the `find` command; that should produce filepaths without the extraneous prefix.

**Comment by foolip** [comment]
Ah, I can fix that!

**Comment by foolip** [comment]
I fixed it! https://github.com/tabatkins/bikeshed/pull/1380
