### ISSUE TITLE
<ul> missing from list for no obvious reason

### ISSUE THREAD

**Issue by sandersaares** [tabatkins/bikeshed#1377]
Given the following document snippet:

```
<table class="def">
	<tr>
		<td>xxxxxxxxxxxxx</td>
		<td>

* xxxx
* xxxxxx
* xxxxxxxxx

		</td>
	</tr>
	<tr>
		<td>xxxxxxxxxxxxxxxx</td>
		<td>

* xxxxxxx
* xxxxxxxxxxxx
* xxxxxxxxx
* xxxxxxxxxxxxxx

xxxxxxxxxxxxxxxxxxxxx

		</td>
	</tr>
	<tr>
		<td>xxxxxxxxxxxxxxxx</td>
		<td>

* xxxxxxxxxx
* xxxxxxxxxx
* xxxxxxxxxx

xxxxxxxxxxxxxxxx

		</td>
	</tr>
</table>
```

I see the following output:

![image](https://user-images.githubusercontent.com/9914262/47771723-10ae0500-dced-11e8-998f-f5a7941a5009.png)

Investigation of HTML indicates that the middle row is missing the `<ul>` and just has a plain sequence of `<li>` elements.

I would expect the middle row to also have the `<ul>` element just like the first and third row.

**Comment by tabatkins** [comment]
The problem here is that Bikeshed *does* care about indentation in the Markdown pass. In this case, all the markup between the first and second lists is, due to it being sufficiently indented, considered as just part of the third list item of the first list.  The rest of the list items are then just continuing that first list, since nothing has ended it yet.

(Interestingly, it's not auto-closing when there's two blank lines, either. That's a bug on my part.)

There's no reason to put the lists up against the margin like that; it's less readable *and* it messes with how things get interpreted. Just indent it like you would anything else.

**Comment by sandersaares** [comment]
Thank you for the fast answer!
