### ISSUE TITLE
Bikeshed thinks empty lines in the middle of an svg start a new paragraph

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1403]
There seems to be a weird parsing bug in Bikeshed that corrupts svg elements when there's empty lines in the, as it seems to thing that these are new paragraphs.

Try to put in an empty document the SVG illustration found in section https://w3c.github.io/w3process/#recs-and-notes of the W3C process, and see what bikshed does with it.

Removing empty lines helps. That shouldn't be needed. If the SVG is well formed, bikeshed should just leave it alone and not try to interpret the content. (and if it is not well formed, it should just fatal error).

**Comment by NicolasRouquette** [comment]
I'm experiencing a related problem with SVG images generated from [Plant UML](http://plantuml.com/index). 

In my case, the SVG images have hyperlinks to other parts of the bikeshed document.
I found that for these hyperlinks to work with bikeshed, I need to include such diagrams like this:

```
<pre class=include>
path: diagram.svg
</pre>
```

If I do instead:

```
<img src="diagram.svg"/>
```

then the hyperlinks don't work.

However, with the include technique, then bikeshed parses the svg diagram as if it were a bikeshed source file. This end up not working at all; regardless of whether I format the svg file beforehand or leave it as is. Either way, bikeshed dies because it thinks that something is not properly indented.

As a proof-of-concept, I disabled the indentation check in `bikeshed/mardown.py` like this:

```

def stripPrefix(token, numSpacesForIndentation, len):
    '''Removes len number of prefix groups'''

    text = token['line'].text

    # Don't mess with "infinite" prefix lines
    if token['prefixlen'] == float('inf'):
        return text

    # Allow empty lines
    if text.strip() == "":
        return text

    offset = 0
    for x in range(len):
        if text[offset] == "\t":
            offset += 1
        elif text[offset:offset + numSpacesForIndentation] == " " * numSpacesForIndentation:
            offset += numSpacesForIndentation
        else:
            offset += numSpacesForIndentation
            # die("Line {i} isn't indented enough (needs {0} indent{plural}) to be valid Markdown:\n\"{1}\"", len, text[:-1], plural="" if len == 1 else "s", i=token['line'].i)
    return text[offset:]
```

See the commented line `die(...)`.
This is obviously not something we want to do for all include files but at least it makes bikeshed work properly with including several svg diagrams with hyperlinks.

So, I think that a way to proceed is to have a special include mode for svg, e.g., something like:

```
<pre class=include-html>
path: diagram.svg
</pre>
```

where `include-raw` would not attempt to parse the included document as if it were legal bikeshed syntax but instead "trust" that it must be legal HTML.

Opinions?

**Comment by NicolasRouquette** [comment]
FYI: I've been able to include SVG images w/ links made with [draw.io](https://www.draw.io/) without any problems.

**Comment by tabatkins** [comment]
Note that Bikeshed is, first, a Markdown processor that happens to be very good at HTML. Markdown rules come first, which means that blank lines can cause subsequent content to be treated as the start of a paragraph.  If you're including the SVG inline, you need to remove the blank lines, same as in HTML.

(Note that starting a line with any non-inline start tag, like `<div>`/`<table>`/etc, will prevent it from assuming you're starting a paragraph. It's just inline tags and raw text that trigger that behavior.)

Now, if your SVG is in an external file, you can use the `<pre class=include-raw>` feature I recently added to emit it directly into the document to be parsed as HTML, without the Markdown pass. Then you don't need to do any editting of the SVG at all.

(You can even include full standalone SVG documents that way, since they'll still generally be valid HTML, and any PIs you have in the doc will get ignored by the parser and not emitted by the serializer.)
