### ISSUE TITLE
<<type>> notation breaks ''notation''

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#1425]
I'm not sure if this is a bug or working as intended, but `''minmax(auto, <<flex>>)''` in the Grid draft isn't working. See end of the `<<flex>>` definition in https://drafts.csswg.org/css-grid-1/#valdef-grid-template-columns-flex

**Comment by tabatkins** [comment]
Known bug due to the current layering of shorthand parsing: if you happen to nest shorthands in the order that they get parsed in, you're fine; if not, the inner shorthand parses and breaks up the outer one into separate text fragments, which then don't parse.

I can't find the original issue for this, but there's something tracking it already. This'll be fixed this year as I rewrite the HTML/markdown parser.
