### ISSUE TITLE
Unsafe usage of lxml

### ISSUE THREAD

**Issue by scoder** [tabatkins/bikeshed#1445]
I stumbled over this code while investigating WebAudio/web-audio-api#1830:
```
def clearContents(el):
    for child in el.iterchildren():
        el.remove(child)
    el.text = ''
    return el
```
It assumes that removing a child does not interfere with iteration, but lxml does not give this guarantee. Why not just use `del el[:]` ? There's also `el.clear()`, but that clears the complete element, including its tail text, which might not be intended here.

Also take care of where this function is used. As with most data structures, it is generally not a good idea to structurally modify elements while iterating over them. It can lead to leaving out elements, prematurely terminating the iteration, or other kinds of unintended behaviour.

**Comment by tabatkins** [comment]
Hm, I didn't realize `del el[:]` would work. LXML's overriding of the operators to refer to children and such confuses me. :(

I suppose I could just save the tail text, then `el.clear()` and restore it.

**Comment by tabatkins** [comment]
Hehe, nope, .clear() kills the attributes, too. What's the use of that, I wonder?

Anyway, swapped it to `del el[:]`, thanks!

**Comment by scoder** [comment]
> LXML's overriding of the operators to refer to children and such confuses me.

Feel free to read [the tutorial](https://lxml.de/tutorial.html#the-element-class).

> `.clear()` kills the attributes, too. What's the use of that, I wonder?

Well, the name `clear()` isn't entirely free of meaning. If you want to clear the complete element to start from scratch, call `el.clear()`. If you want to clear only the sequence of children, use `del el[:]`. If you only want to clear only the attributes mapping, use `el.attrib.clear()`. Seems quite reasonable to me. None of these three is a rare operation, depending on the usage scenario.

**Comment by tabatkins** [comment]
It's not confusing in the sense that I don't understand it, it's that they're mixing idioms in a way that makes things complicated and weird. An element is an object on its own, but it's *also* a dict-like (containing its attributes) and *also* a list-like (containing its children). These clash in various ways, like how it's completely unclear whether `if el:` is doing a boolean test for "is this an element, or is it something falsey like None?", or "does this contain any attributes, or not?" or "does this contain any children, or not?". The fact that LXML emits a warning when you do this *precisely because they've changed behavior on this in the past* is part of it.

> Well, the name clear() isn't entirely free of meaning. If you want to clear the complete element to start from scratch, call el.clear(). If you want to clear only the sequence of children, use del el[:]. If you want to clear only the attributes mapping, use el.attrib.clear(). Seems quite reasonable to me. None of these three is a rare operation, depending on the usage scenario.

`el.clear()` doesn't start an element from scratch, it starts it from scratch *and deletes the following text*. `del el[:]` doesn't clear the sequence of children, it clears all children *except for any text preceding the first element child*. `el.attrib.clear()` clears the attributes, *which means you're having to interact with a sub-object* when the API otherwise lets you pretend the element itself is a dict for its attributes (because if you continue to pretend it's a dict, you'll assume `.clear()` can be used on the element to clear the attributes like any other dict, and you'll be sad...).

LXML's data model is incoherent and confusing; I suspect it's based on some early attempts to be "friendlier", which ended up just clashing in terrible ways as they developed it into a full document API.

Not like any of this matters; this is just the reason I wrote `htmlhelpers.py` to give me a DOM-like interface instead. When I have to interact with the underlying LXML data model to *implement* those functions, it's still confusing, is all.

**Comment by scoder** [comment]
> they've changed behavior on this in the past

No, they didn't.

> deletes the following text … any text preceding … give me a DOM-like interface …

Ah, yes, I was guessing that this was the main symptom of your confusion. I'm aware that it is fairly difficult to unlearn the quirks of most of the (DOM-like) XML/HTML APIs out there, which confuse the concepts or structure and text. But text is not structure. Having to step over text all the time in order to work on the structure is hugely annoying, that's why lxml/ElementTree moves text out of the way and makes it a property of an Element. And when you clear such an Element, then all its content properties are cleared, which obviously include the tail text property. I would find it rather surprising if clearing an Element would clear only some of the content properties but not all of them. You seem to prefer such inconsistency, but sorry, inconsistency is not what the API will give you.

The ElementTree API is actually use case optimised in that it prefers structure over text, and inner (`.text`) content over trailing (`.tail`) text content, which is not more than formatting whitespace most of the time. That makes its use extremely efficient when compared to convoluted DOM-like APIs. You just have to unlearn those first. :)

> element itself is a dict for its attributes

It isn't, and no-one pretends it was. Elements are list-like containers that carry an attribute dict (with get/set convenience functions, because single attribute access is so extremely common). Read the tutorial on this, I think it explains it quite well (not only because I've written it ;) ).

**Comment by tabatkins** [comment]
> No, they didn't.

Tell that to the warning that shows up when you write `if el:`, explaining that behavior changed in some version and recommending using `if el is None:` or `if len(el):` to be clear about which meaning is intended.

> Ah, yes, I was guessing that this was the main symptom of your confusion. [snip]

There's no confusion in this regard. There's nothing wrong with DOM. (Well, there's a *lot* wrong with DOM, but the core data model isn't problematic.)  LXML's data model assumes that "significant" text only shows up at the leaves of your element tree, and is never interleaved with elements; DOM assumes that text and elements are at the same level of importance. For many XML languages, LXML's assumptions are reasonable, and probably make it easier to work with the documents. For HTML, it's 100% wrong and fundamentally ill-suited, whereas DOM is reasonable and useful for HTML.

> It isn't, and no-one pretends it was. 

It absolutely is, and LXML definitely pretends so. Offering a `.get()`/`.set()`/`.has()` on the element itself, interacting with the attributes, means that an element is a dict-like. It's just not *totally* a dict-like, which is confusing.

> Read the tutorial on this

I've absolutely read the tutorial, along with the more detailed docs, multiple times over the past several years. Knowing that the decisions have been made doesn't make them any easier to deal with. ^_^
