### ISSUE TITLE
New status value: DRAFT-FINDING

### ISSUE THREAD

**Issue by hober** [tabatkins/bikeshed#1484]
reSpec has such a thing. Here's [an example](https://w3ctag.github.io/ethical-web-principles/).

It looks like this'll be a really straightforward patch. I'll try to get you a PR this week.

**Comment by hober** [comment]
Just notes to myself: `config/status.py` already knows about draft findings, but `metadata.py` does not.

**Comment by dbaron** [comment]
Done before in #902 -- maybe regressed in a refactoring of statuses?

**Comment by tabatkins** [comment]
No, it's still there, and yeah, works just fine. However, it's not specialized to the TAG, and using it with a W3C `Group` value will cause broken styles because all of them rely on the `[W3C-STYLESHEET-URL]` macro, which isn't set to anything useful for the `DRAFT-FINDING` status.

However, if you do it with no `Group` at all, you get a reasonable-looking output.

If the TAG would like some boilerplate for themselves, that's just fine - copy/paste from some other W3C group and alter accordingly, I'll happy accept the PR. Note that you can specialize the boilerplate files according to `Status`, so in this case `header-FINDING.include` and `header-DRAFT-FINDING.include` files can provide the TAG-specific bylines "Finding of the TAG", etc.
