### ISSUE TITLE
Regression: Encoding Standard

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1537]
TextDecoderCommon defines `encoding` twice, once as dfn and once as attribute. This used to work fine as you can see at https://encoding.spec.whatwg.org/#textdecoder-encoding (dfn) and https://encoding.spec.whatwg.org/#dom-textdecoder-encoding (attribute). It now fails on master https://travis-ci.org/whatwg/encoding/builds/595542510 with

> FATAL ERROR: Multiple local 'attribute' &lt;dfn>s for 'TextDecoderCommon' have the same linking text 'encoding'.

Interestingly enough, this still worked yesterday as the PR I created for this did not report this error, which strongly suggests Bikeshed is the culprit here.

**Comment by tabatkins** [comment]
Hmmmm, nothing broke when I tested the changes yesterday, which is interesting. I'll look into this shortly.

**Comment by npm1** [comment]
Dupe of https://github.com/tabatkins/bikeshed/issues/1536. It is certainly bikeshed BTW because this happened after I did bikeshed update to reproduce the build failure in my spec. There was a suggested culprit there, can we look to see if reverting that fixes the problems? This seems to affect a lot of specs.

**Comment by tabatkins** [comment]
Yup, dupe.

**Comment by tabatkins** [comment]
(Re-closing because this is still a dupe.)
