### ISSUE TITLE
[question] How it differs from asciidoctor, jekyll or others?

### ISSUE THREAD

**Issue by coolbrg** [tabatkins/bikeshed#1570]
First of all, thanks for initiating such a nice project and making it under `CC0` license. 

However, it would be great if we get a clear difference from other similar preprocessor or static site generator which could achieve a similar job. 

Or in a direct sense as a developer why should I choose `Bikeshed` over others.

One clear advantage I see over others is it seems to be super simple to use. Very few variable components than others. 

Thanks

**Comment by frivoal** [comment]
While in practice, bikeshed can be used to produce all sorts of document, it's development is driven by the need to have a preprocessor that is good at writing technical specifications for the purpose of standardization, such as the things you can find at https://spec.whatwg.org/ or https://www.w3.org/TR/.

Since these are documents, bikeshed has lots of features that are common with other generic document preprocessors. But these are specialized document with lots of conventions to be followed, and many specialized tasks for which bikeshed provides helpful tools that you wouldn't find in a more generic preprocessor.

If you're writing other kinds of documents, that doesn't mean you cannot use bikeshed, but keeping in mind who the primary audience is will help you understand why bikeshed is the way it is, why it has an over abundance of certain things, and a lack of others.

**Comment by coolbrg** [comment]
Thanks @frivoal for the response. It has got me enough understanding.
I will keep this issue open for a few more days to get other opinions as well.

**Comment by tabatkins** [comment]
Closing because @frivoal pretty much answered exactly right.
