### ISSUE TITLE
Tech support question: How do you autolink to an HTML global attribute?

### ISSUE THREAD

**Issue by hober** [tabatkins/bikeshed#1606]
How do you autolink to an [HTML global attribute](https://html.spec.whatwg.org/multipage/dom.html#global-attributes), e.g. [hidden](https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute)? The documentation says to write `<{element/attribute}>`, but what element do you name for global attributes? I tried `<{html/hidden}>` and `<{/hidden}>` but neither worked.

**Comment by tabatkins** [comment]
For hidden, the answer appears to be "you don't", because it's not marked up to be exposed *at all* - it has no ID, no attributes detailing its dfn metadata, etc. I'd file a bug against HTML to mark it up properly for Bikeshed to pick up.

(What to make a global definition "for" is up to the language. I'd recommend either "global" or "html".)
