### ISSUE TITLE
"Include Mdn Panels" throws error

### ISSUE THREAD

**Issue by equalsJeffH** [tabatkins/bikeshed#1659]
I cannot get "Include Mdn Panels" to work using locally-installed bikeshed, it throws error:
```
> git diff
diff --git a/index.bs b/index.bs
index 96d1957..b420911 100644
--- a/index.bs
+++ b/index.bs
@@ -61,6 +61,7 @@ Text Macro: WAC WebAuthn Client
 Text Macro: WRP WebAuthn Relying Party
 Text Macro: WRPS WebAuthn Relying Parties
 Ignored Vars: op, alg, type, algorithm
+Include MDN Panels: yes
 Abstract: This specification defines an API enabling the creation and use of strong, attested, [=scoped=], public key-based
  credentials by [=web applications=], for the purpose of strongly authenticating users. Conceptually, one or more [=public key
  credentials=], each [=scoped=] to a given [=WebAuthn Relying Party=], are created by and [=bound credential|bound=] to
>
> bikeshed update
Updating via manifest...
Updating 2 files...
Done!
>
> bikeshed spec index.bs
LINE 64: Unknown metadata key "Include Mdn Panels". Prefix custom keys with "!".
 ✘  Did not generate, due to fatal errors
>
```
However, cloud bikeshed works:

> curl https://api.csswg.org/bikeshed/ -F file=@index.bs -F force=1 -F output=err
LINK ERROR: No 'dfn' refs found for 'present' that are marked for export.
LINK ERROR: No 'dfn' refs found for 'not present'.
LINK ERROR: No 'dfn' refs found for 'publickey-credentials-get-feature'.
&lt;a data-lt="publickey-credentials-get-feature" data-link-type="dfn">publickey-credentials-get&lt;/a>
WARNING: The following locally-defined biblio entries are unused and can be removed:
  * fidouafauthenticatormetadatastatements
 ✔  Successfully generated, with 3 linking errorsjdhodges-glaptop:~/standards/w3c/webauthn[94]>

**Comment by equalsJeffH** [comment]
Update:  adding "Include Mdn Panels" [causes our bikeshed TravisCI-driven auto-build to fail, with a different error](https://travis-ci.com/github/w3c/webauthn/jobs/327464983):

> FATAL ERROR: Couldn't find the MDN data for 'webauthn-2' nor 'webauthn'.
 ✘  Did not generate, due to fatal errors
The command "bikeshed spec" exited with 1.

**Comment by sideshowbarker** [comment]
I think the error will go away if you set the "Include Mdn Panels" value to "if possible" or "maybe".

See https://tabatkins.github.io/bikeshed/#soft-boolish

But given the content of the error message, I think that won’t cause Bikeshed to actually add the MDN panels — because the problem seems to be that Bikeshed can’t find the webauthn.json file.

But at https://w3c.github.io/mdn-spec-links/webauthn.json that file does exist upstream.

Maybe you need to run `bikeshed update`? Or if that still doesn’t work, you can try forcing it:

```
bikeshed update --skip-manifest --mdn
```

**Comment by equalsJeffH** [comment]
thx @sideshowbarker but as shown in the OP I did run bikeshed update. Also, the error I get on my local bikeshed install is (as shown above) "Unknown metadata key "Include Mdn Panels".  Additionally, cloud bikeshed works fine and apparently finds the upstream data.

**Comment by sideshowbarker** [comment]
I’m so far not able to reproduce this.

https://webauthn-mdn.herokuapp.com/#iface-authenticatorassertionresponse shows the output that I was able to generate, with 33 MDN panels included.

I tested like this:
```
pip3 install --upgrade --force-reinstall bikeshed \
  && bikeshed update;
cd /tmp && rm -rf webauthn;
git clone https://github.com/w3c/webauthn.git \
  && cd webauthn && git checkout jeffh-testing-mdn-panels \
  && bikeshed spec index.bs index.html
```
And this is the log of the Bikeshed run:

```
LINE ~1448: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1456: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1496: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1501: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1538: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1569: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1595: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1604: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1606: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1619: No 'dfn' refs found for 'not present'.
LINE ~1652: No 'dfn' refs found for 'not present'.
LINE ~1913: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1917: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1968: No 'dfn' refs found for 'present' that are marked for export.
LINE ~1999: No 'dfn' refs found for 'present' that are marked for export.
LINE ~2029: No 'dfn' refs found for 'present' that are marked for export.
LINE ~2595: No 'dfn' refs found for 'present' that are marked for export.
LINK ERROR: No 'dfn' refs found for 'publickey-credentials-get-feature'.
<a data-lt="publickey-credentials-get-feature" data-link-type="dfn">publickey-credentials-get</a>
LINE ~4385: No 'dfn' refs found for 'present' that are marked for export.
LINE ~5585: No 'dfn' refs found for 'not present'.
WARNING: The following locally-defined biblio entries are unused and can be removed:
  * fidouafauthenticatormetadatastatements
 ✔  Successfully generated, with 20 linking errors
```

**Comment by equalsJeffH** [comment]
did you stick `Include MDN Panels: yes` into index.bs' bikeshed metadata?

**Comment by sideshowbarker** [comment]
> did you stick `Include MDN Panels: yes` into index.bs' bikeshed metadata?

I made zero changes to the source. All I did was to git-checkout the jeffh-testing-mdn-panels branch and run `bikeshed spec index.bs index.html`

**Comment by equalsJeffH** [comment]
@sideshowbarker -- ah, ok, thx, so yeah, `Include MDN Panels: yes` would have been in the source file and you indeed built it fine.  the problem may be my bikeshed install.  checking....

**Comment by equalsJeffH** [comment]
Well, I did a `pip3 install --upgrade --force-reinstall bikeshed  && bikeshed update` on my local machine here and bikeshed continues to fail: 
> LINE 31: Unknown metadata key "Include Mdn Panels". Prefix custom keys with "!".
 ✘  Did not generate, due to fatal errors

I changed the boolish value to `maybe` and the same error occurs (on my local machine). so I dunno, it's annoying but not the end of the world, and barring any others reporting they have the same difficulty, its just me. 

However, `maybe` does work for our webauthn repo's TravisCI build  - https://github.com/w3c/webauthn/pull/1411#issuecomment-624258971 -- so that would seem to be a different problem with finding the upstream data when a `yes` is used (seems odd?).

**Comment by sideshowbarker** [comment]
As far as I understand it, the only reason you’d be seeing that *Unknown metadata key "Include Mdn Panels"* if the bikeshed version that’s getting invoked is older version that doesn’t have support for the MDN-panels feature.

So it sounds like what might be happening is that you have multiple `bikeshed` executables installed on your system, and the one that’s being invoked is an older one that’s not getting updated when you run `pip3 install --upgrade --force-reinstall bikeshed`.

So a way you could troubleshoot that is:

1. Give the `--verbose` option to `pip3 install`:
    ```
    pip3 -v install --upgrade --force-reinstall bikeshed
    ```
    That will in the end emit the install location for the `bikeshed` binary:
     ```
     changing mode of /usr/local/bin/bikeshed to 755
     ```
2. Invoke bikeshed with the full path to that executable:
    ```
    /usr/local/bin/bikeshed spec index.bs index.html
    ```
If you don’t get the *Unknown metadata key "Include Mdn Panels"*, then you can be sure it’s because your normal invocation isn’t causing that binary to be run. And so you’d know you have another `bikeshed` executable somewhere that’s getting invoked instead.

So I guess you’d want to use `which bikeshed` to try to see where that other executable is. And then remove it, or change your `PATH` environment variable to make the pip3-installed `bikeshed` be the first one in your `PATH`.

**Comment by equalsJeffH** [comment]
> ... if the bikeshed version that’s getting invoked is older version that doesn’t have support for the MDN-panels feature.
> 
> So it sounds like what might be happening is that you have multiple bikeshed executables installed on your system...

bingo, that's what's going on. 

THANKS for your help.  All fixed now, closing this issue....

**Comment by sideshowbarker** [comment]
cheers — glad you got it solved 👍

**Comment by tabatkins** [comment]
I'm super glad y'all worked this out!

Just fyi, another "fun" problem that can happen sometimes is that bash will *cache* the path to a command, so that even when you think you've fixed everything, `which bikeshed` shows what you expect, etc., you can still be screwed up.

If this happens (it happened to me!), `type bikeshed` will show you the *actual* path bash is using: <https://unix.stackexchange.com/questions/5609/how-do-i-clear-bashs-cache-of-paths-to-executables>
