### ISSUE TITLE
Feature request: <dfn unused>

### ISSUE THREAD

**Issue by ricea** [tabatkins/bikeshed#1747]
The [Streams Standard](https://streams.spec.whatwg.org/) has the unusual feature that it has a slot "\[[detached]]" which is not referenced inside the standard. It is there to satisfy [the HTML standard](https://html.spec.whatwg.org/multipage/structured-data.html#detached), but that uses the "\[[detached]]" slot in a polymorphic fashion and so there's no requirement for the streams standard to export it.

I'd like to be able to format it as a `<dfn>` without getting an error about it being unused. `<dfn unused>` by analogy with `<var unused>` would be perfect.

**Comment by tabatkins** [comment]
Hm, I don't quite understand the use-case here.

It's a definition meant to be linkable from other specs (in particular, HTML), but for Reasons, HTML doesn't directly link to it. (But would, if its algorithm was written slightly differently.) Is this right?

If so, I don't see why it shouldn't still be exported. It's not meant to be an internal definition; it's intended to be part of the public-facing API of the spec document.

----

That all said, the reason you're getting an error about this is because it's being marked up as a "dfn" type definition; slots should be marked up as `<dfn attribute for=InterfaceName>[[slot]]</dfn>`. That'll also happen to solve your problem, since attributes are exported by default, unlike "dfn" type definitions. ^_^

**Comment by ricea** [comment]
For HTML to link to it, HTML would have to have a list of all detachable objects in all specs, which would not be scalable. But your argument that it is part of the public-facing API is compelling, so I will do that.
