### ISSUE TITLE
Add --version

### ISSUE THREAD

**Issue by saschanaz** [tabatkins/bikeshed#1751]
`bikeshed --version` seemingly doesn't do anything but silently dies. It will be helpful to check the locally installed version.

**Comment by tabatkins** [comment]
It was already printed out as part of `bikeshed -h`'s output, but sure, I added support for --version as well.

It *is* weird that it silently did nothing; I wasn't actually handling it at all. Maybe argparse has some default handling for this flag?

...and yes, turns out it does, so I just switched to that.

**Comment by saschanaz** [comment]
I think bikeshed does not throw error for unknown flags: `bikeshed --lololol` also silently dies.
