### ISSUE TITLE
data-dfn-type="attr-value" not working with data-export

### ISSUE THREAD

**Issue by horo-t** [tabatkins/bikeshed#1752]
Hi. I'm working on  https://github.com/WICG/webpackage/pull/591.

Even after [updating the HTML spec](https://github.com/whatwg/html/pull/5843) to use `<dfn data-export="" data-dfn-for="link/rel" data-dfn-type="attr-value">` for preload, and [updating the bikeshed-data](https://github.com/tabatkins/bikeshed-data/commit/61c0d25aadd483bb33e36d66ee3a441ad51586fc), `<{link/rel/preload}>` is still causing the error:

```
LINK ERROR: No 'attr-value' refs found for 'preload'.
<{link/rel/preload}>
```

Does `data-dfn-type="attr-value"` works with data-export?

(Sorry, I'm not familiar with bikeshed. So I may misunderstand something.)

**Comment by plinss** [comment]
The source is:

    <h5 id=link-type-preload><span class=secno>4.6.6.19</span> Link type "<dfn data-dfn-for=link/rel data-dfn-type=attr-value data-export=""><code>preload</code></dfn>"<a href=#link-type-preload class=self-link></a></h5>

The anchor is the heading, and being a heading the anchor name is '4.6.6.19' with a title of 'Link type "preload"'. Shepherd does see the `<dfn>` inside the heading so classified the anchor as a 'attr-value' type. What's missing is that it's not capturing the 'dfn-for' or any linking text on the dfn (because there isn't any).

There are heuristics in place that do some fixups for element definition headings, but not the general case.

I think the fact that Shepherd isn't catching the 'dfn-for' is just a bug, the `<dfn>` attributes aren't propagating upward into the heading. I can also add some code that synthesizes linking text when the dfn text doesn't match the anchor name and there isn't any other linking text provided.

**Comment by tabatkins** [comment]
Actually no, I see the problem: there's no id on the dfn.

So either if needs an id, or the dfn attributes need to move to the h5 (including a `data-lt=preload`)

**Comment by plinss** [comment]
Right, an id on the `<dfn>` would make it an independent anchor.

On the other hand, there is code to propagate some of the `<dfn>` behavior up into the heading, e.g. the anchor-type, it sort of makes sense to grab the rest of the `<dfn>`.

**Comment by jyasskin** [comment]
This is working now, maybe because of the switch to Webref.
