### ISSUE TITLE
Spec went into broken dark mode

### ISSUE THREAD

**Issue by npm1** [tabatkins/bikeshed#1765]
I filed https://github.com/WICG/layout-instability/issues/76 because I see the spec currently in some form of dark mode that is not quite correct (as some of the text is in light background and does not contrast well). I thought this was fixed in bikeshed so it would be fixed by updating the spec with some trivial change but I still see this in the PR preview for https://github.com/WICG/layout-instability/pull/77

**Comment by npm1** [comment]
Ah so setting the Macbook to dark mode causes the spec to be shown in dark mode. But the header (with the authors etc.) is still shown in a light background, so that part seems broken

**Comment by domenic** [comment]
I've noticed this issue too. I think the WICG template uses a background image which is hard-coded to white: https://www.w3.org/StyleSheets/TR/2016/logos/UD-watermark

**Comment by tabatkins** [comment]
Fixed now; I have some PRs against the W3C css to make it a little better, but for now I just manually override the bg image in those cases with an SVG version I ginned up that is darkmode-appropriate.

Afaict, the `back-cg-draft.png` image is fine, since it's got a transparent bg, and the image looks reasonable against black.
