### ISSUE TITLE
<wpt> doesn't know about manual tests

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1783]
Manual tests are few, but they exist. If you document them in your spec using the `<wpt>` tag, you'll get a fatal error because bikeshed doesn't know about manual tests, and thinks you have a broken link. That's annoying.

To date, I'm documenting them using
```
<wpt>
<!-- manual
foo-001-manual.html
-->
</wpt>
```
but that shouldn't be necessary.

**Comment by tabatkins** [comment]
I actually was including tests classified as "manual" in WPT, but not those classified as "visual". I'm not entirely sure what the distinction is, but it appears to be whether the meta-flags argument is empty or specifies a particular manual intervention to be performed. (Like, anything requiring scrolling is "manual".)

Not sure *why* I was making that distinction, since neither of them are displayed on wpt.fyi.

Looking into this, I also realized that, since I was including "manual" tests which dont' appear on wpt.fyi, but the output wasn't distinguishing between them, any references to manual tests would have some broken links.

Anyway, should be all fixed now. *All* the test categories are tracked, and given the appropriate set of links.

(While I was at it, I realized that, despite *defining* a darkmode set of colors for the WPT block, I didn't actually *use* them in the immediately following styles, so it was unreadable light-mode bg with darkmode text. That's also fixed now.)
