### ISSUE TITLE
Defining an anchor without a spec results in `<a href="#https://.......">`

### ISSUE THREAD

**Issue by hober** [tabatkins/bikeshed#1788]
I have the following anchor definition:

`text: same-origin policy; type:dfn; url: https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy`

**Expected**: I thought this would result in me being able to type `[=same-origin policy=]` and for that to turn into a link to that MDN page.

**Actual behavior**: The result is an `<a>` element whose `href` attribute contains `"#https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy"`. Note the `#` at the beginning.

**Comment by tabatkins** [comment]
Ah, that's not the lack of `spec`, but rather the fact that I assume definitions are pointing to an element in the page, and thus will have an anchor. The rule is just "if `url` doesn't have a # in it, than join it to `urlPrefix` with a # between them; otherwise just join them together. (Your `urlPrefix` is missing, and thus an empty string here.)

Easy fix is putting a # at the end of the URL; does that work for you?

**Comment by hober** [comment]
> Ah, that's not the lack of `spec`, but rather the fact that I assume definitions are pointing to an element in the page, and thus will have an anchor. The rule is just "if `url` doesn't have a # in it, than join it to `urlPrefix` with a # between them; otherwise just join them together". (Your `urlPrefix` is missing, and thus an empty string here.)
> 
> Easy fix is putting a # at the end of the URL; does that work for you?

Oh, that makes sense. It felt a bit cleaner for me to simply s/url/urlPrefix/, and that works for me.
