### ISSUE TITLE
Dark mode is very hard to read for WebAudio spec

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1790]
Visit https://webaudio.github.io/web-audio-api/ in dark mode.  I did this on a Mac.  The ToC looks good with white text on a black background.  But the main page is hard to read with low contrast.  I don't think the WebAudio spec has any CSS that would cause this.  I tested this locally by removing any `<style>` stuff added and removing MathJax.

**Comment by tabatkins** [comment]
...huh, for some reason y'all are manually embedding some ED CSS in your `header-ED.include` file: <https://github.com/tabatkins/bikeshed/blob/master/bikeshed/boilerplate/audiowg/header-ED.include#L10>

That's what's causing the problem here; you should be able to just delete that whole `<style>` block.

**Comment by rtoy** [comment]
Yep, that makes it all work nicely in dark mode.  But doesn't that mean I need to send you a PR to remove that from bikeshed?

**Comment by tabatkins** [comment]
yup!

**Comment by rtoy** [comment]
Ok.  PR coming soon....
