### ISSUE TITLE
Boilerplate: omit conformance conflict with Complain About: missing-example-ids yes

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1804]
Previously, if I said `Boilerplate: omit conformance` and `Complain About: missing-example-ids yes`, I would be fine. Even if the boilerplate section had `<div class="example">` without an ID, there would be no problem.

However, recent attempts to re-build https://github.com/WICG/import-maps/blob/master/spec.bs are failing, because now it seems the processing order has changed, and the check for missing example IDs happens before the removal of the conformance section. So my spec won't build until I remove `Complain About: missing-example-ids yes`.

**Comment by tabatkins** [comment]
Linting example IDs has happened before removing unwanted boilerplate for at least three years (before that the code organization was different and I haven't gone to the effort of tracing further back).

What happened here is that `Boilerplate: omit conformance` was cargo-culted in from the first commit, and didn't actually do anything, as there was no `conformance` boilerplate in the spec.  However, I recently added the ability to have default boilerplate per megagroup, like all W3C specs, and included a conformance boilerplate section in the `footer.include`. Since WICG doesn't define a footer, it started using the W3C version (previously it used the "default" version, which was basically empty).

Anyway, fixed by putting an ID on that example example. ^_^

**Comment by tabatkins** [comment]
Heh, yup, example-ID linting has *always* been processed before unwanted-boilerplate removal. ^_^ https://github.com/tabatkins/bikeshed/commit/d3ca415c3473c439b8e7d0cc3e1dc561fec20174
