### ISSUE TITLE
WHATWG PR snapshots are wrong

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1818]
It doesn't seem like anything in pr-preview changed so I suspect this might be a Bikeshed issue (though it's hard to find a suspicious change in the last month or so), but if you compare

* https://whatpr.org/dom/898.html
* https://whatpr.org/dom/909.html

you'll find that the first is correct and the second doesn't seem to have been generated in the correct way (e.g., it expects a COMMIT-SHA despite that only being for LS and not LS-PR). Anyone with ideas? I'm a bit at a loss.

cc @tobie @tabatkins @domenic

**Comment by tobie** [comment]
Unfortunately, my logs don't go far away enough to catch those. However, whatwg/dom#919 has the same rendering issue and the URL used to generate the Bikeshed build is this one:

https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fbenjamingr%2Fdom%2Fd76d789a01f77f70003cdd06b3d144bd1d5795a5%2Fdom.bs&force=1&md-status=LS-PR&md-Text-Macro=PR-NUMBER%20919

Is this the expected URL on your side, @tabatkins?

**Comment by domenic** [comment]
This is probably on the Bikeshed side:

- We are sending it status LS-PR,
- Which per https://github.com/tabatkins/bikeshed/blob/fc62265be1a1901b5c1336216bbebdda9eeeb00d/bikeshed/boilerplate/whatwg/computed-metadata-LS-PR.include should trigger a `custom` warning,
- which should generate the warning at https://github.com/tabatkins/bikeshed/blob/fc62265be1a1901b5c1336216bbebdda9eeeb00d/bikeshed/boilerplate/whatwg/warning-custom.include ,
- since it is filled in at https://github.com/tabatkins/bikeshed/blob/fc62265be1a1901b5c1336216bbebdda9eeeb00d/bikeshed/boilerplate/whatwg/header.include#L25

**Comment by andreubotella** [comment]
After a bit of digging on the build errors on today's WHATWG Review Drafts (whatwg/whatwg.org#348), I reached the conclusion that it's caused by the same bug as this issue, and that it's indeed a Bikeshed bug.

The error complains about an unmatched `[COMMIT-SHA]` macro in the review draft. This macro of course doesn't appear in the source itself, or in any of the `RD` boilerplate, but it is in the default (non-`RD`) `computed-metadata.include`. And if you force Bikeshed to generate the spec (with `bikeshed watch`, because apparently `--die-on=nothing` doesn't work in this case), you can see that the output is using the `RD` header and footer, but the normal defaults and computed-metadata. Which is what also seems to be happening with the `LS-PR` status.

This seems to happen whenever a status is set, either through the command-line or through the `Status` metadata. And the behavior seems consistent with the PR snapshots.

I've git-bisected the bug to commit 9410d77. I think I'll try to fix it.
