### ISSUE TITLE
Can't find the MDN data for 'webaudio-1' nor 'webaudio'

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1824]
This started showing up a couple of days ago. See https://github.com/WebAudio/web-audio-api/issues/2278

The odd part is when I update my local copy of bikeshed to the latest git version, I don't see this error.  Everything works as expected.  It seems it only shows up when running with Travis CI, which we set up to always clone the latest version of bikeshed from github.  @padenot has the same issue (works locally, but not on Travis).

**Comment by sideshowbarker** [comment]
I don’t know why this would be happening. https://w3c.github.io/mdn-spec-links/webaudio.json exists and that’s what it should be finding. Even in the https://api.travis-ci.com/v3/job/443958168/log.txt raw build log I can’t find any clues beyond just the same error message cited in the issue title here.

**Comment by rtoy** [comment]
Yeah, I don't know what's up with Travis and bikeshed.  We did change our setup to clone the bikeshed repo a little while ago, but it was working fine.  Now it's pretty consistently failing. But not locally.  Really confusing!

**Comment by mkruisselbrink** [comment]
I believe @inexorabletash ran into the same issue for the IndexedDB spec as well.

**Comment by mkruisselbrink** [comment]
For example on https://travis-ci.com/github/w3c/IndexedDB/builds/202248921

**Comment by inexorabletash** [comment]
And FYI if you have the Bikeshed `Include MDN Panels` option set to `maybe` (the default) then failure to fetch the JSON just silently drops the panels with no error. Only a truthy value causes the failure. So... you can at least disable the option for now.

And yeah, exactly the same issue for me: worked locally, worked via the hosted version of Bikeshed, just fails with Travis.

**Comment by sideshowbarker** [comment]
@rtoy or @inexorabletash: Can one or both of you maybe try committing a (temporary) change to the Bikeshed invocation in your `compile.sh` scripts to add the `--debug` flag? `bikeshed --debug …` — so that your CI runs will invoke Bikeshed with that?

I’ve not been able to reproduce this locally with Bikeshed built from the latest sources — neither with the Web Audio spec nor with the IndexedDB. But I guess that’s not surprising, since @rtoy said he also couldn’t reproduce it locally.

But what is more surprising is that for the IndexedDB, the .travis.yml setup seems to actually be running exactly the same thing I am locally — that is, rather than using whatever Bikeshed release version the CI system would normally install, it’s checking out the Bikeshed sources from GitHub and then installing and running that.

I have zero clue myself at this point what would cause Bikeshed to fail to find the right mdn-spec-links JSON file when running under CI but not when running locally.

I’ll try think of some other ways to investigate this further. If we don’t get any further clues from the `--debug` log output, the only next step I can think of is that I start checking in some temporary printf-y debug stuff into the Bikeshed sources to try to get a better picture of exactly what’s happening (or rather, not happening that should be).

**Comment by sideshowbarker** [comment]
Also if you’re able to take the time and trouble to try, please consider also checking in a temporary change to your `compile.sh` scripts to run `bikeshed update --skip-manifest` (with the `--skip-manifest` flag), to force a full update. Another thing to consider trying is `bikeshed update --mdn`, to update just the mdn-spec-link JSON data.

**Comment by tabatkins** [comment]
Taking off of vacation for a few minutes to fix this, sorry about that. :(

So I'm not sure about the root cause yet (just started looking into it), but I'm confident the *proximate* cause is that I updated the data files to a new version, but forgot that the `mdn` folder had been added to the data files since then, and didn't put them into the commit.

I don't know why that's *still* causing issues, considering that WebAudio, and I assume the others, are running `bikeshed update`, which should pick up the new files. So I'll dig in and figure out what's up.

**Comment by sideshowbarker** [comment]
Hi @tabatkins — thanks for the update and for interrupting your vacation.

Only other piece of possibly-useful info I’ve managed to find so far is that when I run `bikeshed update --skip-manifest` locally, I got this:

```
Downloading Can I Use data...
FATAL ERROR: The Can I Use data wasn't valid JSON for some reason. Try downloading again?
__init__() got an unexpected keyword argument 'encoding'
 ✘  Did not generate, due to fatal errors
```
…which of course is about the Can I Use data, not the MDN data. But I suppose maybe that could cause a fatal halt to the entire update process?

But also when I then do this:

```
$ bikeshed update --caniuse
Updating via manifest...
Updating 1 file...
Done!
```
…it appears that the Can I Use data did actually get updated?

So maybe that *FATAL ERROR: The Can I Use data wasn't valid JSON for some reason* failure isn’t relevant at all actually.

**Comment by sideshowbarker** [comment]
> @rtoy or @inexorabletash: Can one or both of you maybe try committing a (temporary) change to the Bikeshed invocation in your `compile.sh` scripts to add the `--debug` flag? `bikeshed --debug …` — so your CI runs will invoke Bikeshed with that?

I’ve since realized I can also try that myself, so I forked the IndexedDB repo and flipped on he `--debug` flag in my fork, and  I have a CI run started at https://travis-ci.org/github/sideshowbarker/IndexedDB/builds/744986754

**Comment by tabatkins** [comment]
`--debug` won't do anything useful here, it just makes some things output differently; I mostly use as a testing trigger.

Anyway, I've reproduced the bug, so I can be confident of fixing it now.

**Comment by tabatkins** [comment]
@sideshowbarker Oh yeah and that encoding issue you're running into is because you're on an even more recent Python (>3.7) and the JSON decoder no longer recognizes that argument (which hasn't done anything since py3 started). It won't cause problems on 3.7, which the bikeshed-data project uses. (And I'll remove it when I get a chance.)

**Comment by sideshowbarker** [comment]
> Anyway, I've reproduced the bug, so I can be confident of fixing it now.

ah, OK — cool 🎉

> `--debug` won't do anything useful here, it just makes some things output differently; I mostly use as a testing trigger.

OK, yeah I’ve basically just been over here rubbing sticks together to try to make fire 😆 I’m glad you were able to step away from vacation for a bit to figure it out

> that encoding issue you're running into is because you're on an even more recent Python (>3.7) and the JSON decoder no longer recognizes that argument

Ah yeah I remember now seeing some discussion of that in another issue

**Comment by rtoy** [comment]
@tabatkins This isn't time critical or anything for WebAudio  Feel free to work on the fix after your vacation.

**Comment by tabatkins** [comment]
Ahhhhh, I've figured it out!

So, to ensure that you have the right datafile structures that the current code expects, I have a "version" identifier on the readonly datafiles, and if it's ever higher than your active datafiles, I'll delete all your active files and swap in the readonly ones. (I don't update the core datafile structure much anymore, but this was vital when I was doing the splitting of the anchor file into the hundreds of files it is now, so you could pull more recent code without *requiring* an `update` immediately, which was much more onerous in the past.)

The standard `bikeshed update` is manifest-based, and compares the local manifest against the remote to see what files have changed and need to be re-downloaded. It does *not* examine the underlying file structure at all to verify that all the files listed in the manifest still exist, and are what it thinks they are.

Combine this all with the proximate bug I listed earlier, and you see the problem - I updated the data files, but didn't include the mdn folder in the new readonly contents. Upon first running, Bikeshed sees that the readonly files are a new version, so swaps them all in, *including the manifest that included the mdn files*. Then `update` runs, sees the MDN files didn't change (same hash in both local and remote manifests, no new paths), and doesn't touch them.

So, immediate fix will be easy - I'll just update the datafiles again, make sure I catch *all* the new ones in the git commit, and then push a fresh version.

I need to make sure this doesn't happen again, tho - it's happened in the past, and there might be files other than MDN that are missing and won't be repaired until they change that y'all just haven't noticed yet. So I guess I'll need to put in at least some file-existence checks into the updater, and pull those. I'll investigate the performance of just running the full manifest-creator on every update, tho, so I can get a guaranteed-accurate view of the local data files (right now I just copy the remote manifest over when the update is done, trusting it to be accurate).

**Comment by tabatkins** [comment]
All right, immediate fix is pushed and on pypi. Confirmed it worked locally, but would appreciate confirmation of it working from someone else.

**Comment by inexorabletash** [comment]
I'll push something to IDB...

**Comment by inexorabletash** [comment]
No errors from https://travis-ci.com/github/w3c/IndexedDB/builds/203242411 and https://w3c.github.io/IndexedDB/ has panels again. w00t!

**Comment by tabatkins** [comment]
Excellent, thanks everyone and apologies for pushing this error!
