### ISSUE TITLE
"Note:" boxes and hyperlinks ought to render in green and blue (respectively), but do not

### ISSUE THREAD

**Issue by equalsJeffH** [tabatkins/bikeshed#1991]
circa 9-Feb-2021, my local bikeshed install, updated using `bikeshed update`, changed rendering behavior in that "Note:" boxes and hyperlinks that ought to render in green and blue (respectively), began rendering in black (fg) & white (bg) (respectively).

A colleague's local BS install began behaving in the same manner not long afterwards, upon his doing `bikeshed update`.

upon investigation it appears the CSS has changed like so: 
```
OLD
.note {
    border-color: #52E052;
    background: #E9FBE9;
    overflow: auto;
}

NEW
.note {
    border-color: #52e052;
    border-color: var(--note-border);
    background: #e9fbe9;
    background: var(--note-bg);
    color: black;
    color: var(--note-text);
    overflow: auto;
}
```
The second definition overrides the first. But none of the vars are defined anywhere in the document.

An example bikeshed .html doc, renamed to be .txt (so I could upload it here), and  exhibiting this issue is: 

[fido-client-to-authenticator-protocol (1).txt](https://github.com/tabatkins/bikeshed/files/6174271/fido-client-to-authenticator-protocol.1.txt)

thanks!

**Comment by tabatkins** [comment]
What's your source file? Those variables are all set in `style` blocks added by Bikeshed, or come from the W3C's own stylesheet if you're publishing to /TR.

**Comment by tabatkins** [comment]
(And nit - `bikeshed update` just updates the data files. I presume you mean you did `pip upgrade bikeshed` or similar.)

**Comment by dturnerx** [comment]
(I'm the colleague mention above)
@equalsJeffH attached a sample source as the `txt` msg in his post. 

The variables `--note-*` aren't defined anywhere in the source or the output. Do I have to turn something off so those lines aren't added to the output?

**Comment by tabatkins** [comment]
Jeff attached the post-bikeshedding html file, not the source bs file. 😃

**Comment by dturnerx** [comment]
Source and output

[FIDO-IoT-spec.bs.txt](https://github.com/tabatkins/bikeshed/files/6176141/FIDO-IoT-spec.bs.txt)
[FIDO-IoT-spec.html.txt](https://github.com/tabatkins/bikeshed/files/6176142/FIDO-IoT-spec.html.txt)

**Comment by tabatkins** [comment]
Okay, confirmed the issue. The Bikeshed-default stylesheet assumes that a particular set of color variables exist. These are automatically added by Bikeshed normally, but if you are publishing to /TR, Bikeshed omits those variables and depends on the W3C stylesheet defining them instead. (The colors are set up separately from the rest of the default stylesheet for complicated reasons involving W3C's slow migration to darkmode-aware; the details are unimportant here.)

However, you're not publishing a W3C spec! You're using `Group: fido` in your metadata, which Bikeshed recognizes (allowing a similar set of `Status` values to what the W3C uses), but which doesn't have [any boilerplate files](https://github.com/tabatkins/bikeshed/tree/master/bikeshed/boilerplate) defined for it. This is fine, it just means you get the Bikeshed-default boilerplate instead.

But then your spec has `Prepare for TR: true` set, which suppresses the color variables from being generated, and nothing else in the Bikeshed-default boilerplate sets up those colors again.

The solution is to either (a) not use `Prepare for TR`, since you're not generating W3C specs and the concept of "TR" doesn't mean anything for you, or (b) if you still want to use that metadata for some reason, then provide a set of boilerplates for the FIDO group that fills in those color variables.

(If you were a W3C group, then missing boilerplates would fall down to the W3C-default boilerplates instead, which do refer to the W3C stylesheet that defines the color variables.)

**Comment by tabatkins** [comment]
Also: you don't have any "note" boxes at all in that spec, just a couple of tables (used for layout!!!!) specifying notes that aren't styled at all. Are you looking at a different doc that has "Note:" blocks?

**Comment by dturnerx** [comment]
I removed `Prepare for TR: true` and got the colors back. Thanks for this. 

Sorry for uploading the wrong docs. :-(

**Comment by equalsJeffH** [comment]
> But then your spec has `Prepare for TR: true` set....

yeah, doh, that's probably been in there since forever, we ignored it, and it didn't bite us until here recently.  Thanks for your help!
