### ISSUE TITLE
Bikeshed should autogenerate the width and hight attributes of images

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#2000]
Setting the width and height of img tags is good, as it makes page loading more stable. But it is tedious to do. Bikeshed should help.

Ideally, it should do it by default. If that cannot be done due to compat reasons, then I'll still be happy with an opt in.

If width or height have been specified manually, they should be left alone.

This should probably come with a `res=2x` attribute or something for high dpi images.

**Comment by tabatkins** [comment]
This sounds reasonable to me, if you can detect these things with cross-platform Python libraries that don't depend on shelling out to tools that might not exist.

I think it's probably fine to happen automatically, but we definitely need a document-wide opt; to do so, add something that takes a boolish to `metadata.py`, and default it to True for now.

**Comment by nschonni** [comment]
> Setting the width and height of img tags is good, as it makes page loading more stable. But it is tedious to do. Bikeshed should help.

How does it make it more stable? If no attributes are set, it uses the intrinsic size

**Comment by tabatkins** [comment]
> If no attributes are set, it uses the intrinsic size

Which isn't known until the image is downloaded, causing a layout jump if the layout depends on the intrinsic size. Setting a width/height helps, *and* nowadays it even implicitly sets the aspect-ratio, so even if you are setting the width in CSS rather than relying on the intrinsic width, you'll still get the desired height early, before the image is loaded.
