### ISSUE TITLE
"Boilerplate: repository-issue-tracking off" doesn't seem to work?

### ISSUE THREAD

**Issue by MatsPalmgren** [tabatkins/bikeshed#2155]
I added `Boilerplate: repository-issue-tracking off` in the `<pre class='metadata'>` at the start of the document but I still get the CSSWG repository link:  https://matspalmgren.github.io/css-gap-decorations/Overview.html

**Comment by tabatkins** [comment]
Ah, that's unrelated. It's in fact already turned off by the CSSWG boilerplate; what you're seeing is the separate `Issue Tracking` metadata added by the CSSWG's [`computed-metadata.include`](https://github.com/tabatkins/bikeshed-boilerplate/blob/main/boilerplate/csswg/computed-metadata.include) file. (The contents of the entry hint at this as well, as they don't just point at the repository, but at a *specific label*, which is why we have this special entry building it.)

This particular metadata just accumulates in a list, and I don't have any way to remove entries from that list once they're added, so there's no way to kill it.
