### ISSUE TITLE
"WPT tests (too many to display individually)"

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#2213]
Bikeshed tells me

> WARNING: There are 56 WPT tests (too many to display individually) underneath your path prefix 'css/css-color/' that aren't in your document.

So I have to go into each WPT directory, do a directory listing, grep out support and ref files, then check manually to find the missing tests.

Glad that bikeshed is so concerned about verbosity, but I didn't find any command line option to actually list those tests which it already knows about. That would be a useful feature.

**Comment by tabatkins** [comment]
The current hack around it is to just use a <wpt-rest> element and copy out of that. But yes, @frivoal has asked for an option to display them all, too.

**Comment by tabatkins** [comment]
All right, so the reason I was concerned about verbosity before is because there was *no way* to silence the warning for cases, like css-color, where you didn't actually *want* all the tests that were under your prefix. Now that `<wpt hidden>` is a targeted way to address that, I can remove the verbosity control, so I've done so now.
