### ISSUE TITLE
Output metadata as JSON

### ISSUE THREAD

**Issue by gsnedders** [tabatkins/bikeshed#2214]
There's times when one might need the metadata used by a generated spec, but without wanting to reimplement the early stages of spec generation (with external metadata, etc.) it's not clear there's any easy way to get this data in a machine-readable form. It would be nice to have some command that just output the spec's metadata in JSON or similar.

**Comment by tabatkins** [comment]
Huh, yeah, that would be easy enough to do. What sort of use-case are you envisioning?

**Comment by tabatkins** [comment]
All right, added. You can gather all parsed metadata with `bikeshed debug --print-metadata`. As the help message says, the top-level keys are the metadata source, in increasing order of importance; the second-level keys are the metadata keys themselves, in order of first appearance in each context.

There is no collapsing of metadata, since I don't do that at the textual level but rather post-parsing, and that would make the code a lot more complicated. You'll need to know which metadatas override, which accumulate, and which do something more complicated on your own. Lmk if this actually is something you require.

**Comment by gsnedders** [comment]
> There is no collapsing of metadata, since I don't do that at the textual level but rather post-parsing, and that would make the code a lot more complicated. You'll need to know which metadatas override, which accumulate, and which do something more complicated on your own. Lmk if this actually is something you require.

Will let you know. I don't think it is, but we'll see if my answer changes once I start doing anything.

**Comment by tabatkins** [comment]
Cool. Note that if you're just, like, wanting to smush all of it together into one place for hermetic builds or something, you can do that; just make sure the lines retain their relative ordering between sources when you smush them (so instances from commandline come after instances from document, etc).
