### ISSUE TITLE
[bug] Local boilerplate with group does not work

### ISSUE THREAD

**Issue by gabyx** [tabatkins/bikeshed#2217]
Not sure if I am using it wrong:

```markdown
Group: devops
Local Boilerplate: header yes, stylesheet yes, stylesheet-code-highlight yes
```

and having a `devops/header.include` next to the document, does not include it, neither the other files?
How should that work, maybe we could improve the Doc if my understanding is wrong.

**Comment by tabatkins** [comment]
It doesn't work; local boilerplates files are just looked for as siblings of the spec document. I don't support this because it didn't seem necessary - a single file is gonna be produced by a single group, and thus want a single set of boilerplates, right? Is there a particular reason you wanted to put your local boilerplates in a folder?

**Comment by gabyx** [comment]
Ah it was just to have them together in a folder. I was confused why these boilerplates cant be in a separate group subfolder but other can?

Von meinem iPhone gesendet

**Comment by tabatkins** [comment]
It just wasn't necessary to do so. The built-in boilerplates need to be in folders because, well, there's lots of them, all for different groups. Your local boilerplates don't need that, so I didn't implement anything to look for folders.

I *could*, certainly, it just would be relatively low-value, I think.
