### ISSUE TITLE
[bug] Second boiler-plate `stylesheet2` not included in `header.include`

### ISSUE THREAD

**Issue by gabyx** [tabatkins/bikeshed#2218]
Using the following does not include `stylesheet2.include`:

```markdown
<!-- markdownlint-disable -->
<pre class='metadata'>
Title: DS Code Convention C++
Shortname: cpp-code-convention
Level: 1
Revision: 1
Status: DREAM
Group: ds-devops
URL:
Markup Shorthands: markdown yes
Date: 2021-01-04
Toggle Diffs: no
Indent: 2
Boilerplate: style-syntax-highlighting no
Local Boilerplate: header yes, stylesheet yes, stylesheet2 yes
</pre>

Test test
```

With `header.include` next to the `main.bs` and two file `stylesheet.include`,`stylesheet2.include` :

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>[TITLE]</title>
  <style type="text/css" data-fill-with="stylesheet"/>
<style type="text/css" data-fill-with="stylesheet2"/>
</head>

<body class="h-entry">
<div class="head">
  <p data-fill-with="logo"></p>
  <h1 id="title" class="p-name no-ref">[TITLE]</h1>
  <h2 id="subtitle" class="no-num no-toc no-ref">[LONGSTATUS],
	<span class="dt-updated"><span class="value-title" title="[CDATE]">[DATE]</span></h2>
  <div data-fill-with="spec-metadata"></div>
  <div data-fill-with="warning"></div>
  <p class='copyright' data-fill-with='copyright'></p>
  <hr title="Separator for header">
</div>

<div class="p-summary" data-fill-with="abstract"></div>
<div data-fill-with="at-risk"></div>

<nav data-fill-with="table-of-contents" id="toc"></nav>
<main/>
```

Also putting every `*.include` it into `ds-devops` subfolder, does not work, even though its described in the Docs?

**Comment by tabatkins** [comment]
> Using the following does not include stylesheet2.include:

Ah, so Bikeshed only grabs boilerplate *files* from a predetermined set. The `Local Boilerplate` metadata just tells Bikeshed which of these should be grabbed from the same folder as the spec, rather than fetching from the pre-included boilerplate files. (This is useful for several things, notably calling Bikeshed on a URL, so it knows that it needs to modify the URL to find those files.) So adding files that Bikeshed doesn't know about won't do anything.

> Also putting every *.include it into ds-devops subfolder, does not work, even though its described in the Docs?

That's talking about the pre-included boilerplates, but I grant that my documentation isn't super clear. That entire section kinda needs to be rewritten for clarity, tbh.

But yeah, local boilerplates are just looked for in the same folder as the spec.
