### ISSUE TITLE
Trailing commas in WebIDL enums are no longer allowed

### ISSUE THREAD

**Issue by kainino0x** [tabatkins/bikeshed#2287]
Trailing commas in WebIDL enums broke in Bikeshed 3.6.0/3.7.0.
WebGPU ran into this here: https://github.com/gpuweb/gpuweb/pull/2966 (we've easily worked around it for now). Example:

```webidl
enum GPUPowerPreference {
    "low-power",
    "high-performance",
};
```

According to my local git bisect of Bikeshed:
> 18533a7d9027182f83a429ecfdb1b18338257f8d is the first bad commit

Based on the title of the commit, it doesn't seem like this was an intentional change.

**Comment by tabatkins** [comment]
OHHHHH, okay, so this warning has been raised for the last two years (<https://github.com/plinss/widlparser/blame/main/widlparser/productions.py#L733>), but I didn't supply a "warn()" method on the marker before; I gave one now because it's part of the interface and mypy was complaining. Without one, the code just failed to emit the warning.

But hm, not sure why this is a warning in the first place, that's not "legacy IDL", it's just a normal part of the grammar. I'll submit a PR to widlparser to get this fixed properly.

**Comment by tabatkins** [comment]
Closing as this isn't a Bikeshed issue per se, and I'll fix it upstream. I'll reopen if there's some reason I can't get it fixed there.

**Comment by tabatkins** [comment]
(PR up at <https://github.com/plinss/widlparser/issues/76>)
