### ISSUE TITLE
Add hyperlink that goes directly to a paper, not to the References section

### ISSUE THREAD

**Issue by jwakely** [tabatkins/bikeshed#2299]
When reading ISO C++ proposals written in Bikeshed I find it extremely tedious to click on a reference like [PnnnnR0] and get taken to the references section at the end of the paper. Once there I have to manually scan through the references to find the one I clicked on (because the browser doesn't put it at the first line because we're at the end of the doc), and then click again. I don't care about the nicely formatted references section that makes it look like a nice academic paper. I just want to go to PnnnnR0 and read the flipping paper!

As mentioned, the experience is made worse by the fact that the link to the references usually doesn't place the relevant one at the top of the browser pane, because it's near the end of the doc e.g. https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p0323r12.html#biblio-p1051r0 just takes me to "somewhere in the references" and then I have to find the one I want from among a sea of other refs with not very memorable paper numbers.

Would it be possible to add a little "link" icon (e.g. U+1F517) after a reference that has an associated URL, so that it appears as [PnnnnR0]:link: and I can click the icon to go straight to the paper, not to the References section?

It would also be nice if the `<a>` element for references had a `title` attribute, so you could see the name/title of the reference without having to click to jump to the end of the doc, then go back to where I was reading.

Personally, I'd just make the reference in square brackets link directly to that reference's URL in the first place ... does anybody really want to jump to the References when clicking that? Most of the time I just want to read the actual paper being referenced, so I want to open it in a new browser tab ASAP. But I might be in the minority there.

**Comment by tabatkins** [comment]
The current "link goes to the bibliography, you can click thru from there" design was just inherited from W3C standard practice.

That said, the behavior you want is accessible, both on a link-by-link basis (writing `[PnnnR0 direct]` or `[PnnnR0 inline]`; the former retains the normal biblio styling, while the second supplies the reference title instead) or whole-document (using the `Default Biblio Display` metadata). See <https://tabatkins.github.io/bikeshed/#biblio-mods> for details.

Since I added that feature specifically at the request of C++ folks (because yeah, y'all've got terrible paper names), maybe it makes sense to apply that as a default, in <https://github.com/tabatkins/bikeshed-boilerplate/blob/main/boilerplate/wg21/defaults.include>? I'd be happy to accept a PR, particularly if @brycelelbach or @jfbastien (or whoever is now in charge of that stuff if they're no longer the right people) +1 it.

> Would it be possible to add a little "link" icon

Just drop a `a[data-link-type="biblio"]::after { content: "\1f517"; }` into your stylesheet. Or, again, make it C++-wide and put it into y'all's boilerplate <https://github.com/tabatkins/bikeshed-boilerplate/blob/main/boilerplate/wg21/header.include>.

> It would also be nice if the `a` element for references had a title attribute, so you could see the name/title of the reference without having to click to jump to the end of the doc, then go back to where I was reading.

Ah, now that's something I'm not already doing, and which would be a great idea in general. Tracked in #2300.

**Comment by jwakely** [comment]
Oh cool, I had no idea this was already doable! I'll send a PR now. Thanks.

**Comment by jfbastien** [comment]
+1 from me :)
