### ISSUE TITLE
Multiple elements with same id when spec referenced 3 ways

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#2349]
Given:

```bikeshed
<pre class='metadata'>
Title: Your Spec Title
Shortname: your-spec
Level: 1
Status: w3c/UD
Group: WGNAMEORWHATEVER
URL: http://example.com/url-this-spec-will-live-at
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Abstract: A short description of your spec, one or two sentences.
</pre>

Introduction {#intro}
=====================

[[REPORTING]]

[[REPORTING#try-delivery]]

[=report/url=]
```

Bikeshed gives the warning:

```
WARNING: Multiple elements have the same ID 'biblio-reporting'.
Deduping, but this ID may not be stable across revisions.
```

Removing any of the 3 ways of referring to the `reporting` spec eliminates the warning.

**Comment by tabatkins** [comment]
....huh. Reproduced locally, but this is sure a head-scratcher at first. It's generating two identical biblio entries, but more importantly, how in the *hell* is it only doing so when given *all three*, but *any two* doesn't cause this? I'll dig into this.

**Comment by tabatkins** [comment]
Logging some details for Monday Tab to deal with:

* I only get a duped URL ref (found by dedupBiblioReferences) when both the biblio and section links are present
* Biblio and section links are generating a REPORTING-1 key in normativeRefs, the autolink is generating a REPORTING key

**Comment by jyasskin** [comment]
I thought you'd enjoy that symptom.

**Comment by tabatkins** [comment]
On their own:
* biblio link generates a "REPORTING" informative ref
* section link generates a "reporting-1" normative ref
* autolink generates a "reporting-1" normative ref

(all have the same url; "REPORTING" is from SpecRef while "reporting-1" is from Shepherd)

Two at a time:
* biblio + section => "reporting-1" normative, "REPORTING" informative, duped "shepherd + specref" url detected
* biblio + autolink => "REPORTING" normative, "REPORTING" informative, no duped url detected (both either a shepherd or specref reference)
* section + autolink => "reporting-1" normative, "REPORTING" informative, duped "shepherd + specref" url detected

All three:
* "REPORTING" and "reporting-1" normative, "REPORTING" informative, duped url detected, and two entries in the index

So biblio will always get from SpecRef if possible. Autolink gets its linking data from Shepherd, but then fetches a biblio ref according to the dfn's spec name; this can potentially get either but uses the same "prefer SpecRef when possible" rules. But it looks like section autolinks *always* just use Shepherd data, presumably since I'm drawing the heading data from Shepherd as well.

I think I should make section autolinks fetch the biblio ref in the same way as normal autolinks.

**Comment by tabatkins** [comment]
And yup, that did it, *and* it fixes a persistent issue I've seen where the same spec shows up twice in the refs.
