### ISSUE TITLE
--just-tar doesn't seem to work

### ISSUE THREAD

**Issue by jakearchibald** [tabatkins/bikeshed#2404]
I ran `bikeshed echidna --just-tar` against https://github.com/w3c/csswg-drafts/tree/main/css-view-transitions-1, and it appears to build the spec, but doesn't seem to output `test.tar` (there's no additional file in the directory).

This is on MacOS.

The regular `bikeshed echidna` with credentials works fine.

**Comment by tabatkins** [comment]
Hm, that's because the --just-tar option appears to have never worked. It just causes the code to create and use a `test.tar` file in the working directory, but then at the end it deletes the file. (And returns the bytes from it, but the CLI option doesn't do anything with the return value anyway.)

Presumably I just want to write the bytes to stdout so you can use a pipe to do whatever you want with them?

**Comment by tabatkins** [comment]
Ah, yup, some blame digging shows that it *used* to work, and I accidentally broke it in <https://github.com/tabatkins/bikeshed/commit/f4ea8dbce273573533f47311506cf21b333a32d8#diff-e933e8c90041283bbc380d9b4cb62f7b5a8338da07a25dfdf51423e557cf6efd> when I changed the return type of the function to be bytes.

Do you prefer having the old behavior (leaving an arbitrarily-named file in the current directory) or getting the file on stdout?

**Comment by jakearchibald** [comment]
I don't have a strong preference.

Thinking about other cmd line tools I've used, for binary output, writing a file seems to be the more common pattern, but stdout is definitely more versatile.

If you can be bothered doing both:

```
bikeshed echidna --just-tar
```

⬆️ output to stdout

```
bikeshed echidna --just-tar -o test.tar
```

⬆️ write to `test.tar`

Although I guess the latter is kinda redundant due to:

```
bikeshed echidna --just-tar > test.tar
```

**Comment by tabatkins** [comment]
Right, the ease of piping to an output file is why I'm thinking I just print it to stdout ^_^
