### ISSUE TITLE
Remaining specs not in WebRef

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#2431]
Heya @tidoust I'm trying to switch over to WebRef exclusively, but there's still a handful of specs present in Shepherd that aren't in WebRef.

<details><summary>Full List</summary>
<pre>
box-tree-api-1
css-2007
css-2010
css-2015
css-2017
css-2018
css-2020
css-2021
css-2022
css-color-3
css-color-6
css-color-hdr-1
css-conditional-values-1
css-contain-1
css-egg-1
css-fonts-3
css-forms-1
css-grid-1
css-marquee-3
css-mobile
css-page-template-1
css-parser-api-1
css-preslev-1
css-print
css-template-1
css-tv-1
css-ui-3
css-writing-modes-3
css1
custom-1
dom-level-2-style
hr-time-2
matrix
mediaqueries-3
navigation-timing-1
page-visibility-2
payment-method-basic-card-1
payment-request-1
promises-guide-1
resource-timing-2
scroll-customization-api-1
selectors-3
selectors-nonelement-1
web-bluetooth-1
webdriver1
</pre>
</details>

Broadly these are three categories: 
* CSS specs that haven't been published to /TR yet (still ED/UD)
* CSS specs that *have* been published to /TR but are older
* Others (varied) - some WHATWG, some CG

The first category is fine, tho I'd like to have a way to add them to the WebRef spider (probably there already is).

The second category confuses me. Why is that happening? We definitely need the older versions for several of the specs, as for a few the WebRef data is only delta specs and thus would be missing a lot of terms defined in the earlier levels.

The third category is also a little concerning. How are these sorts of specs collected? Is it manual, so they just need to be added? Or is there a hole in some auto-collection process?

**Comment by tidoust** [comment]
> Heya @tidoust I'm trying to switch over to WebRef exclusively, but there's still a handful of specs present in Shepherd that aren't in WebRef.

Nice :)

The list of specs in Webref comes from [w3c/browser-specs](https://github.com/w3c/browser-specs/#web-browser-specifications). The starting point of browser-specs was to list specs that are directly implemented in browsers or about to be. The README lists [selection criteria](https://github.com/w3c/browser-specs/#spec-selection-criteria). These criteria leave some leeway as to which specs can make it to the list.

On top of these, the list has now been extended to also contain non-browser specs (we divided the exports into two NPM packages: the `web-specs` package contains all specs, the `browser-specs` package only contains specs directly targeted at browsers). Webref uses the full list, so no problem extending the list in theory.

All in all, we can probably relax the rules we've followed so far and add more specs, especially if that's useful on your side. I'll work on the list with @dontcallmedom after the holidays and will report on progress. Some comments and questions below in the meantime.


> The first category is fine, tho I'd like to have a way to add them to the WebRef spider (probably there already is).

Yes, specs in the first category can be added. We typically track specs that are marked as "unofficial", "not ready for implementation", or as "collection of interesting ideas" in a [monitoring list](https://github.com/w3c/browser-specs/blob/main/src/data/monitor.json) and only add them once there is a clearer implementation story (entries in the monitoring list are reviewed every three months). I think that we can relax that rule and add specs sooner when they are under the umbrella of a working group, perhaps with some "unofficial" flag or something like that.


> The second category confuses me. Why is that happening? We definitely need the older versions for several of the specs, as for a few the WebRef data is only delta specs and thus would be missing a lot of terms defined in the earlier levels.

Motivating goal for the list was to document the "current" web platform, so we haven't included older specs on purpose. That said, we should never start from a delta spec (for instance, the list includes the `css-color-5` delta spec, but also the `css-color-4` full spec). Do you have an example of a situation where lots of terms are missing?

We could add previous levels easily. We could also add obsolete specs if that seems needed. I wonder about the value though. What is the intended usage? Are there specs that reference them in any way? Is it more for historical reasons or to be comprehensive? To always have the latest Recommendation in the list in leveled specs?

I'm asking about usage because not having them in the list means it's harder for a spec to reference their terms. We tend to view that as a good thing. Also, in terms of usage, we know that MDN does not need these older specs for their documentation. 

> The third category is also a little concerning. How are these sorts of specs collected? Is it manual, so they just need to be added? Or is there a hole in some auto-collection process?

We have a job in place that [finds new specs](https://github.com/w3c/browser-specs/blob/main/src/find-specs.js). These candidate specs are then reviewed and either added to the main list, to the monitoring list, or to the ignore list when we're confident we won't add them in the foreseeable future. The job tracks a number of sources, including WHATWG, CSS, SVG, TC39, WICG and of course W3C repositories.

Looking at the list you reported, if there's a hole, it does not seem to be caused by that auto-collection process, more by the rules we follow to decide whether a spec should be added to the list or not.

The specs you listed more or less matches the list discussed in https://github.com/w3c/browser-specs/issues/50#issuecomment-645489318 back in 2020. We have more ways to categorize specs in the list, so I think we can now include more of them in the list.

<details>
  <summary>Rationale per group of specs</summary>

  > css-2007
  > css-2010
  > css-2015
  > css-2017
  > css-2018
  > css-2020
  > css-2021
  > css-2022
  > promises-guide-1

  These are the type of non-normative documents that we didn't include in the list, and now only add when needed. We could probably be more systematic about these from now on. For older versions of `css-xxxx`, same question as for "older specs": what is the intended usage?

  > css-color-3
  > css-contain-1
  > css-fonts-3
  > css-grid-1
  > css-ui-3
  > css-writing-modes-3
  > hr-time-2
  > mediaqueries-3
  > navigation-timing-1
  > payment-request-1
  > selectors-3
  > webdriver1

  These are not in the list because they are before the "current" level. Current level is in the list.


  > box-tree-api-1
  > css-color-6
  > css-color-hdr-1
  > css-conditional-values-1
  > css-forms-1
  > css-page-template-1
  > css-template-1

  These specs are in our monitoring list. We could add them to the list, perhaps categorizing them as "unofficial".


  > css-egg-1

  We could add it to the list. I'm worried that this could create confusion, as that would add units such as Parsec (`pc`) to the cross-referencing database, which would clash with the official Picas unit. Spec authors that use ReSpec need to be explicit about the list of specs they reference, but that means they would have to choose between `css-egg` and `css-values` if they need to reference `pc`. That's a good way to promote `css-egg` though ;)


  > css-marquee-3
  > css-mobile
  > css-preslev-1
  > css-print
  > css-tv-1
  > custom-1
  > matrix
  > payment-method-basic-card-1
  > scroll-customization-api-1
  > selectors-nonelement-1
  > css1
  > dom-level-2-style
  > page-visibility-2

  These are retired/obsolete/replaced/superseded specs in your second category.

  Additional notes:
  - There is no actual spec for `scroll-customization-api-1` as far as I can tell.
  - `css1` and `dom-level-2-style` do not use `<dfn>` to mark definitions, so you would only get headings out of them. I haven't checked others.
  - The `page-visibility-2` spec was folded into HTML. We no longer have it in the list not to create duplicate IDL terms. That would not be a problem if we flag such specs as "superseded". But then, same question as usual, what is the point?


  > css-parser-api-1

  It is in the list under `css-parser-api` as there is no level in the WICG shortname.


  > resource-timing-2

  It is in the list under `resource-timing`. The group no longer versions the spec.


  > web-bluetooth-1

  It is in the list under `web-bluetooth`.
</details>

**Comment by tabatkins** [comment]
Yeah, after doing a more thorough diff of the URLs between the two sources, it looks like all I really care about are the following:

* https://drafts.csswg.org/css-2022/
* https://drafts.csswg.org/css-color-3/
* https://drafts.csswg.org/css-color-6/
* https://drafts.csswg.org/css-color-hdr/
* https://drafts.csswg.org/css-conditional-values-1/
* https://drafts.csswg.org/css-contain-1/
* https://drafts.csswg.org/css-display-4/
* https://drafts.csswg.org/css-forms-1/
* https://drafts.csswg.org/css-grid-1/
* https://drafts.csswg.org/css-ui-3/
* https://drafts.csswg.org/css-writing-modes-3/
* https://drafts.csswg.org/mediaqueries-3/
* https://drafts.csswg.org/selectors-3/
* https://drafts.csswg.org/selectors-nonelement-1/
* https://www.w3.org/TR/DOM-Level-2-Style/

(and their /TR equivalent URLs, when applicable)

Everything else that's different between the sources is either a previous version that probably *isn't* relevant, or a rescinded spec, or just a mistake.

**Comment by tabatkins** [comment]
That said, the set is small enough that I'm going to go ahead and throw the switch on using WebRef as the primary dfn source later today.

**Comment by tabatkins** [comment]
Fixed the Display 4 issue. ^_^
