### ISSUE TITLE
"multiple-word" is not equal to "multiple word"

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#319]
Bikeshed generates the same ID for both `<dfn>source expression</dfn>` and `<dfn>source-expression</dfn>`; it's arguable that I shouldn't have defined both those terms, but I did, and it broke. :(

Perhaps the latter could canonicalize to `source--expression`, since it's probably less common than the former?

**Comment by mikewest** [comment]
(ID generation aside, though, you're doing the right thing with linking, which is great!)

**Comment by tabatkins** [comment]
I added an argument to simplifyText to cause this dashes-become-underscores behavior, and now invoke it for "dfn" type definitions, and headings.

**Comment by fantasai** [comment]
This change broke links on my specs. Also underscores suck for URLs. I don't think we should make things worse for everybody just because somebody defined "foo-bar" and "foo bar" as different terms and wants that to automatically work out.

**Comment by tabatkins** [comment]
Why do underscores "suck"?  Why is anyone caring about the look of the ID in the first place?  That's what auto-linking is for, and making it work automatically for more things is more better.

**Comment by fantasai** [comment]
Because they blend in with underlines, which is commonly used to format links. (Also they're harder to type.) Auto-linking is great for things that auto-link, but people cut and paste URLs to specs all over the place.

Also, your change probably broke a lot of links into our specs from outside our auto-generated ecosystem. Changing it break would break some newer links, but would fix those older ones (of which I'm sure there are more).

**Comment by fantasai** [comment]
Another reason not to make this change is that a term might change from hyphenated to unhyphenated or vice versa, and that very superficial change would also break links.

**Comment by fantasai** [comment]
For the case where someone has created "foo-bar" and "foo bar" as distinct terms, that's very unusual and can be handled by manually specifying the ID. I think the other cases here, for which reverting this change would be beneficial, are more common.

**Comment by mikewest** [comment]
If I'm the only one using this, then back it out and I'll deal with it.

That said, I use this all over the place. The `Content-Security-Policy` HTTP response header is not the same as the "Content Security Policy" concept, the `source-expression` ABNF rule name is not the same as the "source expression" concept, and so on. It surprises me that it hasn't bitten anyone else.

**Comment by tabatkins** [comment]
All right, I'm gonna go ahead and revert this.  Sorry about that, Mike.  I'll give you time to set your IDs manually; just ping this thread when you're ready.

**Comment by mikewest** [comment]
*shrug* Again, I don't see this as unusual for specs that deal with either HTTP headers or ABNF rules. Perhaps it's unusual for CSS specs?

Just revert the change. I'll deal with it. :(

**Comment by tabatkins** [comment]
It doesn't appear to be too common.  And underscores *are* uncommon; every time I've had to do `<pre class=anchors>` for a dashed term, I've had to manually specify the ID, because Bikeshed's attempt at auto-generation was inserting underscores.

**Comment by domenic** [comment]
Why not just go with the OP's suggestion of dashed-term becoming dashed--term?

**Comment by tabatkins** [comment]
That *also* doesn't match existing usages.  @fantasai's point is that if you convert specs to Bikeshed (rather than writing them in Bikeshed originally), basically **all** dashed terms have a simple single-dash ID too (that is, "foo-bar" becomes "#foo-bar".  This is really consistent, and breaking it means that you have to remember to manually set the ID when converting.  You also have to manually specify the ID when using `<pre class=anchors>`.

The cost of Bikeshed yelling at you to manually specify an ID when there's a collision between "foo bar" and "foo-bar" within a single document seems to be worthwhile for the usability benefits.
