### ISSUE TITLE
Syntax highlighting overwrites in-example links.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#327]
Example code may contain links, for instance:

    <pre>
        if (!navigator.<a idl>credentials</a>)
            return;
    </pre>

might link to the IDL definition in the same spec, for ease of whatever.

Syntax highlighting doesn't respect in-code markup, and drops the links entirely. This makes me a bit sad, but is probably a bug with Prism more than Bikeshed. :(

**Comment by tabatkins** [comment]
Indeed.  The only way around it is to turn off syntax highlighting for that element.  Otherwise, syntax-highlighted things are treated similarly to IDL blocks, in that their text is processed and replaced without concern for any markup inside.

I can file a bug on Prism, but I'm not confident about this getting fixed.  Closing on my side for now; I'll reopen if there's any change.

**Comment by tabatkins** [comment]
Prism's website has an example of how to work around this, to some extent - rather than highlighting at the block level, wrap the stuff before/after the link in `<code>`s with highlighting turned on.  For example:

```html
<pre class='metadata'>
Title: test
Group: test
Status: UD
ED: http://example.com
Shortname: test
No Editor: true
Abstract:
</pre>

<pre>
    <code class='lang-javascript'>if (!navigator.</code><a idl>credentials</a><code class='lang-javascript'>)
        return;</code>
</pre>

<dfn attribute for=Foo>credentials</dfn>
```

This produces a reasonably-highlighted block of code.  It's a bit annoying, of course.
