### ISSUE TITLE
Why do syntax highlighting at runtime instead of compile time?

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#332]
Bikeshed is so good at doing everything else ahead of time. Why resort to ReSpec-style in-browser compilation of the examples into highlighted examples?

**Comment by tabatkins** [comment]
Because adapting Prism to Bikeshed was trivial, but porting it wouldn't have been. Patches welcome.

**Comment by domenic** [comment]
Ah I see, I thought Prism would have a Python version. Maybe pygments?

**Comment by tabatkins** [comment]
I'll look into it!

**Comment by tabatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/682840/8344253/fa98524e-1a93-11e5-9164-822f926bd72f.png)

So here's a first run at it. Top is Prism, bottom is Pygments with the "friendly" style.  I think I can just make a style that matches Prism, because I like its colors.

**Comment by tabatkins** [comment]
And it's now finished and pushed. Please let me know if you encounter any problems (beyond the initial error it'll spit out asking you to install pygments)!

**Comment by tabatkins** [comment]
Oh yeah, and this is what it looks like now that I've aped the Prism styling: 

![image](https://cloud.githubusercontent.com/assets/682840/8360856/4f01c33e-1b24-11e5-9d95-cf065fd91f86.png)

Not 100% identical, because tokens are categorized a little differently, but close enough for government work.

**Comment by domenic** [comment]
<3!
