### ISSUE TITLE
Simplify Link Defaults

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#339]
It would be nice if Link Defaults could take just a list of specs. Then I could list the specs I expect to link to and not have to have this excessively long and difficult to visually-parse and annoying to maintain list of values I want from this other spec.

(Might also consider a list of "things I definitely don't want to link to". For example, I never want to link to the Web Animations spec, but it's making me clarify which version of 'left' etc. I want to link to. The CSS one, of course!)

**Comment by tabatkins** [comment]
I need to figure out why Web Anim is defining the 'left' property in the first place, and make them stop.  I think it might be Shepherd being too aggressive in parsing out things that look vaguely like definitions.

Would you prefer switching to the block form of link defaults?  It's a little longer, but much easier to read.  For Writing Modes, it would be:

```html
<pre class='link-defaults'>
type: property
    spec: css21
        text: display
        text: min-height
        text: max-height
        text: min-width
        text: max-width
        text: clip
        text: left
        text: right
        text: bottom
        text: top
    spec: css-text-3
        text: letter-spacing
    spec: css-text-decor-3
        text: text-decoration
    spec: svg2
        text: glyph-orientation-vertical
        text: glyph-orientation-horizontal
</pre>
```

The reason I'm hesitant to do a "always choose this spec" thing is that it's easy to accidentally over-match and have a term that *should* link somewhere else accidentally link into one of your "always" specs.  This is a silent error, which I'm afraid of.

I'm fine with adding a "no shut up, don't link to these specs" option, though.  Worst thing that could happen is something fails to match when it should, and you'll know about that.

**Comment by fantasai** [comment]
Well, simply being able to wrap the line would be helpful. If you're requiring indentation, though, then it'd be nice to just drop all those keywords and just rely on the indentation level to say whether it's a type/spec/text. Or pick some kind of readable ASCII list markup.

Wrt "always choose this spec" silent errors... I think that might be true for values, but for properties it's unlikely to be an issue. We don't have multiple propdefs of the same property, generally.

**Comment by fantasai** [comment]
This is pretty compact, but also readable, fwiw:

css21: display, min-height, max-height, min-width, max-width, clip, left, right, bottom, top
css-text-3: letter-spacing
css-text-decor-3: text-decoration

(I'm not sure what its syntactic context would be, but it's way easier to read than the current Link Defaults.)

**Comment by tabatkins** [comment]
> Well, simply being able to wrap the line would be helpful.

You can split it across multiple Link Default lines.  Put one spec per line, if you like.

> Wrt "always choose this spec" silent errors... I think that might be true for values, but for properties it's unlikely to be an issue. We don't have multiple propdefs of the same property, generally.

The number of ambiguous propdef links in your spec that you have to resolve with Link Defaults seems to suggest the opposite.  We define the same property in multiple specs rather often (usually because we're *replacing* the definition and moving it into another spec).

Wrt readability, for more complex data I'm purposely using a [single reusable format](https://github.com/tabatkins/bikeshed/blob/master/docs/infotree.md) now, to make it easier to learn how to use Bikeshed.  Learning a bunch of specific grammars is okay for small pieces of metadata, but it makes it unnecessarily complicated when dealing with larger things.

For example, your example structure doesn't allow one to indicate the type of the data, or its `for` value, both of which are important for Link Defaults (and the latter of which I can't easily add to the Link Default metadata line).  InfoTree is slightly more verbose, but it's structured and easy to tell what's going on, and rearrangeable so you can compactify things as needed (very useful when defining a bunch of anchors; see CSSOM View source for an example).

**Comment by tabatkins** [comment]
Also, I totally forgot about the `autolinker-config.md` file that specifies a bunch of Bikeshed-wide link defaults.  We haven't put new stuff into it for a while, but as more specs get parsed correctly you'll run into more conflicts.  Feel free to add some of these to that file when there's a particular definition you definitely want by default.

**Comment by tabatkins** [comment]
Oh, and the current `autolinker-config` syntax is terrible, one of my biggest mistakes.  It was way too cute.  I need to come up with an InfoTree version of it, move it into the Bikeshed repo, and let you specify its stuff locally.  That'll let you ignore specs entirely, always prefer one spec in preference to another, etc.

**Comment by tabatkins** [comment]
#346 now covers the things that I plan to enable for this issue, so I'll close this one.
