### ISSUE TITLE
Move the specberus ID to a separate argument

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#369]
Heya @mikewest, I think I'd be happier if the Specberus ID was a separate comma-separated argument, rather than just inferred as the last token of the editor name if it's numeric.  That way we can handle expansion better in the future if necessary.

I'm thinking just `specberus <id>` for the syntax.  I think you're the only one using it for now, so does that sound okay?

**Comment by darobin** [comment]
Is this about the editor ID? If so, please don't tie it to the "Specberus" name. Specberus had a bug that required its presence for a while, but that bug is gone — the ID is unrelated to that. The ID is required for Echidna, the automated publishing system. Yet I *still* would not call it "echidna". It's just the Editor ID, it should be called something like that. ReSpec calls it `w3cid`; not great but it reflects that it's one's user id in that system.

**Comment by mikewest** [comment]
Sorry, I missed this issue, Tab. I'm fine changing my specs to whatever you like. Just tell me how you'd like it to look.

**Comment by tabatkins** [comment]
@darobin Yeah, this definitely isn't a generic "id"; it's a value for one specific publishing system.

If you think there won't be something else reasonably called a "W3C ID", then I'm fine with the name `w3cid`.  Otherwise, I'd prefer a name that reflects the specific publishing system that's using this.

**Comment by darobin** [comment]
The ID is that of users of the W3C system. It's used by Echidna but also by a lot of other (currently internal) tools. Anything W3C related that will call upon people's identity will use the same ID.

It really isn't tied to Echidna, though I think it's the first time it's surfaced. That said if you wish to give it a name other than "w3cid" please don't make it anything to do with Specberus because that is *completely* unrelated.

**Comment by tabatkins** [comment]
Nope, that's good enough, I'll call it `w3cid`.

**Comment by tabatkins** [comment]
@mikewest I've now added this; providing your ID as another comma-separated value containing `w3cid ####` works.  I've left in the "if the last token of the editor name is numeric" handling for now, to ease your migration, but I'll remove that code next week or so when I remember to do it.
