### ISSUE TITLE
It's tough to define slots in a consistent way.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#393]
I'd like to define slots along with the other WebIDL properties, a la https://w3c.github.io/webappsec/specs/credentialmanagement/#dom-credential-internaltype. I'm currently forced to call the slot an `argument` as that triggers the `{{whatever}}` shortlinking goodness, but doesn't attempt to add type information. I'd prefer to make it an `attribute`, as that's a closer fit. Perhaps we could just add `slot` as a type?

@domenic might have opinions, as he's probably slotting it up too.

**Comment by tabatkins** [comment]
Call it an `attribute`, because that's what it is (just a private one).  The `{{foo}}` autolinking handles the square brackets for you, so there's no need to escape anything to prevent it from looking like a biblio link; just write `{{[[internaltype]]}}`.

I see the issue you're having with the typing information.  I'll special-case that bit so that it doesn't complain that it can't find a `[[foo]]` in the IDL block. ^_^  Fix incoming.

**Comment by tabatkins** [comment]
Done.
