### ISSUE TITLE
Why does - convert to _ with links?

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#404]
This is changing a whole bunch of links and also caused a bunch of regressions for URL which were somewhat annoying to fix.

**Comment by tabatkins** [comment]
Because of #319.

If you're converting a spec that previously used a different processor (particularly Anolis), you *probably* don't want to rely on Bikeshed's auto-generation of IDs, as it's pretty likely to give a different ID and break links.  Instead, specify the old IDs on all the `<dfn>`s manually.  (With anolis, this is just a matter of changing `title` to `id` on all your `<dfn>` elements. Then you can generally just remove `title` from all your `<a>`s - autolinking will usually take care of things for you.)

When I have a little spare time this week I'll review what you're doing with URL and see if you're fixing things in a good way or not. ^_^

**Comment by annevk** [comment]
But I also don't like the new IDs. I don't want underscores in them :-(

**Comment by tabatkins** [comment]
Then you can override them when desired, by using `<dfn id>` yourself. ^_^

(Sorry this doesn't help you, but since most people don't really care about their IDs, prioritizing ease-of-use wins over pretty IDs.)

**Comment by annevk** [comment]
It's not clear to me that what @mikewest does is actually easy for the reader, having to distinguish those terms. And as long as browsers show URLs, they are also part of the interface and not primarily a concern for specification editors, but also for users. And users prefer - over _ in URLs.

**Comment by mikewest** [comment]
What am I doing that you don't like?

**Comment by tabatkins** [comment]
Defining two terms that differ only by the presence/absence of a hyphen, thus necessitating the bugfix in #319.

**Comment by mikewest** [comment]
*shrug* That still doesn't seem terrible to me, and I end up doing it pretty much every time I use ABNF (https://w3c.github.io/webappsec/specs/content-security-policy/ has a number of examples). How would y'all suggest that I go about things?

**Comment by annevk** [comment]
I don't understand what you're doing with e.g. `source-expression` since for almost every other term such as `style-src` and such you are fine using the hyphen outside of the ABNF context.
