### ISSUE TITLE
Stop emitting </p>

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#460]
It creates a lot of noise in the generated diff.

**Comment by tabatkins** [comment]
I kinda gotta leave those in, actually.  The auto-closing rules for `<p>`s are confusing, and back when I didn't emit closing tags, specs regularly hit problems where elements merged into the preceding paragraph.

**Comment by annevk** [comment]
Do you have any concrete examples? The only time I ran into that is with `<form>` which was a browser bug that got fixed.

**Comment by tabatkins** [comment]
Hm, actually, looking at HTML and Bikeshed's code, there's not much reason.  I thought `<figure>` was one, but that auto-closes `<p>`. Then I thought `<img>` was a problem, but they're considered "inline elements" to Bikeshed's Markdown parser, so they'll get put in their own paragraph.

The only real problem, then, is custom elements, since they never auto-close `<p>`.
