### ISSUE TITLE
Some line breaks in code examples are stripped off

### ISSUE THREAD

**Issue by LeaVerou** [tabatkins/bikeshed#473]
```
		<pre>background: conic-gradient(black 25%, white 0deg 50%, black 0deg 75%, white 0deg);
		background-size: 60px 60px;</pre>
```

Live https://drafts.csswg.org/css-images-4/#example-e6fc165a

**Comment by tabatkins** [comment]
I explained this in person - it's because the code is catering to HTML's dumbness. Bikeshed allows (and in fact prefers) the `<pre>` tags to be on their own line, with the content between them, and will correct the markup for you to make HTML happy.  It will also anti-correct the markup if you're catering to HTML. ^_^

Closing because I'm not that interested in fixing this bug; adjust the markup to make Bikeshed happy also makes it more readable.
