### ISSUE TITLE
Inlining GitHub Issues hits API rate limit

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#492]
One workaround is to use the API to [list issues of a repository](https://developer.github.com/v3/issues/#list-issues-for-a-repository) instead. Make sure to fetch them all using the data provided by the [Link headers](https://developer.github.com/v3/#link-header). This should limit the number of requests to 3-4 for a large repo, instead of _n_ as is currently the case.

Another (better) workaround is to allow passing credentials to bikeshed which should boost the number of authorized requests from 60 per hour to 5000. See https://developer.github.com/v3/#rate-limiting. 

---

* [x] Cache responses locally, and use conditional queries to see if anything changed <https://developer.github.com/v3/#conditional-requests>
* [ ] Use pagination to make fewer requests; construct paging from the requested issues <https://developer.github.com/v3/#pagination>
* [x] Let people use auth to increase their own API limits <https://developer.github.com/v3/#rate-limiting>

**Comment by tabatkins** [comment]
Okay, I've editted in a list of things I need to do. I'm being terrible naive in my treatment right now.

**Comment by tabatkins** [comment]
All right, caching and conditional responses are now in use, so hitting rate limits should be *much* rarer now; you'll only run into it if you're processing for the first time and use a bunch (> 60) of inline issues, and then it just means you have to wait an hour for your limit to refresh and Bikeshed will pick up where it left off.  (Bikeshed emits an informative error message for this case.)  Or get an OAuth token once, so it can blast thru your issues list; unless more than 60 issues have changed since the last time you ran Bikeshed, you won't need that token again.

Paging turned out to be a dud; I can't reliably predict what pages the issues will be on unless I slurp down *all* issues including closed ones, and (a) I don't think I want to speculatively cache every issue in your whole repo, and (b) I'm not sure how conditional responses work in that case.  Making individual requests per issue isn't a big deal now, so I'm going to consider this issue closed.
