### ISSUE TITLE
Whitespace trailing em-dash is removed only if there's a newline

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#507]
From `mediasession.bs`:
```
When the {{play()}} method on a <a>media element</a> is invoked from script —
or a <a>media element</a> is otherwise played from the web page
```

As of https://github.com/tabatkins/bikeshed/commit/323e3cf0d88da469d30cc7fbfc9df389290f1a93 the output of this has changed from
```
script —
or
```
to
```
script —<wbr>or
```

Intentional? Is the idea that you shouldn't have whitespace around your em-dashes anyway?

**Comment by tabatkins** [comment]
Yes, that's intentional.   According to common typographic practice, you shouldn't have whitespace around your em dashes, and if a linebreak occurs, it should go after the em-dash.

(The only reason this behavior changed for you is that I bugfixed the em-dash handling - it previously wouldn't fire unless the text was indented.)

Note that Bikeshed has a shorthand for this, so you dont' have to type em-dashes by hand - just end a line with --, like:

```html
When the {{play()}} method on a <a>media element</a> is invoked from script--
or a <a>media element</a> is otherwise played from the web page
```

**Comment by foolip** [comment]
Very well, just checking that this wasn't an unforeseen consequence.
