### ISSUE TITLE
Shorthand for `for`'d `dfn`s?

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#527]
`<a for="whatever">thing</a>` is hard to type for `dfn` types. I'm jealous of IDL's `{{whatever/thing}}` syntax. Can we use some of the remaining punctuation to shorthand regular old `dfn`s? Or at the very least respect the `/` shorthand inside `<a>` (e.g. `<a>whatever/thing</a>`)?

**Comment by tabatkins** [comment]
Possibly. I've avoided it because `dfn` dfns are freeform text; there's no reserved punctuation available to use.  I'd have to make the `for` inference weak, so that if interpreting it as `<a for="foo">bar</a>` fails I can silently fallback to looking for `<a>foo/bar</a>`.

But I feel you.  All the CSS shorthands have use of the `/` syntax too.

**Comment by tabatkins** [comment]
Here are the choices I compiled from last time we had to find a new autolinking syntax:

1. *Triple* angles: `<<<iframe>>>` and `<<<iframe/src>>>`
2. We've double all the matching chars except parens: `((iframe))` and `((iframe/src))`
3. Any special character that markdown hasn't claimed:
    1. `$iframe$` and `$iframe/src$`
    2. `%iframe%` and `%iframe/src%`
    3. `=iframe=` and `=iframe/src=`
    4. `~iframe~` and `~iframe/src~`
4. Any of the above, doubled, for lowered likelihood of collisions?

Do you have any preference on what to use for dfn autolinks, so I can start supporting the inline niceties?

**Comment by tabatkins** [comment]
I'm kinda for `=foo=`, because I do dfn autolinks all the time, and I'd prefer a character I don't need to hit Shift for.

**Comment by mikewest** [comment]
`=` is probably fine. It looks unused in Markdown/Kramdown/Maruku, so we might as well claim it for our own.

I'd kinda like something magically consistent with the other link types, and I'd personally be fine with `<a>whatever/thing</a>`, but shorter probably isn't worse. It just means I'll need to poke at my vim syntax file for highlighting that I'd get for free with the HTML element. :)

**Comment by tabatkins** [comment]
I *very purposely* do not do magic text shenanigans when you're just using plain elements, because otherwise I have to invent an escaping technique for when you really do want to refer to a term with a slash in it, and ugggggggggh.  Instead all the magic goes in the already-magical shorthands, and the "escape" is "use HTML like a peasant".

**Comment by tabatkins** [comment]
Oh yeah, also, the only markdownish language I care about is CommonMark.

**Comment by tabatkins** [comment]
Done - `=foo=` is now a dfn autolink for "foo".  Standard set of syntax features - `=foo/bar=` is equivalent to `<a for=foo>bar</a>`, and `=foo|the real text=` is equivalent to `<a lt=foo>the real text</a>`.
