### ISSUE TITLE
Cross-spec section links?

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#528]
I'd like to reference algorithms in the ED of CSP from other specs. I don't currently have a good way of doing that. :/ 

I guess this is two problems:

1. I'd like to be able to reference headers in other specs.

2. I'd like to be able to build a definition list from specs that aren't in Shepard. If I had a dollar for each spec into which I copy a list of Fetch and CSP definitions, I could probably buy myself two coffees. Maybe three.

**Comment by tabatkins** [comment]
1. is planned - there's even a comment to that effect somewhere.  I have all the data I need, at least for things either in Shepherd or SpecRef.  (Shepherd things can check your link's validity, but at least with SpecRef things you just need the shortname and the anchor.)

2. Yeah, I kinda desperately need to put together a metadata that's just "merge these definitions into the linking database normally" and store that in Bikeshed for exposure to everyone.  (The current anchors block is purposely privileged, and treats its dfns equivalent to local dfns, because you put those dfns into your spec on purpose.)

**Comment by tabatkins** [comment]
Yay! Cross-spec section links now work *as long as the spec is in Bikeshed*.  Syntax is `[[versioned-shortname-3#heading-id]]`, and it substitutes in `Spec's Abbreviated Name §8.1 Heading Title`.  It verifies that the spec and anchor exist.

Next up is putting together a lower-power version that uses biblio data and just trusts that the anchor exists, since anchor data doesn't exist for arbitrary biblio stuff.

**Comment by tabatkins** [comment]
And done now - things in the biblio database can be reffed by a cross-spec section link in the same way, it just reuses the anchor as the section name (because it doesn't know the section number or title) and trusts that the anchor exists.
