### ISSUE TITLE
WebIDL syntax highlighting

### ISSUE THREAD

**Issue by Ms2ger** [tabatkins/bikeshed#542]
`lang-idl` unfortunately selects something else already

**Comment by tabatkins** [comment]
Are you going to be highlighting anything *besides* stuff intended for the auto-parser (which fills in `<a>` and `<dfn>` for you)?

I have a long-term plan to augment the WebIDL parser to also output the classes that the highlighting code uses, so it'll work together automatically.  (Long-term only because I haven't sat down to write it yet, not because it's got a lot of prereqs or anything.)

**Comment by Ms2ger** [comment]
This is for the IDL spec itself; mostly example snippets. Look they to see what they look like exactly?

**Comment by tabatkins** [comment]
Ah, that answers the question then - you want highlighting but *not* autolinking/dfning.  Hmmmmmm.

I think this means I'll need a mode on the IDL parser to emit *just* spans with the highlighting classes, rather than a/dfns with the highlighting classes, when I augment the parser appropriately.  And then I'll special-case the highlighter to skip highlight=webidl elements, and have the idl parser check for that instead.

Okay, cool, got a plan. I'll see about working on this soon.

**Comment by tabatkins** [comment]
And done. That was way easier than I thought it would be.  All WebIDL now gets syntax-highlighted.  Non-normative IDL blocks (currently, those in notes and examples) get highlighting too.
