### ISSUE TITLE
Manual Link Fixups Are Annoying

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#556]
Things that don't link up correctly for TR drafts, that I have to fix up manually before publication, include:
* ''initial'' links to Cascade 4 ED instead of Cascade 3 CR
* Most terms defined in CSS Display Level 3 link to the ED instead of the TR, for no apparent reason. Examples include "formatting context".
* Linking 'overfow' values like 'auto' to the ED of css-overflow-3 instead of (preferably) CSS2.1 or the TR copy

Will add to list as more come up...

**Comment by fantasai** [comment]
Also
  * CSS Pseudo L4: ::first-letter and first formatted line don't link to TR...
  * CSS Images L3 specified size doesn't link to TR
  * large swaths of the bibliography link to the http://dev.w3.org/ EDs

This is all while generating Flexbox CR, fwiw.

**Comment by fantasai** [comment]
biblio-css-values or biblio-css-values-3. Pick one. You're generating broken links.

**Comment by tabatkins** [comment]
> biblio-css-values or biblio-css-values-3. Pick one. You're generating broken links.

Looks like I fixed this.

> Most terms defined in CSS Display Level 3 link to the ED instead of the TR, for no apparent reason. Examples include "formatting context".

The TR wasn't even in Shepherd! Fixed now.

> Linking 'overfow' values like 'auto' to the ED of css-overflow-3 instead of (preferably) CSS2.1 or the TR copy

The value doesn't exist in a Shepherd-detectable way in CSS 2.1.  The TR of overflow-3 predates Bikeshed, and doesn't have the metadata necessary to have the definitions picked up properly.  This'll be fixed next time we publish Overflow.

> ''initial'' links to Cascade 4 ED instead of Cascade 3 CR

Ah, now *this* is a genuine error in Bikeshed.  My current strategy for "prefer TR" is to discard any ED links if there's a TR link from the same spec, but keep the ED links if there is no TR link.  The latter is based on the assumption that if the ED added a term that the TR didn't have, I should still link to it.  This doesn't take into account the possibility that there's no TR link *because we haven't created a TR spec for that level at all yet".  I created #621 for this.

> CSS Pseudo L4: ::first-letter and first formatted line don't link to TR...

::first-letter is literally not `<dfn>`'d in the TR version for some reason.

"first formatted line" isn't exported in the TR version.  It's exported in the ED.  This'll fix itself next time Pseudo is published.

> CSS Images L3 specified size doesn't link to TR

Same deal - the TR doesn't export the term, the ED does.

> large swaths of the bibliography link to the http://dev.w3.org/ EDs

That happens for specs which aren't in the biblio data.  For examples, CSS-IMAGES-3 isn't in there, only CSS3-IMAGES, since it hasn't been published since 2012 and so didn't use the new naming scheme.

Since everything is either addressed, or a data error (not Bikeshed error), or has been copied into a new more specific issue, I'm closing this.

**Comment by fantasai** [comment]
Okay, so summary:
  * values level-or-not breakage was mysteriously fixed
  * display is fixed by updating Shepherd's data
  * #621 is filed for handling L4 ED vs L3 TR issue
  * republishing Pseudo L4, Images L3, and Overflow 3 will fix the rest
and then this is all done.
