### ISSUE TITLE
Links for parameters in constructors

### ISSUE THREAD

**Issue by surma** [tabatkins/bikeshed#563]
I believe I found a bug where typed parameters in constructors are not being linked as expected. 

Here’s a reduced sample taken from [Houdini’s Typed OM](https://github.com/w3c/css-houdini-drafts/blob/master/css-typed-om/Overview.bs#L355) spec:

```
<pre class='metadata'>
Title:  CSS Typed OM Level 1
Status: DREAM
Group: houdini
ED: https://drafts.css-houdini.org/css-typed-om-1/
Shortname: css-typed-om
Level: 1
Abstract:
Editor: Shane Stephens, shanestephens@google.com
Repository: w3c/css-houdini-drafts
</pre>

<pre class=link-defaults>
spec: dom-ls; type:interface; text:Document;
spec: dom-ls; type:interface; text:Element;
spec:css-transforms-1; type:property; text:transform
</pre>

<pre class='idl'>
[Constructor(),
 Constructor(sequence&lt;TransformComponent>)]
interface TransformValue {
  iterable&lt;TransformComponent>;
};

interface TransformComponent {
};
</pre>
```

The `sequence` parameter in the constructor is not a link, while the `iterable` is.

![screenshot 2016-01-18 15 57 48](https://cloud.githubusercontent.com/assets/234957/12395905/3f548478-bdfc-11e5-9ed1-55e047221b3d.png)

**Comment by tabatkins** [comment]
That IDL, while technically grammar-conforming to the generic IDL grammar, does not actually specify a constructor!  The [Constructor] construct must have an argument list, which requires argument names.  Since it doesn't have that, it's falling into the generic "unknown extended attribute" part of the parser, which is output as plain text.  If you add an argument name, you'll see that everything gets marked up appropriately.

So this isn't actually an error in Bikeshed, it's an error in the spec. ^_^

**Comment by surma** [comment]
Well, I’ll PR it to Houdini then :D Thanks for clearing that up.
