### ISSUE TITLE
<dfn> in <table class=data> causes link target that cuts off other cells

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#584]
https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetooth-deviceinstancemap-slot links to 
<img width="801" alt="Table row cut off at top of browser window" src="https://cloud.githubusercontent.com/assets/83420/12726639/8bfa7554-c8cd-11e5-8cd4-dc84ffb63c19.png">

It'd be nicer if the `id` were on the `<td>` so it would link to 
<img width="833" alt="Complete table row" src="https://cloud.githubusercontent.com/assets/83420/12726618/7a33adea-c8cd-11e5-9fba-b641b93db229.png">

Or maybe if the dfn were top-aligned within the table:
<img width="801" alt="top-aligned table cells" src="https://cloud.githubusercontent.com/assets/83420/12726717/fa01eac8-c8cd-11e5-9043-0663fcb1598a.png">

@fantasai since this is also related to https://github.com/w3c/tr-design.

**Comment by tabatkins** [comment]
This is a general failing of hash-linking I think.  Center-aligning table headers looks better by default, even though it causes a bad alignment here.  I can't move the ID up without moving *all* the linking stuff up, and declaring that `<th>` can create a definition (currently limited to `<dfn>` and headings). And that won't help the case where you have two definitions in the same cell (top-aligning won't help in that case either, if the user is linked to the second definition).

I could maybe detect when a dfn is in a container like this, auto-gen an ID on the container, and then cause autolinks to link to the *container* instead of the definition itself.  I can probably only do this for local links, tho, and obviously it won't help if people click on the dfn's own autolink and pass that link around.

All considered, I think I can't do anything reasonable here. Anything I *can* do is hacky, and only works in simple cases.  This needs a styling solution to work right, maybe something related to snap points that helps control behavior of hash-links.
