### ISSUE TITLE
Manually specify ID for definitions in IDL blocks.

### ISSUE THREAD

**Issue by mkruisselbrink** [tabatkins/bikeshed#599]
For migrating an existing spec to bikeshed it would be nice if it was possible to manually specify the ID for a definition in an IDL block (at least for dictionary/interfaces). I know I can add an explicit `<dfn` somewhere, but especially for EventInit and Options dictionaries I don't really want to have a separate definition outside the IDL block.

At least it is also somewhat unlikely people are actually linking to these types, so probably not keeping their ID stable isn't too bad, but it would still be a nice to have feature.

**Comment by tabatkins** [comment]
The IDL autoformatter unfortunately isn't friendly with manual markup - it takes raw text as input and outputs structured HTML.

That said, there are two ways to get manual IDs in your IDL markup:

1. Mark up the entire IDL block yourself, and put `data-no-idl` on the `<pre>`. This will make the autoformatter skip the block.
2. Use the autoformatter as normal, but create `<dfn>` outside the IDL block. If they're set up correctly, the IDL block will link to them instead of defining things itself, and then you can control the ID in the normal way.

Bikeshed follows the "dom/whatwg style" for autogenning IDL IDs, so if you were already following that, the automatic IDs should match.

I don't currently have a mechanism for manually overriding the IDs otherwise, unfortunately.  That said, I could look into it!  It wouldn't be hard to add a new metadata that takes a list of [bikeshed ID, desired ID] pairs, and automatically uses the desired ID whenever it would otherwise generate the given bikeshed ID.

**Comment by mkruisselbrink** [comment]
Unfortunately the service worker spec doesn't currently use that style for IDL IDs. Fortunately though for most IDL types the serviceworker spec already has separate `<dfn>`s, so that already gets me 99% of the way to ID stability (after adding the appropriate for= attributes).

It's just options and event-init dictionaries, where it doesn't really makes sense to have a separate `<dfn>` for the dictionary that are difficult. Having a way to specify that mapping would be great for that, either in metadata or in an attribute on the `<pre>`. I could also just add manual anchors to the section or something to make sure existing links at least end up in the correct section, so having this is not absolutely required if it would be difficult.

**Comment by tabatkins** [comment]
And done. Added a new `Translate IDs` metadata, which takes a comma-separated list of Bikeshed-generated IDs and manually-specified IDs.
