### ISSUE TITLE
emitting empty paragraphs

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#646]
See `dom.html` changes in https://github.com/whatwg/dom/commit/10b6cf1ba02806220d5461a3bdb7939728b73635. Probably another bug resulting from parsing HTML using regular expressions?

**Comment by tabatkins** [comment]
No, I don't parse HTML with regexes. I *do* parse *Markdown* with them, because that's the accepted way to do Markdown.  But HTML parsing is done with html5lib.

But this is unrelated to that.  Notice that there's a `<p>` in the original, too.  It's just that the default minification strategy strips comments, so now you're left with nothing inside the `<p>`.  

I can't delete empty elements *in general* (you might have intended them!), but I *can* track which paragraphs are added by the Markdown parsing, and kill any that end up empty.  They can't be *created* that way - it can only happen if they had content during parsing, and then got their child nodes ripped out afterwards - so it should be safe to kill them.

**Comment by tabatkins** [comment]
Fixed by removing comments at Markdown-parsing time. (Ok, ok, *now* I'm actually parsing HTML with regex, a little bit. But comments are a super-simple corner of HTML, and I verified that this'll work correctly for all valid HTML comments.  (And most invalid, as long as you're not doing `<!foo>` or something.)

I manually checked this against DOM, and it fixes things up - there's actually *several* empty `<p>` elements caused by this already lying dormant in DOM, and now they're gone.

There's one error introduced - fixing that now.

**Comment by tabatkins** [comment]
Error's fixed, DOM builds just fine now.

**Comment by annevk** [comment]
I don't understand how the processing works. If you parse the HTML first, then remove the comments, then handle markdown, how can there be a problem? If you do the markdown first, you're parsing HTML with regular expressions.

I also noticed I can't put HTML comments inside an IDL block. That's another sign that HTML is not being parsed and then passed along from some kind of tree.

**Comment by tabatkins** [comment]
I parse Markdown first, then HTML.  (You can't go in reverse, you lose a ton of information.)  But aside from some *very* trivial handling of "this line starts with a block-level tag, require the contents to be indented", it's doesn't do any HTML-level parsing at all.

> I also noticed I can't put HTML comments inside an IDL block. That's another sign that HTML is not being parsed and then passed along from some kind of tree.

Can you provide more detail?  I'm not seeing any problems with comments inside of IDL.

**Comment by annevk** [comment]
Something like
```webidl
interface ParentNode {
  [SameObject] readonly attribute HTMLCollection children;

  <!--Element? querySelector(DOMString selectors);
  [NewObject] NodeList querySelectorAll(DOMString selectors);-->
};
```
broke the parser. I ended up putting the comment after the IDL block.

(I think that parsing the markdown before the HTML is a problem. ecmarkup doesn't seem to do that, instead opting for special elements where markdown is processed within. It looks a lot cleaner too than the mishmash bikeshed has.)

**Comment by tabatkins** [comment]
> Something like
> [snip]
> broke the parser.

Doesn't anymore, as far as I can tell. If it still does for any case, let me know.
