### ISSUE TITLE
dfn panels show up in "reader view"

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#656]
Test https://streams.spec.whatwg.org with the bookmarklet from https://www.readability.com/bookmarklets and you will see the problem. Also visible in Firefox's reader mode (although getting Streams to go into reader mode is not easy right now for unknown reasons I'm still working through).

EDIT: you can get reader view to trigger if you go to https://streams.spec.whatwg.org/index.html. Firefox has a heuristic that disallows "homepages" from triggering reader view.

**Comment by tabatkins** [comment]
I can't figure out how to do anything about this. ;_;  There's *extremely* minimal documentation on the various reader modes, so I can't tell what, if any, methods exist to force something to hide.  (I did find a little bit of guidelines for the Readability bookmarklet, but they appear to be DAMNABLE LIES.)  I've also got my hands tied by stupid HTML parsing; I can't use any element that auto-closes a `<p>`.

I'll go ahead and close this, because afaict it's hopeless, but I'll gladly reopen if anyone can figure out how to do it.

**Comment by domenic** [comment]
If you can move the content around a bit, and use `<aside>`s, I think that works. A simple patch didn't work because of the `<p>` problem you mention. IIRC the original dfn.js did not insert things in the same location you do (they were just children of body I think), so maybe look at that?

**Comment by tabatkins** [comment]
Yeah, original dfn.js has a single element as a child of body, and fills it in on the fly and positions it when you click.  I suppose that's not too bad; I think I avoided it because I was originally planning on doing a no-JS implementation (with the checkbox hack, yay!) but that didn't end up working out.  I'll try it, at least.

**Comment by domenic** [comment]
Here's another example of where putting it as the sibling of the `<dfn>` works out poorly: https://drafts.csswg.org/cssom/#parse-a-list-of-css-page-selectors

**Comment by tabatkins** [comment]
Yup, definitely gonna change that.

**Comment by tabatkins** [comment]
Okay, all the dfn-panels are now ASIDEs at the end of the document. I *think* they'll be omitted in reader views now.

**Comment by domenic** [comment]
Confirmed works! Rebuilt streams, and https://streams.spec.whatwg.org/index.html Firefox reader view now looks quite nice.

**Comment by tabatkins** [comment]
:+1:
