### ISSUE TITLE
Autolinking and defining extended attributes

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#677]
We are introducing the [CEReactions] extended attribute [in HTML](https://html.spec.whatwg.org/multipage/scripting.html#cereactions), and I would like all specs that use it in their IDL to have a link to its definition. You can see [examples in HTML](https://html.spec.whatwg.org/multipage/scripting.html#htmlscriptelement), where the linking is done manually.

It would also be nice to have all other extended attributes link to their definitions in Web IDL, so that you can easily figure out what "PutForwards" or "Unforgeable" mean.

This presumably would require a new linking type.

There's a bit of conflict with the [Constructor] extended attribute which currently links to the constructor definition for the interface. In reality that just shouldn't be an extended attribute...

**Comment by tabatkins** [comment]
Done.  Use the new `extended-attribute` definition type, and Bikeshedded IDL blocks will linkify automatically.

Currently, extended-attribute link failures are silent, because all of them will fail right now.  This hides misspellings, tho, so I plan to turn them back to normal after WebIDL is Bikeshedded.
