### ISSUE TITLE
Support for C++ papers

### ISSUE THREAD

**Issue by jfbastien** [tabatkins/bikeshed#713]
Opening this issue to track what would be required to support C++ standards committee papers. Will work with @tabatkins when I'm back from vacation, @jyasskin and @brycelelbach please add anything that I've missed.

Latest papers can be found here: http://open-std.org/jtc1/sc22/wg21/docs/papers/2016/
URL shortener is http://wg21.link e.g. http://wg21.link/p0193r1

I was thinking that C++ versus Web would be a document-level metada, defaulting to Web, which then affects the below properties.

# Headers

Mandatory headers:
* Type: {paper, TS, IS}
* Author[s] + Author email[s] for paper; editor + editor email for TS / IS
* Audience: one of the subgroup ([details](https://isocpp.org/std/the-committee), currently {SG1–SG14, cwg, ewg, lwg, lewg}).
* Date
* Status: {draft, published}
* Revision

Optional headers:
* Other contributors (e.g. see http://wg21.link/p0190r1)
* Previous papers
* I like linking to sources on github.com/jfbastien/papers/foo.bs, as well as wg21.link/pXXXXrX publication URL

# Index

For `bikeshed update` the C++ index / auto-linking should know about:

* Papers are currently numbered pXXXXrX when published, and dXXXXrX when drafts. Papers used to be numbered nXXXX and dXXXX (we still need to support linking to them, see wg21.link).
* wg21.link also has a handy feature linking to C++ issues with: wg21.link/cwgXXX wg21.link/ewgXXX wg21.link/lwgXXX wg21.link/lewgXXX wg21.link/fsXXX

# Miscellaneous

1. I don't think we want anything w.r.t. copyright and would drop the header entirely (see [ISO](http://www.iso.org/iso/home/policies.htm))
2. I would drop the "issue tracking" header
3. Drop the auto-generated "conformance" section
4. Drop the RFC2119 normative reference (some papers do have references that are worth keeping, e.g. http://wg21.link/p0190r1)
5. C++ code format: C++ has a bunch of `<angled-braced>`, single `&`, double `&&`. That's a PITA, would you recommend using `<pre highlight="c++"><![CDATA[`...`]]></pre>`? Or maybe being able to file-include a range? It would also be nice if the default highlight language for `<code>` and `<pre>` were C++ in C++ mode!
6. Some papers like having a diff from the spec (red for deletions, green for additions), with a swappable view with the proposed final version (i.e. apply the diff). See http://wg21.link/n4430 for example. Similar to 5. above, a file-include range diff would be cool (i.e. `diff old.cc:42-99 new.cc:45-101`).

**Comment by brycelelbach** [comment]
For Miscellaneous (1), (2), (3), (4), these can be fixed by creating custom boilerplate files for C++. I've done this part already.

**Comment by jyasskin** [comment]
A previous attempt at this, just for publications rather than papers, is at https://github.com/cplusplus/fundamentals-ts/blob/v2/main.html.

Two good example papers are http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0152r1.html and http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4430.html.

**Comment by brycelelbach** [comment]
When going through the code, I noticed that there were a couple of things that were conditional on the group, for example:

https://github.com/tabatkins/bikeshed/blob/master/bikeshed/MetadataManager.py#L280

If we can always get access to the group, then perhaps this is the way to go?

For example, for papers we'd like to have "Authors" instead of "Editors". If we knew we were in a spec with group == "isowg21" (the name I've arbitrarily picked for the C++ group), then I'd want addSpecMetadataSection to behave differently. I'm just not sure how to figure out the group when I'm in addSpecMetadataSection (e.g.  https://github.com/tabatkins/bikeshed/blob/master/bikeshed/boilerplate.py#L509).

**Comment by tabatkins** [comment]
`doc.md.group`, usually

**Comment by tabatkins** [comment]
In the gitter @jfbastien talked about better support for code blocks that might use special HTML chars like `<` and `&`. I haven't given it a good test, but `<xmp>` *should* work anywhere a `<pre>` works, and lets you use whatever chars you want without escapes (in fact, escapes *don't work*) until the `</xmp>` close tag.

**Comment by jfbastien** [comment]
This has pretty much been addressed, or forked into other issues. Closing.
