### ISSUE TITLE
The [algorithm] attribute should produce class="algorithm" in the output

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#759]
If I write:

```html
<div algorithm>
  <p><dfn>some algorithm</dfn> must do the following steps:</p>
  <ol>
    <li>step 1
      <ol><li>step 1.1</li></ol>
    </li>
  </ol>
</div>
```

I should get the same formatting I'd get if I'd used `<ol class="algorithm">`.

The [stylesheet](https://github.com/tabatkins/bikeshed/blob/754169cee44fa32e7b96abdc4a457ff9d9e50ef6/bikeshed/include/stylesheet.include#L405) already supports this with a

```css
	ol.algorithm ol:not(.algorithm),
	.algorithm > ol ol:not(.algorithm) {
```

selector.

**Comment by mikewest** [comment]
I want that style. :(

The specs I've worked on generally have followed the following pattern:

```
<h3 algorithm>Should |block| be considered an algorithm?</h3>

Given an element (|block|), the following algorithm returns
"`Algorithm`" or "`Not Algorithm`".

1.  If |block| is algorithmic enough, return "`Algorithm`".

2.  Return "`Not Algorithm.`"
```

The algorithm is implicitly ended by the next `h*` of the right level. It would be nice if we could somehow support this kind of syntax as well. I'd prefer not to add wrapper elements to the source just for styling...

**Comment by tabatkins** [comment]
@jyasskin Done. The `algorithm` attribute now causes the generation of an `algorithm` class on the element.

@mikewest That's just a little bit too magic for me; I'm not sure that I want to automatically assume that all OLs inside of an algorithm section are the algorithm steps.  That said, I just added a feature I've been planning for a while: you can manually specify the list container for markdown lists.  Like:

```
<ol class=foo>
	1. first
	2. second
</ol>
```

This will use the OL you specified, rather than generating one automatically. So you'll be able to wrap your list accordingly, and won't have an extraneous wrapper element cluttering things.  Same applies to your example, @jyasskin.

**Comment by jyasskin** [comment]
@tabatkins, any idea why the `<div algorithm>`s in https://github.com/heycam/webidl/pull/180/files#diff-ec9cfa5f3f35ec1f84feb2e59686c34dR7572 aren't causing `class="algorithm"` in https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/webidl/9392a5d2343bd42f62fecb088bddcd3bc8604b01/index.bs#es-to-open-dictionary?

@tobie
