### ISSUE TITLE
More markdown support?

### ISSUE THREAD

**Issue by jfbastien** [tabatkins/bikeshed#778]
I'm trying to understand why bikeshed supports [a subset of markdown](https://github.com/tabatkins/bikeshed/blob/master/docs/markup.md) and not other parts. I'm not sure I get a trend beyond what's currently implemented is what's there.

 Specifically, I'd like to support:
* Regular markdown links à la `[awesome](zombo.com "Anything is possible")` as well as with ID.
* Emphasis and bold with `*` and `**`.

Is that just something I can send a PR for, or do you have a moral objection?

**Comment by tabatkins** [comment]
The subset is "the parts I've bothered to support so far".  I'm happy to support more, and will gladly accept PRs.

The only things I'm willfully violating are the indent rules (and with that, a little bit of the html-block syntax), and the fucking "indented code block" syntax BECAUSE I HATE IT SO BAD.
