### ISSUE TITLE
Warn about examples without IDs

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#787]
Bikeshed seems generate example IDs based on the hash contents of the example, which means the links will be broken whenever the example changes. This is bad, but maybe a reasonable default behavior.

It would be ideal if Bikeshed encouraged us to put IDs on all of our examples to override the auto-generated ones.

**Comment by tabatkins** [comment]
I don't think I want to warn by default, as that seems too noisy to me.  Having IDs on examples at all is a nicety that is rarely done by hand anyway; having the links break when you change the content isn't great, but oh well.

That said, I'm 100% fine with adding a metadata switch to noisily complain about examples without IDs. Would that work for you, since it could just be put in the WHATWG defaults?

**Comment by domenic** [comment]
Yeah, that sounds great.

**Comment by tabatkins** [comment]
Done. Add `Complain About: missing-example-ids yes` to whatever spec you want. If @annevk's okay with it, I can add it to the WHATWG defaults, or I'll happily accept a PR to do so.

**Comment by annevk** [comment]
I'm okay with that.

**Comment by tabatkins** [comment]
Done.
