### ISSUE TITLE
Advisements are style differently depending on how they're marked-up

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#790]
The following src code:

```
<div class="advisement">
  
     This is a markdown paragraph inside of a DIV.
     
     So is this.

</div>

Advisement: This is a markdown paragraph
that is prefixed with "Advisement: ".

<p class="advisement">
     This is a standard paragraph with a class of "advisement".
</p>
```

yields the following HTML:

```html
<div class="advisement">
    <p>This is a markdown paragraph inside of a DIV.</p>
    <p>So is this.</p>
</div>

<strong class="advisement"> This is a markdown paragraph
that is prefixed with "Advisement: ".</strong> 

<p class="advisement"> This is a standard paragraph with a class of "advisement". </p>
```

_(Note the missing `<p>` tags issue already raised in #789.)_

which renders like so:

![image](https://cloud.githubusercontent.com/assets/3392/17807240/9cc0091a-6609-11e6-8c8c-37206d1f231a.png)

It would be nice if there were the same consistency between the output as is observed with notes.

**Comment by tabatkins** [comment]
This display difference appears to be intentional in the W3C stylesheet. Note the styles in the stylesheet:

```css
	.advisement {
		border-color: orange;
		border-style: none solid;
		background: #FFEECC;
	}
	strong.advisement {
		display: block;
		text-align: center;
	}
```

In other words, the bolding comes from the use of `<strong>`, and the centering is specifically associated with that.

You def don't want the bold/center in `div.advisement`, as you can put arbitrary amounts of stuff in there. Maybe for a paragraph, but then just use the `Advisement: ` syntax (or if you really want to use HTML, add the `<strong>` yourself).

**Comment by tobie** [comment]
OK, so my suggestion would be for the "Advisement: " prefix not to be wrapped up in `<strong>` for consistency with "Note: " and "Issue: ".

**Comment by tabatkins** [comment]
But that's... intended? Like, it's semanticly useful to have it be `<strong>`.

**Comment by tobie** [comment]
Agreed, but then why no longer care about those semantics when the advisement goes beyond a single paragraph?

(TBH, I don't really care either way—the inconsistency bugged me, hence reporting it—but I won't loost sleep over your wontfix. :)
