### ISSUE TITLE
Using "arguments" as identifier in a varidadic callback def mysteriously references a houdini spec.

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#803]
Given the below, arguments should be defined as a local argument, not as a reference to arguments defined in [[WORKLETS-1]].

Seems to work as intended for regular operations.

```
<pre class="metadata">
Title: Web IDL
Shortname: WebIDL
Level: 2
Status: ED
Group: webplatform
Mailing list: public-script-coord@w3.org
Mailing List Archives: https://lists.w3.org/Archives/Public/public-script-coord/
Repository: heycam/webidl
ED: https://heycam.github.io/webidl/
Abstract: Foo
Editor: Bar
</pre>

<pre class="idl">callback Function = any (any... arguments);</pre>

<pre class="idl">
interface Foo {
  any specialOperation(any... arguments);
};
</pre>
```

**Comment by jyasskin** [comment]
This'll be fixed by https://github.com/w3c/css-houdini-drafts/pull/289.

**Comment by tabatkins** [comment]
Fixed in Bikeshed by finally giving up on the idea that a non-`partial` defining instance in an IDL block would ever want to link to some other spec; now only local dfns will turn them into links, and otherwise they'll always be dfns.

Worst case, this results in slightly more collisions that have to be manually resolved with a link-defaults entry, until I get obsoleting machinery in place properly.
