### ISSUE TITLE
"Terms defined by reference" often contains two sections for each spec

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#808]
See e.g. https://heycam.github.io/webidl/#index-defined-elsewhere

**Comment by tabatkins** [comment]
Ah, interesting bug. I was relying on the fact that in Bikeshed's own dbs, spec shortnames are always lowercased; I didn't consider that anchor-block definitions could provide spec shortnames with different casing (which made different categories in the index, but all used the "canonical" casing from the biblio database).

Fixed by 95bcf2f.
