### ISSUE TITLE
`<script` confuses Bikeshed.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#814]
Bikeshed became quite confused after I added an unclosed HTML tag inside backticks. That is, with the raw text:

```
  ... the string "`<script`" ...
```

various processing things broke down. For instance, https://www.w3.org/TR/2016/WD-CSP3-20160901/#iana-registry didn't get formatted correctly, and many sections after the unclosed element are missing paragraphs and other niceties.

I've worked around it for the moment by switching to `<code>&lt;script`, so not a huge deal, but it confused me for a bit.

**Comment by tabatkins** [comment]
Right. In order to prevent various text-mangling things from running inside of scripts or styles, I preemptively look for a handful of "raw" elements (script, style, xmp, pre, anything you've manually marked as raw) and turn off processing until I see the appropriate closing tag.

I could potentially only look for those elements at the start of a line, but I chose to go for the conservative solution and recognize them anywhere on the line.

That said, though, my actual regex is `r"<({0})[ >]"` - that is, it looks for either a space or a closing angle-bracket following the word. It shouldn't match a snippet like you provided. Can you point me to some source that is causing the problem?

**Comment by tabatkins** [comment]
Ah, I see, it was specifically line 3595 that was causing it, because that has a larger prefix of a `<script>` tag, enough to trip the regex.

**Comment by tabatkins** [comment]
Yeah ok, I'm not happy that this is happening. I'll see what I can do.

**Comment by tabatkins** [comment]
Hah, this is biting me *hard* trying to port the Bikeshed documentation to Bikeshed, since I use markdown-backticks to escape a bunch of `<pre>` and `<script>` elements.

I'm just gonna only recognizing them at the start of the line, there's no reason to format your code such that a `<script>` has significant content preceding it on the line.

**Comment by tabatkins** [comment]
Okay, should hopefully be fixed, but brain no work good right now. Tests pass, at least.
