### ISSUE TITLE
<a>namespace object</a> generates the wrong Web IDL spec in references

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#837]
See https://console.spec.whatwg.org/#references. Web IDL 1 doesn't even define namespace objects. And that's the URL for Web IDL, not Web IDL 1.

**Comment by tabatkins** [comment]
Hm, this is how the biblio data sees things:

```
-
a:webidl
WebIDL
webidl-1
-
d:webidl-1
WebIDL-1
15 September 2016
PR
WebIDL Level 1
https://www.w3.org/TR/WebIDL-1/
https://heycam.github.io/webidl/


Cameron McCormack
Boris Zbarsky
```

It aliases `webidl` to `webidl-1`, and then you end up getting the "current" links, which is to the correct spec.

The w3.org url is the most correct, recent "snapshot" url, too, so I'm not sure what's wrong with this?

**Comment by domenic** [comment]
What's wrong is that in https://console.spec.whatwg.org/#references it says "Web IDL Level 1" and "PR" instead of "Web IDL" and "ED".

**Comment by tabatkins** [comment]
The most recent snapshot level for the spec is indeed PR.  And calling the spec as a whole "level 1" is fine imo - what's wrong with it?

Note that WebIDL *is* still officially a W3C spec.

**Comment by domenic** [comment]
Right, but we're not linking to Web IDL level 1, the spec located at https://www.w3.org/TR/2016/PR-WebIDL-1-20160915/ whose level is PR. We're linking to Web IDL, the spec located at https://heycam.github.io/webidl/ whose level is ED.

**Comment by tabatkins** [comment]
Yes, I'm aware of all the issues around WebIDL snapshotting. But the facts are still that WebIDL is a W3C spec, it has snapshot versions, the latest such snapshot is a PR, and it has links to both the snapshot and the current version. And, since WHATWG has a default policy of linking to the current versions, you see only the current versions in your biblio anyway.  

The only problem seems to be that you would like the reference to be unlevelled (it's a W3C spec, so the name is determined by the W3C, and they say it's called "Web IDL Level 1" in their biblio data), and that you dislike the fact that "PR" is mentioned in the biblio (despite it being a true fact that its most recent snapshot is a PR).  Since they're both correct as written, and working around it would be some sort of terrible hack, I'm not super excited about trying to "fix" anything there.

**Comment by domenic** [comment]
From my perspective, a spec is a series of { name, status, url } tuples. We'd like to reference a specific { name = "Web IDL", status = "ED", url = "https://heycam.github.io/webidl/" } tuple.

However, what we've ended up with is a hybrid. It's talking about a spec with name = "Web IDL Level 1", status = "PR", but with url = "https://heycam.github.io/webidl/". There is no such spec! The biblio entry is internally inconsistent with itself! The URL doesn't match the name and status fields! In other words, "you see only the current versions in your biblio anyway" is not true---we're seeing a hybrid of the old snapshot version, and the current version!

Reading between the lines of your replies, it seems like Bikeshed has some kind of policy that whenever you reference a spec, it wants to put information on whatever the latest status of that spec is in the biblio entry. But I argue this doesn't make sense, and is actively misleading for readers, when the URL it gives is in fact for a different-status spec.

**Comment by tabatkins** [comment]
Hmm, you're right that, if I'm just using the "current" URL, talking about the snapshot's status doesn't matter (and is kinda confusing). I'll fix that.

**Comment by tabatkins** [comment]
Done. If you prefer current URLs (and got one), it omits the date and status of the snapshot.

**Comment by domenic** [comment]
Thank you!
