### ISSUE TITLE
Option --include for 'bikeshed source'?

### ISSUE THREAD

**Issue by kba** [tabatkins/bikeshed#846]
Using `pre.include` blocks to include content is really helpful to concentrate on structure and text and keep the tables and definition lists somewhere else.

This works very well locally but it's an irreversible decision: Once you start using includes, you won't be able to use the web service for building or check in the full spec source code for easy reading.

Therefore I wanted to know whether an option to include files into the **spec source** would be feasible, how much effort it would be, i.e. are there any inclusion logic problems to consider? Or is it just a bad idea and one should stick to either using or not using includes?

**Comment by tabatkins** [comment]
I don't fully understand. Wouldn't this just write the includes into your source, so you're not using includes at all anymore?

**Comment by kba** [comment]
Right. The output of `bikeshed source --include input.bs output.bs` would be `input.bs` with all `<pre class=include>` replaced with their contents. Probably a terrible idea to do this in-place by accident...

**Comment by tabatkins** [comment]
Still kinda curious about the use-case for this before I close it. ^_^

So the idea is, I guess, that you've started authoring a spec using includes for organization, but your fear is that at some point you might want to switch back to using a single source file, right?

Dealing with the web service doesn't appear to be a use-case here, since you would have to have a local installation to *perform* the flattening anyway, and then why are you using the web service to do the actual processing?

I suppose if you ever run into this use-case, just let me know and I'll figure something out. ^_^
