### ISSUE TITLE
Add some mechanism for Bikeshed to actually set link defaults (overriding local dfns)

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#853]
As discussed in https://github.com/w3c/ServiceWorker/pull/995, there are many scenarios where the generic definition of a term is in another spec (often HTML), and all instances of `<a>origin</a>` in a spec should refer to HTML's definition---even if the spec defines something like `a foo's <dfn for="foo">origin</dfn>`, and once or twice talks about the `<a for="foo">origin</a> of a foo`.

It would be great if there were a way to set the link defaults so that this was possible. Since link-defaults does not set the defaults in this way, maybe we need some other thing, like link-actually-defaults?

**Comment by tabatkins** [comment]
Hmm. So, let's enumerate the cases:

1. The generic (`for`-less) version of a term is in a foreign spec, and you have a local (or anchor-block) definition of a `for`'d version of the term.  A simple `<a>term</a>` will then silently choose the local/anchor-block version.

2. Within your spec, you define multiple variants of a single term with different `for` values. One of them might be `for`-less; I don't think this affects the scenario. You want `<a>term</a>` to link to a particular one of these; right now it complains about an ambiguity, but requires you to solve it by annotating every autolink, rather than using a link-default.

Is there anything else?

The first one is the most important one, as it causes silent spec corruption. Plus, seemingly harmless edits to the spec, like adding a new `<dfn>`, can suddenly break previously-working autolinks.

So I think I can fix that first part automagically.  If you do a `for`-less autolink that matches a local `for`'d definition, but a `for`-less version exists in a foreign spec, I can automatically warn about that, in case it's unintentional.  I'd then add another "Ignore FOO" metadata variant to silence the warning when it's spurious.

---

Now, if the warning *isn't* spurious, you've got to fix things. Right now that means fixing each individual autolink, to add a `for=/`.

So the question now is, is it *always* a matter of "I want an omitted `for` on the autolink to match the `<dfn>` without a `for` (that is, equivalent to `for=/`)"? Or do you sometimes want an actual honest-to-god link-default that applies to local links too, letting you say `<a>term</a>` and having it autolink to a foreign `<dfn for=foo>term</dfn>`, even tho there's a local `<dfn for=bar>term</dfn>`?

The reason I've been hesitant to do that in the past is that Bikeshed's current design intentionally makes it easy to refer to local links without having to specify their `for` value if it's unambiguous, and having a "real" link-defaults makes it, I think, too easy to accidentally type out an `<a>term</a>` link, expecting it to link to the local term, and have it accidentally link to something else.  (Especially if there are multiple editors, or if it's been a while since you last editted the spec.)

The same kinda applies to the "assume no `for` means `for=/`", but somewhat less so; the ergonomics are better, at least.  Maybe I should instead just have a flag letting you turn that on globally, so *all* autolinks have the "no `for` means `for=/`" behavior if you want?  Would that work for you?  That would reduce the usefulness of link-defaults in general (it would only let you select between multiple specs defining the exact same term/for), but it appears that it would match your mental model better?

**Comment by domenic** [comment]
> So the question now is, is it always a matter of "I want an omitted for on the autolink to match the `<dfn>` without a for (that is, equivalent to for=/)"? Or do you sometimes want an actual honest-to-god link-default that applies to local links too, letting you say `<a>term</a>` and having it autolink to a foreign `<dfn for=foo>term</dfn>`, even tho there's a local `<dfn for=bar>term</dfn>`?

That's a good question. All the cases I've come across want to link to the for=/. But that's probably because I'm going around trying to fix HTML/Bikeshed spec integration, and most of those cases are when HTML defines the for=/ version.

> having a "real" link-defaults makes it, I think, too easy to accidentally type out an `<a>term</a>` link, expecting it to link to the local term, and have it accidentally link to something else. 

I can see the concern, but in the end I think I'd be OK saying that you brought it on yourself. You told it to set those as the defaults, after all; if you didn't want to do that, don't set the other spec to be the default!

> Maybe I should instead just have a flag letting you turn that on globally, so all autolinks have the "no for means for=/" behavior if you want? Would that work for you? That would reduce the usefulness of link-defaults in general (it would only let you select between multiple specs defining the exact same term/for), but it appears that it would match your mental model better?

That would work! And then we could turn it on for default in WHATWG, and maybe given some other prominent people who seem to have this model, in webappssec and webbluetoothcg?

To clarify, with this flag on, I think this would mean that link-defaults becomes actually-link-defaults in general? Because now everything has a `for` value, so nothing is "local" and thus nothing bypasses the link-defaults layer? That would be amazing.

**Comment by tabatkins** [comment]
> To clarify, with this flag on, I think this would mean that link-defaults becomes actually-link-defaults in general? Because now everything has a for value, so nothing is "local" and thus nothing bypasses the link-defaults layer? That would be amazing.

Not quite, but the effect would end up being very similar.  Since *every* link is now treated as having a `for` value, the only thing link-defaults can do is let you decide which spec to use when multiple specs define exactly the same term/type/for.  If you define a particular term/type/for locally, and want to link to the one in a different spec, link-defaults won't help, but wanting to use link-defaults there would be *crazy* (to link to your local one you'd have to specify `status=local` on your autolink!).

**Comment by tabatkins** [comment]
Okay, the first bit (detecting when you might have meant to link to a cross-spec for-less definition but accidentally hit a for-full local definition) is landed now. (And it triggered on two definitions in the docs!)

**Comment by tabatkins** [comment]
And the second bit is done now - add `Assume Explicit For: yes` to your metadata to make `<a>term</a>` equivalent to `<a for=/>term</a>`.
