### ISSUE TITLE
Do section numbers have a period after them or not?

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#856]
I noticed that in e.g. http://dom.spec.whatwg.org/, the TOC reads "1 Conformance" whereas the section header reads "1. Conformance".

Is this intentional or accidental? I'm fine with intentional although I'd be curious what the reasoning is.

I ask because I was hoping to align HTML with a similar style but its preprocessor doesn't distinguish between in-TOC and out-of-TOC without some extra work. So before putting in that extra work I wanted to see whether maybe this was just an accident.

**Comment by tabatkins** [comment]
Semi-intentional style choice.  In the default Bikeshed styling, the TOC numbers are physically separated from the heading text, and period-less looks better.  In the actual headings, tho, the period helps visually separate the heading number from the heading text.

WHATWG's TOC styling doesn't work quite the same way, but it's still very visually obvious what's a number and what is the heading, so it's ok for them to not have a period either.
