### ISSUE TITLE
"Assume Explicit For: yes" not working quite right?

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#862]
The latest at https://github.com/w3c/ServiceWorker/pull/995/files is still giving me trouble. Although many of the errors are legitimate (they need an explicit for=""), some don't make sense to me. In particular it seems to be erroring about explicit for for anything defined in IDL blocks. For example, I get the error

```
[1;33mLINK ERROR:[0m No 'idl-name' refs found for 'FetchEventInit' with for='/'.
```

despite the definition being a perfectly ordinary 

```html
    <pre class="idl" id="fetch-event-init-dictionary">
      dictionary FetchEventInit : ExtendableEventInit {
        required Request request;
        DOMString clientId = "";
        DOMString reservedClientId = "";
        DOMString targetClientId = "";
        boolean isReload = false;
      };
    </pre>
```

**Comment by tabatkins** [comment]
Nope, it's working just fine; what you're seeing is markup errors that were previously masked.  In particular, a lot of the `<section>`s have a `dfn-for` attribute, which applies to *all* the `<dfn>`s contained within, including IDL.  Since a bunch of stuff is now incorrectly "for" something, it's not matching the `for=/` implied by the autolink.  Fix those and you'll be fine.

(In the meantime, I should note which definition types should *not* have a `for`, and flag it as a fatal error if they gain one, to help catch markup errors like this.)
