### ISSUE TITLE
Don't give argument names semantic meaning

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#866]
This came up before and now it's blocking conversion of XMLHttpRequest in https://github.com/whatwg/xhr/pull/97.

Rather than giving weight to types of arguments, as IDL does, Bikeshed gives weight to the argument names.

This leads to specifications defining overloads as multiple operations. However, if they were implemented in JavaScript it would likely be a single method with a single description. (I think there was also another problem, but it escapes me at the moment. @domenic?)

I think we should approach this differently.

**Comment by tabatkins** [comment]
Woah, don't lay overloads at Bikeshed's feet.  That's been a quality of WebIDL for a long time; if anything, Bikeshed makes it *more annoying* to do (as you discovered), which is the opposite of encouragement.

Bikeshed's linking process for methods is based on the way that people actually refer to methods in prose. Nobody says "the open(DOMString) method" or whatever, they use the actual argument name (if they give arguments at all).  Most commonly you don't need to distinguish based on arguments anyway, so you can omit the arguments entirely.  In the rare cases that you do, people usually give different argument names; your particular case is just one where you didn't do that.

If you want to define a single method with wider types, rather than overloads with narrower types, feel free to do so. It makes Bikeshed's job easier, and yours too (since you can just say `{{method()}}`, without args at all).  Or, since argument names don't have semantic meaning to you, just rename one of the non-optional args in one of the overloads.  Either solution works.

**Comment by annevk** [comment]
The names themselves don't mean anything, but using different names for what is the same argument is what is wrong. That way you cannot define it as a single method.

**Comment by tabatkins** [comment]
Then just define it as a single method. Your problem is that your IDL defines it as two methods, then you're trying to define it as one method in the prose.  Be self-consistent, one way or the other, and it'll work a lot better.

**Comment by annevk** [comment]
There's no way to combine the two lines of IDL into one.

**Comment by tabatkins** [comment]
Then be consistent the other way, and write out two `<dfn>`s? You can put them in the same spot in your prose, just noted as two signatures of the singular method you're defining.  Or you can manually write out the `lt` needed to get the one `<dfn>` to trigger for both of them (it's just the concatenation of the `lt`s that get autogenerated for your WebIDL.

Either way, tho, if you're stuck with having two WebIDL methods, then their signatures need to be distinguishable, and that means at least one of their shared required arguments has to have a different name. This is as easy as renaming one of the arguments `blobValue`.

**Comment by annevk** [comment]
Right, but I think that's wrong. There's only a single method we're defining here, it's just that to trigger some of the desired IDL semantics it needs to go on two lines.

And if I use a single `<dfn>` but the argument name in the IDL is off, that wouldn't make much sense.

**Comment by tabatkins** [comment]
Unfortunately for this case, Bikeshed's linking mechanics for WebIDL are weighted toward actually representing WebIDL, not representing an idealized representation of the underlying operations. It would be *way* more confusing and difficult otherwise.

**Comment by annevk** [comment]
But it's not! IDL does not do overloads based on argument names.

**Comment by tabatkins** [comment]
Right, but everyone, when they refer to functions with their args, uses the arg names.  Nobody writes "the `append(USVString, USVString)` method", they say "the `append(name, value)` method".  We're not executing a method, we're referring to it by name to link to it.

**Comment by annevk** [comment]
Yeah, and there's only one name, which is `append()`. Maybe there should be some kind of opt-in to get them distinguished, since I'd actually argue that any specification that uses that is probably wrong. We mostly try to get rid of overloaded methods too.

**Comment by annevk** [comment]
That `FormData` uses overloading is somewhat unfortunate and poor legacy design that we tried to get rid of, but unfortunately could not.

**Comment by annevk** [comment]
This also creates a problem for the `open()` method.

**Comment by annevk** [comment]
This is now blocking moving XMLHttpRequest to Bikeshed.

**Comment by tabatkins** [comment]
Nothing's blocked, I've given you several options to resolve this:

1. Rename at least one of the required args on one of the overloads. (And either put in two `<dfn>`s, or set up your one `<dfn>` with the required `lt` for it to substitute for both.)

2. Rewrite your IDL to have only one method, and add some prose to your algorithm to do whatever additional error-handling is lost as a result. (I guess throwing an error if the second argument is a USVString and the user passed a third argument?)

Your problem is that you have an overloaded IDL method (thus, *two* methods, as far as Bikeshed is concerned), and are attempting to pair that with a single method description (because it's one method in JS). The IDL block isn't describing a JS method, tho, it's describing an IDL method. Be consistent in referring to it, and the problem goes away.

You can even be explicit about the fact that this is just two overloads of the same method:

> The `append(name, value)` or `append(name, blobValue, filename)` method, when invoked, ...

This is a quick and simple way to resolve your problem. What's not quick or simple is waiting for me to figure out WTF I would have to do to make IDL overloads not count as separate methods, in a way that actually makes sense to people, particularly when they *do* want to describe the overloads' behaviors separately.

**Comment by annevk** [comment]
I wish you had not closed this. I don't think it's resolved.

Which specifications describe overloaded methods as distinct methods? I'd argue they are wrong.

**Comment by tabatkins** [comment]
> Which specifications describe overloaded methods as distinct methods? I'd argue they are wrong.

Why would it be wrong?  You have two distinct argument patterns; if their behavior is sufficiently distinct, it's reasonable to write out their algorithms separately.  It's not *good* API design to have the same method work that differently, but the web is full of bad API design. ^_^

The point still stands - WebIDL denotes the overloads as two distinct things, and it would be a lot of work to try and untangle that to make only one of them an anchor while still making all the argument patterns linkable and the whole thing understandable, and that still depends on me doing something *unknown* to handle the case where two overloads have the exact same argument pattern, *which is the exact situation you're running into*.

Just. Rename. The. Argument. If they're not semantic, the name doesn't matter, so you can freely change it; if they are semantic, then distinct names are actually significant for linking/recognizing purposes, so you should change it.

**Comment by annevk** [comment]
It's not just renaming the argument. If I renamed the argument I'd also have to have multiple entry points, change the algorithms, etc. And it's not clear to me why purely for transitioning to Bikeshed such gratuitous changes are justified.

I filed https://github.com/heycam/webidl/issues/241 to discuss the IDL issue underneath this.

**Comment by tabatkins** [comment]
> It's not just renaming the argument. If I renamed the argument I'd also have to have multiple entry points, change the algorithms, etc.

You wouldn't have to do any of this. You just change the opening sentence of the append() algorithm to:

> The `append(name, value)` / `append(name, blobValue, filename)` method, when invoked, must run these steps:

Then just adjust the place where you refer to `value` to say `blobValue` too, or put in an earlier step that collapses the two argument names to a single `value` var so you can operate on them symmetrically.

Similar minor adjustments work for the `open()` method.

**Comment by domenic** [comment]
It's a real shame that Bikeshed is constraining us from writing specs that other preprocessing tools are able to handle fine, and that is fine to do in Web IDL, by constraining the argument names to not collide between different overloads. I'd ask that Bikeshed introduce the ability to distinguish by type for cases such as these, since that's what Web IDL does and expects. It's very unnatural to have to pick different argument names in overloads, as a spec writer. (Or as an implementer; check your nearest C++ files in codesearch for evidence).

**Comment by annevk** [comment]
@tabatkins that is what I meant. I agree with Domenic that this is unnatural and unnecessarily constraining.

**Comment by tabatkins** [comment]
This "constraint" is because referring to functions by argument name is how people *actually want to refer to functions*.  Names provide useful human-level semantics for arguments, even if they're not strictly meaningful at the IDL-level.  C++ overloads allow the same argnames *because you never point to a function definition itself in C++*, you just call it with values; the analogy isn't meaningful, since the whole point of Bikeshed in this case *is* to refer to function definitions.

Like, what, if you define two overloads with the same argnames, you just *can't* refer to them by argname anymore? (At least, not without getting an ambiguous-link error and having it arbitrarily choose one or the other.) That's pretty crappy.  Adding an overload (uh, *anywhere* in the Bikeshed ecosystem) means that your previously-useful `append(name, value)` links are now impossible to use, with no chance of disambiguation - you have to instead change them to `append(DOMString, DOMString)`.

Additionally, IDs are genned based on the argname signature; if the presence of a same-argname overload means the argname signatures are no longer valid, it means I'd have to change the ID generation in some way, while being careful not to alter existing IDs.

---

My overall point is that the system is WAI right now. Changing it would be a ton of careful, fiddly, confusing-for-most-end-users work, and the "benefit" is that in a tiny handful of cases, some people can use their desired argument names, *despite the entire opening argument being that argument names aren't meaningful*.  You're not actually blocked on anything whatsoever, except your own refusal to not change a "non-semantic" argument name.  Change the argument name, and live the rest of your life content.

**Comment by annevk** [comment]
Again, I don't think most end users define overloads (nor should they). And changing the argument names changes the IDL which implementers copy-and-paste and base their C++ on. I don't want to change it just for Bikeshed and I want IDL to match what would make most sense for implementers. And that requires each overloaded argument to have the same name.
