### ISSUE TITLE
Add line information to warnings/errors

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#868]
It would be useful for debugging if errors had a line indicating where they are found.

**Comment by tabatkins** [comment]
Already doable with the `-l` flag <https://tabatkins.github.io/bikeshed/#cli-spec>.

Note the caveats tho - because LXML is terrible and doesn't consistently preserve line numbers, I had to achieve this with hacks - it does a scan of the pre-parsed text and inserts line-number attributes whenever it thinks it's found a start tag. Because this can misfire on things that just *look* like tags, but will eventually become raw text, the `-l` flag disables actually producing an output spec. In other words, it's just for debugging purposes; you can't just run Bikeshed with this flag constantly (or else I'd have just turned it on for everything).

**Comment by annevk** [comment]
This flag does not work in combination with -f, making it not super useful when converting XMLHttpRequest.

**Comment by tabatkins** [comment]
Of course it does. I'll bet you're putting the flag in the wrong place, tho - `-f` is a global Bikeshed flag, while `-l` is a flag for the `spec` command, so the command should look like `bikeshed -f spec -l`.

**Comment by mkruisselbrink** [comment]
I can't seem to get the -l flag to do anything useful for me. Bikeshed currently is giving me some link errors (for bikeshed versions after 237216488a585c6f0fbfeb6dc67a26c10fd1d88d, bikeshed versions before e0037f327e6a0d78c4d3948c1bb7486cf60235e4 don't give the error), but even with `bikeshed spec -l` I'm not getting any kind of line information or any other context to tell me where this error would be...

**Comment by tabatkins** [comment]
Yeah, not every error has an element to associate it with, and elements generated by Bikeshed don't get line numbers. :(  It many cases this is reasonable, but in places where I'm, for example, converting autolinking shorthands into elements, it's a lot more annoying and less reasonable.

I'll open an issue to handle that latter case, at least.
