### ISSUE TITLE
Automatically generate diffs

### ISSUE THREAD

**Issue by mgaunard** [tabatkins/bikeshed#871]
When replacing part of an old specification with new wording, it would be nice to write the old version and the new version side by side, and let bikeshed generate the diff as appropriate.

**Comment by tabatkins** [comment]
The problem here is that automatic diffing of *text lines* is already quite difficult to do well, and it's not uncommon to just suffer thru a non-optimal diff because it's good enough.  Automatic diffing of *tree structures* is way more difficult; just like with text lines, you can usually get it reasonably correct in small doses, but you'll often get it wrong.

(I just did an HTML diff of a spec on Tuesday to help generate the changes list, and experienced exactly this - it did a reasonable job in some parts, but in others it was very bad, interpreting an addition as a series of intermingled changes.)

HTML Diffing is, at least currently, something that really needs to be done by a human.

**Comment by jfbastien** [comment]
When @mgaunard and I chatted in meat-space one thing that came up was auto-generating diffs based on *source code*. So you'd say "here's `foo.old.cpp` and `foo.new.cpp`, create a diff for these between lines `[X.old, Y.old)` and `[Y.new, Y.new)`".

That could be done directly with Python's `difflib` plus some post-processing. The neat thing is that you don't need to HTML-markup the code manually (because `<xmp>` doesn't mesh with `<ins>` / `<del>`).
