### ISSUE TITLE
Async Method With Promise in IDL Processing

### ISSUE THREAD

**Issue by lisa0314** [tabatkins/bikeshed#878]
When defining an async method using promise in web idl design, I encounter something really confusing.
For example, I have a IDL definition in the source file named index.bs:

```
Interface A {
promise<Config> getConfig();
}
```

And after the pre-process, the corresponding code in output file named index.html look like this:

```
Interface A{
   promise getConfig();
}
```
  
However, I think the format in the output file is against the standard web idl definition for **Promise**. Maybe I misunderstand the usage of the tool ?

**Comment by tabatkins** [comment]
Look more closely at your html - you'll notice that you're actually (accidentally) writing a `<Config>` HTML element in the middle of your IDL. ^_^  (Same thing happens if you use a `sequence<Foo>` and aren't careful.)

Two ways around this, use whichever you like better:

1. Use an `<xmp class=idl>` instead. This *turns off* all HTML markup inside the block, so using `<` characters is safe again. `<xmp>` is a deprecated HTML element, but Bikeshed will automatically switch it back to a `<pre>` in the output document.

2. Escape your `<` characters as `&lt;`.

**Comment by lisa0314** [comment]
@tabatkins Thanks(●'◡'●)
