### ISSUE TITLE
Shepherd: "sequence" not indexed

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#882]
In https://github.com/heycam/webidl/commit/d99fdf9e6ac6e0682703d8a790569c901701a41f I export sequence and record. Record succeeded, but sequence did not. Is that because of the angle brackets in `lt="sequence|sequence<T>"`?

This blocks https://github.com/whatwg/fetch/pull/418.

**Comment by tabatkins** [comment]
Hmm, that shouldn't cause any problem. Plenty of CSS non-terminals use angle brackets, after all. Looking into it.

**Comment by tabatkins** [comment]
@plinss Yo, I can't figure this out, as things seem to work correctly locally.  <https://heycam.github.io/webidl/#idl-sequence> defines `sequence` and `sequence<T>` correctly, but it's not showing up in the db.

**Comment by plinss** [comment]
The anchor is in the DB, but just not as a definition, because there's no &lt;dfn> tag there, just a heading (though it has a data-dfn-type attribute...)

**Comment by plinss** [comment]
sequence&lt;T> is defined by https://heycam.github.io/webidl/#sequence-type and that seems to be in the DB ok (though maybe not with the linking text you're expecting because that got placed on the heading before...)

**Comment by tabatkins** [comment]
@plinss Headings have been able to define definitions for quite a while. We discussed this and you updated Shepherd accordingly months ago.

**Comment by plinss** [comment]
Right you are, forgot about that, sorry. 

Looking deeper I found the problem: the heading has the linking text of "sequence|sequence&lt;T>", but then there's the other &lt;dfn> within that section that also has the linking text of "sequence&lt;T>" (form its text content). There's code that detects the duplicated linking text and when it conflicts with a heading dfn, the conflicting linking text gets deleted from the heading and the heading gets demoted from dfn to a regular heading.

Possible solutions are:
1) resolve the conflict by removing the sequence&lt;T> linking text in the heading (or stop using the heading as a dfn and move the "sequence" linking text to the dfn)
2) resolve the conflict by removing the second dfn
3) I modify the duplicated linking text code to only demote the heading when all of its linking texts are deleted (currently any deletion triggers the demotion)

I'm not entirely sure if option 3 is safe, but it smells reasonable to me on the surface (then again, maybe not). The issue is that you _do_ have two dfns in the same section trying to define the same thing, so do you really want to different dfns with different linking texts?

I suppose another option would be for the duplicated linking text code to continue to demote the heading, but move any leftover linking texts to the sub-dfn. This would move all the links to the non-heading dfn.

**Comment by annevk** [comment]
I do think you are correct that IDL is somewhat confusing how it handles these things. I can look into a solution there, though it's somewhat surprising to me how Shepherd works given that Bikeshed does not complain. Does Shepherd not consider `lt` attributes authoritative?

**Comment by tabatkins** [comment]
@plinss It's a bug in Shepherd, then, that it's paying any attention whatsoever to the text content of the DFN, as the element has an `lt` defining its linking text instead.

The DFN should only be defining the term "sequence type", while the heading defines the terms "sequence" and "sequence<T>", per the Bikeshed definition contract.

**Comment by plinss** [comment]
Digging through it more I agree, there are a few cases where I do append the text content of the dfn into the linking text but those are all in legacy spec support (mostly for older SVG specs). Will have a fix momentarily.

**Comment by tabatkins** [comment]
Danke!

**Comment by plinss** [comment]
Fixed and the DB is updated.

**Comment by annevk** [comment]
Thanks!
