### ISSUE TITLE
Prevent auto-paragraph insertion on first line of <dt> elements when using markdown ":" syntax.

### ISSUE THREAD

**Issue by travisleithead** [tabatkins/bikeshed#914]
This change fixes an inconsistency between hand-authored html docs and the html generated by bikeshed when using markdown shorthands. For example, consider the following:
```html
   <ul>
     <li>my list item</li>
     <li>another list item</li>
  </ul>
```
The above passes through Bikeshed as you would expect. Now consider a spec authored as follows:
```md
   * my list item
   * another list item
``` 
This causes bikeshed to generate the following:
```html
   <ul>
     <li data-md>
       <p>my list item</p>
     </li>
     <li data-md>
       <p>another list item</p>
     </li>
   </ul>
```
(Note the extra paragraphs.)

This same behavior applies to the contents of `<li>`, `<dt>` and `<dd>` elements.

So... I didn't care until I noticed how the HTML5.2 spec was rendering when I used:
```md
<dl class="switch">
  : dt item
  :: dd item
</dl>
```
See (https://w3c.github.io/html/dom.html#dom-document-title -- the title-setter algorithm switch statement)

The W3C stylesheet for dt (`dl.switch > dt`) generates a cute little right-arrow character to represent the "switch" item. This generated content is applied to the `<dt>` element. When the paragraph is inserted by Bikeshed, it adds margin to the contained text relative to the dt's container. Thus, it makes it look like the little "switch" character is floating directly above and left-aligned to dt's contents. Yuck. 

The workaround--don't use `:` and `::` syntax... Until now.

We should change Bikeshed so that it doesn't auto-generate paragraph tags when there is only textual content in the `<li>`, `<dt>`, or `<dd>` elements. This matches typical author expectations, and happens to also fix the HTML spec's rendering (without changing stylesheet rules).

When there is more than one "paragraph" in an `<li>`, `<dt>`, or `<dd>` element, then a paragraph should be inserted for the second paragraph, as expected.

**Comment by domenic** [comment]
-1. The WHATWG stylesheets and specs depend on such p elements, because very often we have multiple ps per li. I also disagree that p-less matches author expectations and hand-authored HTML; all of the specs I've worked on do not use bare lis except in specific circumstances. This would be very disruptive.

**Comment by travisleithead** [comment]
PR #915 has the proposed change. I rand the HTML 5.2 spec through Bikeshed with this change and noted that the rendering issue was fixed.

**Comment by travisleithead** [comment]
Perhaps this should be scoped to just `<dt>`? I looked at WHATWG html, and the "switch" class applies the generated content to naked `<dt>`. I suppose adding a paragraph there would equally mess-up the WHATWG documents...

**Comment by domenic** [comment]
Agreed dt should not get paragraphs. dd probably should still.

**Comment by travisleithead** [comment]
SGTM. I'll update the PR.

**Comment by tabatkins** [comment]
Ideally I'll eventually follow the actual Commonmark spec and differentiate between "loose" and "tight" lists - if you have empty lines between your list entries you get `<p>` around the contents, otherwise you don't - but that requires more complex logic than I'm willing to dive into right now.  (And, for legacy and styling purposes, I'd want a metadata option to opt into always-p.)

But for now, I'll gladly accept a PR preventing `<dt>` from generating `<p>`. No need for that; it's an extreme minority of cases that would actually want that.  It's basically an accident that they get any in the first place.

**Comment by travisleithead** [comment]
PR updated with this feedback incorporated.

**Comment by tabatkins** [comment]
(Whoops, dealt with this issue a while ago, but didn't close it.)
