### ISSUE TITLE
UD vs DREAM status

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#917]
Using `Status: UD` and the correct working group gets you the correct boilerplate for that group. In the case of CSS for instance, you get the addition to the Introduction that says what CSS is, and CSS specific additions to the conformance section.

However, using `Group: csswg`, even with `Status: UD` also seems to hardcode reporting issue to the csswg's github (cannot replace it using `Repository` or `Issue Tracking`), which isn't right for an Unofficial Draft, especially when you host  it elsewhere. It also set the copyright line to 

> Copyright © 2017 W3C® (MIT, ERCIM, Keio, Beihang). W3C liability, trademark and document use rules apply. 

which doesn't seem right of an Unofficial draft either.

Using `Group: csswg` and `Status: DREAM` together has the same problems, plus broken styling.

If you use `Status: DREAM` without a group, these problems go away, but you don't get the relevant boilerplate.

Fixing a few of the following things would help:

* [ ] fixing the combination of `Group: ***` and `Status: DREAM` to use the same stylesheet as no group and `Status: DREAM`, rather than a non existing `https://www.w3.org/StyleSheets/TR/2016/W3C-DREAM`
* [x] Changing the copyright line for `Group: ****` + `Status: DREAM` (and maybe also for `Status: UD`) to what you get when you're not in a group
* [ ] Don't point to the groups's default Issue tracker when `Status` is `DREAM` or `UD`, or alternatively, allow it to be overridden by an explicit `Repository`.

**Comment by tabatkins** [comment]
The copyright is easy to do right now - just submit a `csswg/copyright-DREAM.include` file that's identical to the default one.  Feel free to PR me for that.

I agree with the other two as well, and will work on them.

**Comment by tabatkins** [comment]
Okay, so I'm looking into this more.  Specifically, the third one is caused by the CSSWG's own defaults:

```json
{
	"Repository": "w3c/csswg-drafts",
	"!Issue Tracking": "<a href='https://github.com/w3c/csswg-drafts/labels/[VSHORTNAME]'>GitHub Issues</a>",
	"Boilerplate": "repository-issue-tracking no",
	"Infer CSS Dfns": "yes"
}
```

So you *can* override the `Repository` key, it just doesn't matter, because the group turns off the generation of the issue tracking from the repository metadata. You can turn that back on if you like - just repeat that `Boilerplate` line with a `yes` (or other boolish true).

But you can't remove the special Issue Tracking line - custom metadata is purely additive.

Similarly, the first issue isn't caused by Bikeshed, it's a result of the CSSWG's own boilerplate, which links to the W3C stylesheet.  Bikeshed does autogen this URL, and will happily do so for statuses that don't exist in the W3C, but ultimately it's a matter of the boilerplate using a particular `<link>` rather than including an inline stylesheet.

-----

Really, you just shouldn't fight against this. Use no `Group` at all if you're not working in the CSSWG repo; the CSSWG boilerplate and defaults are tuned for the WG repo.  (The boilerplate also links to default.css, for example, tho the effects of that are pretty minimal.)
