### ISSUE TITLE
Should add `bikeshed serve` to get a server running

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#921]
From @frivoal:

> A `bikeshed serve` command that does like `bikeshed watch` and sets up an http server on 127.0.0.1:8000 would make irrelevant thought. wink wink nudge nudge.

This should be pretty trivial, given SimpleHTTPServer.  Just need to add a flag to control port, I guess.

**Comment by frivoal** [comment]
Don't forget to serve other files in the same directory or sub-directories, otherwise lots of spec will break due to missing images.

**Comment by tabatkins** [comment]
Okay, added. Try it out and let me know if it works for your Android use-case.

Note that the CSSWG references a stylesheet in the parent directory, which is *not* served by default (since it's above the root), so to deal with those specs you have to issue the command from the repo root, and specifically go to `localhost/css-foo/Overview.html`.

**Comment by frivoal** [comment]
Great, it works, thanks.

If you want to go from great to freaking awesome, here's a list of incremental improvements you could make (some are likely trivial, some not). These are in no particular order, and are usefull independently, but many reinforce each other so the more the merrier: 
* [ ] If the file being requested over HTTP is currently being rebuilt by bikeshed, stall the HTTP request until the build has completed. Builds on android can take a while, so you may otherwise serve a stale version for quite some time, and multi-tasking to your background termux console to just to see if bikeshed is done is cumbersome.
* [ ] if the HTTP request is for `localhost:8000/css-foo/` and `css-foo/Overview.html` exists, serve that. Less typing, more happy.
* [ ] Allow `bikeshed serve` (and the underlying `bikeshed spec` and `bikeshed watch`) to take multiple files as a parameter, generating all of them, so if you're working on a set of specs, you don't have to constantly stop and start bikeshed to switch which spec it is re-building.
* [ ] If `bikeshed serve` (and `bikeshed spec` and `bikeshed watch`) is run without argument, first try (as now) to find a `.bs` file in the current directory, but if that fails, run in on `*/*.bs/`. That way, I can just `cd csswg-drafts && bikeshed serve` and off I go.
* [ ] When serving multiple files, process autolinks differently: if I `bikeshed serve css-foo/Overview.bs css-bar/Overview.bs` and css-foo has some auto-links that point to css-bar, make them point to the local copy of css-bar rather than the canonical one, making offline work a breeze.

Let me know if you'd rather have these tracked as separate issues.

**Comment by frivoal** [comment]
Also, after leaving `bikeshed serve` accidentally on for half a day on my phone, I am happy to report that this **does not** drain the battery when sitting idle, and had no measurable effect. 👍
