### ISSUE TITLE
auto-generated Dependencies section?

### ISSUE THREAD

**Issue by equalsJeffH** [tabatkins/bikeshed#937]
Various specs have a (manually-generated) "Dependencies" (or equivalent) section towards the "front" of the spec so readers know what kind of things to expect later on (e.g., https://www.w3.org/TR/2016/REC-webstorage-20160419/#dependencies).  

Though, bikeshed auto-generates backmatter that essentially duplicates said "dependencies" sections, e.g.: https://www.w3.org/TR/webauthn/#index-defined-elsewhere .

Perhaps bikeshed could have a directive indicating whether to place `#index-defined-elsewhere` in frontmatter or in backmatter?

**Comment by tabatkins** [comment]
While I definitely *could* free up the index generation a bit so it can be moved around to elsewhere in the document, I highly doubt that editors will generally consider it an improvement over their existing "Dependencies" sections. They're usually hand-crafted to refer to the most significant dependencies, with prose talking about them, rather than just a bare listing of every single external reference used in the entire spec.

Also, those "Dependencies" sections are mostly an artifact of the older spec generators being unable to provide good cross-spec linking and reference checking.  For the most part they can be removed in modern Bikeshedded specs.

**Comment by domenic** [comment]
> Also, those "Dependencies" sections are mostly an artifact of the older spec generators being unable to provide good cross-spec linking and reference checking. For the most part they can be removed in modern Bikeshedded specs.
