### ISSUE TITLE
missing-example-ids flags examples in boilerplate includes

### ISSUE THREAD

**Issue by inexorabletash** [tabatkins/bikeshed#992]
Given
```html
<pre class=metadata>
...
Group: webplatform
Complain About: missing-example-ids yes
...
</pre>
```
I get the output:
```
WARNING: Example needs ID:
<div class="example">
        <p>This is an example of an informative example.</p>
    </div>
```
... which is coming from `bikeshed/boilerplate/webplatform/footer.include`

**Comment by mkruisselbrink** [comment]
Seems #977 only fixed this for one specific footer.include, leaving all the group specific includes still broken...

**Comment by inexorabletash** [comment]
Seeing this again: https://github.com/w3c/web-locks/pull/101

```
Group: webapps
Complain About: missing-example-ids yes
```

cc: @saschanaz

**Comment by tabatkins** [comment]
I'd accidentally missed adding the boilerplate folder to the update-cleanup code that removes deleted files, so all the `footer.include` files I removed (in favor of the one good version in the `/w3c` folder) were getting kept around. Published a new bikeshed version earlier today that fixes this, so once you `pip install --upgrade bikeshed` (or run your GH action again, since it fresh-installs each time), this problem should go away.

**Comment by inexorabletash** [comment]
Thanks @tabatkins !
