### ISSUE TITLE
"LINK ERROR: No 'property' refs found for 'width' with spec 'mediaqueries-4'."

### ISSUE THREAD

**Issue by SimonSapin** [tabatkins/bikeshed#995]
The CSSOM draft has source code like:

```html
<table class="complex data" spec=mediaqueries-4>
 <thead>
  <tr>
   <th>Media Feature
   <th>Serialization
 <tbody>
  <tr>
   <td>'width'
   <td>...
  <tr>
   <td>'height'
   <td>...
```

Bikeshed warns:

```
LINK ERROR: No 'property' refs found for 'width' with spec 'mediaqueries-4'.
<a class="property" data-link-type="propdesc" data-lt="width" data-link-spec="mediaqueries-4">width</a>
LINK ERROR: No 'property' refs found for 'height' with spec 'mediaqueries-4'.
<a class="property" data-link-type="propdesc" data-lt="height" data-link-spec="mediaqueries-4">height</a>
LINK ERROR: No 'property' refs found for 'color' with spec 'mediaqueries-4'.
<a class="property" data-link-type="propdesc" data-lt="color" data-link-spec="mediaqueries-4">color</a>
```

This is a regression from:

* https://drafts.csswg.org/date/2016-09-28T02:20:48/cssom/#serialize-a-media-feature-value
* https://hg.csswg.org/drafts/file/6f73506d3898/cssom/Overview.bs#l377

**Comment by tabatkins** [comment]
I suspect this is caused by my "prefer property refs over descriptor refs when matching a propdesc autolink" code working badly - I suspect it's seeing that the result set contains both props and descs, throwing away the descs, then filtering away all the props and failing to autolink.

Instead, I should be trying to look for property refs, then if that fails, try to look for desc refs.

**Comment by tabatkins** [comment]
Ah, found the issue, it's not at all what I thought.

The problem here is that I have a link-default saying that CSS2.2 is the correct source for the "width" property.  (And the "height" property, and that Color3 is the correct source for the "color" property.)  The code that responds to link-defaults then says "hey, 'propdesc' is compatible with 'property', so you probably meant to ask for that; I'll just correct your linkType for you". It then searches for a property named 'width' in MQ, and doesn't find it.

If I remove that link-default, it complains that a plain `'width'` might be the property, or the @media descriptor, or the @viewport descriptor.  And this complaint happens in every single spec that references the 'width' property.  (Who thought it was a good idea to have several different namespaces under a single syntax? Whoever first started editing CSS specs with this preprocessor format, I guess.)

There are a few ways I could fix this, but none of them are *great*. I think the best right now is to just leave it as it is, and have CSSOM manually specify `'@media/width'` (as it now does).
